### ISSUE TITLE
Missing filter support for BoolQuery

### ISSUE THREAD

**Issue by kukulich** [ruflin/Elastica#1000]
See https://www.elastic.co/guide/en/elasticsearch/reference/2.0/query-dsl-bool-query.html

Filtered query is deprecated since 2.0.0-beta1, see https://www.elastic.co/guide/en/elasticsearch/reference/2.0/query-dsl-filtered-query.html

**Comment by ruflin** [comment]
@kukulich Thanks for bringing this up. We should add setFilter in our BoolQuery and mark Filtered Query as deprected. Any chance you could open a PR with that?

**Comment by kukulich** [comment]
It's difficult for me because I work on Windows7 and don't have any experiences with docker yet.

**Comment by ruflin** [comment]
No docker experience shouldn't be the issue as it should "just" work but I see the problem that you can't use the Makefile.

At the same time, you can also run tests without the hole docker setup, but need to have elasticsearch running locally. Have a look at this lines: https://github.com/ruflin/Elastica/blob/master/Makefile#L50

**Comment by kukulich** [comment]
Ok, I will try to prepare PR :)

**Comment by ruflin** [comment]
Cool, thanks.

**Comment by kukulich** [comment]
https://github.com/ruflin/Elastica/pull/1006

**Comment by kukulich** [comment]
Solved by https://github.com/ruflin/Elastica/pull/1006.
