### ISSUE TITLE
Use POST to send bulk requests

### ISSUE THREAD

**Issue by hakman** [ruflin/Elastica#1010]
A RESTful design uses PUT for updates and POST for create. Elastica uses the bulk API to create new documents:
https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Bulk.php#L356

Would it be OK to change the way Elastica sends bulk requests from PUT to POST?
Elasticsearch docs also mention POST as the method for sending bulk requests, though the spec allows both:
http://www.elastic.co/guide/en/elasticsearch/reference/master/docs-bulk.html

**Comment by damienalexandre** [comment]
Good point. No reason to use PUT here, but elasticsearch handle them [exactly the same](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/rest/action/bulk/RestBulkAction.java).

The official PHP client is also [using POST](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Endpoints/Bulk.php#L80).

**Comment by ewgRa** [comment]
I think you right and it must be synced and POST more right in this case, so +1 for POST.

@hakman Did you face with real problem when PUT used? Or there is no something behind?

**Comment by hakman** [comment]
We have a product that works as a proxy for Elasticsearch to accept and parse logs.
I am writing some examples for that using various languages and libs. One of them is Monolog and had trouble shipping logs with it, because of this issue.

We are also modifying our proxy, but thought this might help others in the future.

**Comment by otisg** [comment]
+1 for supporting POST

**Comment by ruflin** [comment]
I remember there was a reason we used PUT, but I think it was related to one of the deprecated transports. So +1 on this change.

**Comment by ruflin** [comment]
Closing as https://github.com/ruflin/Elastica/pull/1011 was merged.
