### ISSUE TITLE
\Elastica\Aggregation\TopHits::setSource() : wrong signature

### ISSUE THREAD

**Issue by mfn** [ruflin/Elastica#1012]
It's the same issue as https://github.com/ruflin/Elastica/issues/818 ; `_source` can be set to false in the ES API, but not with this client.

The [TopHits](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-metrics-top-hits-aggregation.html) documentation doesn't mention it explicitly but refers to [Soure Filtering documentat](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-request-source-filtering.html) which documents it.

**Comment by ewgRa** [comment]
Do you want to contribute? :)

**Comment by mfn** [comment]
Sorry don't plan at the moment, too busy!

**Comment by ruflin** [comment]
@mfn Thanks for the reporting. I opened https://github.com/ruflin/Elastica/pull/1015 to fix it. Side note here: It is always possible to pass a bool other other params by using setParam directly instead of setSource.
