### ISSUE TITLE
filtered query should not throw error

### ISSUE THREAD

**Issue by yehosef** [ruflin/Elastica#1018]
In Elastica\Query\Filtered it throws an error - "Use BoolQuery instead".

This is still supported as of elasticsearch 2.1 and I assume will be until at least version 3.  This should not throw an exception.

As they say in the blog post https://www.elastic.co/blog/better-query-execution-coming-elasticsearch-2-0

>Note that the query DSL is still backward compatible in spite of this change: if you try to run a filtered query, it will parse as a bool query internally. However, we would encourage you to migrate to the new syntax as the filtered query will be removed in a future release.

This is a relatively simple remapping on their part.  I don't think Elastica needs to be more zealous in this matter than Elastic is - supporting it will ease migration to Elastica 3.  A depreciated notice is fine.

**Comment by yehosef** [comment]
nevermind - I realize this is due to my error settings and depreciated warnings.  move along!

**Comment by ruflin** [comment]
@yehosef I just had a look at this PR and I don't think we throw an exception, only error. Could this be your error handling?

**Comment by ruflin** [comment]
@yehosef Ah, just saw your comment a bit too late :+1:
