### ISSUE TITLE
Suggested deprecation of the Filtered query doesn't work with Graylog servers

### ISSUE THREAD

**Issue by lynx-ripe** [ruflin/Elastica#1026]
We use the Elastica\Query\Filtered to query Graylog servers. The upgrade to the recent ruflin/elastica version (2015-12-13 20:27:31 -> 2015-12-19 20:49:34) causes the following deprecation warning:

    Use BoolQuery instead. Filtered query is deprecated since ES 2.0.0-beta1 and this class will be removed in further Elastica releases.

However the suggested migration to BoolQuery (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-filtered-query.html) doesn't work with our Graylog servers:

    SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; 
    shardFailures {[hx0OL0t0QHGFSKWU4cD2yg][graylog2_mellon_10][0]: RemoteTransportException[[es_node_es02.central.prod-logging.xxx][inet[/172.16.12.39:9300]][indices:data/read/search[phase/query]]]; nested: 
    SearchParseException[[graylog2_mellon_10][0]: from[-1],size[-1]: Parse Failure
    [Failed to parse source [{"query":{"bool":{"filter":[{"and":[{"term":{"level":6}},{"range":{"timestamp":{"gte":"2015-12-29 22:00:00.000","lte":"2015-12-30 22:00:00.000"}}},{"term":{"streams":"559e6f97498e4cfd705043ad"}}]}]}},"sort":{"timestamp":"asc"}}]]]; nested: 
    QueryParsingException[[graylog2_mellon_10] bool query does not support [filter]]

According to this thread: https://discuss.elastic.co/t/elasticsearch-query-does-not-support-filter/36554 the bool query with filter is only available in Elasticsearch 2.x. Which version of ruflin/elastica can be used to stay compatible with the existing Graylog servers?

**Comment by ruflin** [comment]
I assume Graylog is using an elasticsearch version previous to 2.0. All version of Elastica prior to 3.0 are compatible with elasticsearch 1.*

**Comment by lynx-ripe** [comment]
Sorry, it doesn't work for us - at least with the "dev-master" branch:

1) we update the composer lock, it updates ruflin/elastica c000d5d => a8b0b6b;
2) our code stops working due to the following deprecation error in the Elastica\Query\Filtered:
    Use BoolQuery instead. Filtered query is deprecated since ES 2.0.0-beta1 and this class will be removed in further Elastica releases.
3) we switch to the BoolQuery as the code suggests;
4) our code stops working with our Graylog servers, we get 
Parse Failure [Failed to parse source [{"query":{"bool":{"filter":[{"term":{"level":6}},{"range":{"timestamp":{"gte":"2016-01-20 22:00:00.000","lte":"2016-01-21 22:00:00.000"}}},{"term":{"streams":"56016df7e4b039e60c641ce6"}}]}},"sort":{"timestamp":"asc"}}]]]; nested: QueryParsingException[[graylog2_prod_2] bool query does not support [filter]]

Please suggest how can we continue using ruflin/elastica with our Graylog servers.

**Comment by ewgRa** [comment]
@lynx-ripe can you show code?

can you show your ES version?

**Comment by ewgRa** [comment]
I think your ES version < 2, so, in 1.7 there is no filter in bool query - https://www.elastic.co/guide/en/elasticsearch/reference/1.7/query-dsl-bool-query.html

This is why you have problem. You try use Elastica that compatible with ES >= 2 on ES < 2

**Comment by lynx-ripe** [comment]
ruflin says that "All version of Elastica prior to 3.0 are compatible with elasticsearch 1.*". But our experiments show that the master branch is not compatible with ES < 2 anymore. Which branch should we use to stay compatible with ES < 2?

**Comment by ewgRa** [comment]
Master branch have latest changes, so latest tags created from master branch. Elastica tags 2.x compatible with ES 1.x

You can check in readme file of tag which one version Elastica it support.

**Comment by ruflin** [comment]
@lynx-ripe As @ewgRa pointed out, the master branch is the most recent version. In general I do not recommend to work based on master as it changes on a daily base. I'm closing this is issue as I think it is answered by the comment from @ewgRa above. Please reopen if this is not the case.
