### ISSUE TITLE
elastica version 3.0 can support elasticsearch below 2.0?

### ISSUE THREAD

**Issue by pangminfu** [ruflin/Elastica#1027]
Hi,

is it posible to use elastica v3.0 on elastic search below 2.0? which elastica version is stable to use on production?

**Comment by ruflin** [comment]
For elasticsearch below 2.0 Elastica 2.3.1 should be used. Elasticsearch 2.0 has many BC breaks, so has Elastica to accommodate for it. For elasticsearch >= 2.0 Elastica 3.0.1 must be used.

**Comment by ruflin** [comment]
Closing this as I think the question was answered. Please reopen if needed.
