### ISSUE TITLE
Should 3.0.1 get more than a bugfix bump? it upped the ES server dependency

### ISSUE THREAD

**Issue by ahungry** [ruflin/Elastica#1029]
First off, thanks for the great project.  However, I noticed that release 3.0.1 doesn't seem to work with an install of 2.0.0 ElasticSearch server (which is what 3.0.0 specifies as the dependency).

Then, 3.0.1 ups the requirement to 2.1.1, which is not a backwards compatible change - shouldn't it have went up to 4.0.0?

**Comment by ruflin** [comment]
@ahungry The elasticsearch version mentioned in the release is the one it was tested with. As there were no major changes from 3.0.1 to 3.0.0 I would be surprised if it doesn't work anymore with elasticsearch 2.0. Can you provide some more details on what is not working anymore?

**Comment by ahungry** [comment]
It may have been an unrelated issue, please disregard, I believe you're correct
