### ISSUE TITLE
Snake Case vs Camel Case

### ISSUE THREAD

**Issue by designermonkey** [ruflin/Elastica#1032]
I'm really confused as to why the QueryBuilder uses a snake case format, when all of the Filters and Queries use a camel case format?

Should these not be the same?

(using v2.3.1)

**Comment by ruflin** [comment]
I remember there was a good reason for that but not sure which one it was. Best to answer is probably @webdevsHub

**Comment by webdevsHub** [comment]
QueryBuilder uses snake case because Elasticsearch query names (like `{ "match_all": {} }`) use snake case too. So QueryBuilder acts like you are writing Elasticsearch JSON with autocomplete.

**Comment by ruflin** [comment]
Thanks @webdevsHub for jumping in here. Makes sense. @designermonkey Closing this issue as I think the question was answered. In case the intention of the issue was to actually change the current implementation, please reopen for discussion.

**Comment by designermonkey** [comment]
Yeah no problem. Thanks for the input guys; It just took me by surprise that's all.
