### ISSUE TITLE
minimum_should_match query

### ISSUE THREAD

**Issue by christiancannata** [ruflin/Elastica#1034]
Hi,
How can I do a "minimum_should_match" query with Elastica?
This is a query that I am going to do, but I've more problem to compose it with Elastica classes:

``` javascript
{
   "query":{
      "filtered":{
         "query":{
            "bool":{
               "should":[
                  {
                     "multi_match":{
                        "query":"my search term",
                        "type":"cross_fields",
                        "fields":[
                           "name"
                        ],
                        "minimum_should_match":"30%"
                     }
                  }
               ]
            }
         }
      }
   }
}
```

**Comment by ruflin** [comment]
@christiancannata Can you post what you have so far or which part exactly is not working?

**Comment by christiancannata** [comment]
Unfortunately I don't know how make this query with elastica classes, I can make only simple match or multi match query, I don't understand how can add minimum should match filter with cross fields

**Comment by ruflin** [comment]
For the multimatch queries, best have a look at the tests here as examples: https://github.com/ruflin/Elastica/blob/master/test/lib/Elastica/Test/Query/MultiMatchTest.php

For the Bool Queries you can find examples here: https://github.com/ruflin/Elastica/blob/master/test/lib/Elastica/Test/Query/BoolQueryTest.php

Then it should be possible to combine it. In case some fields are missing, use setParam(...)

**Comment by Tobion** [comment]
This issue can be closed. minimum_should_match exists on multi_match as setter, see https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Query/MultiMatch.php#L102
And with #1242 it also exists on bool query.

**Comment by ruflin** [comment]
Closing based on the feedback from @Tobion . Please reopen if you think it is not solved.
