### ISSUE TITLE
"Bool" is a reserved word as of PHP 7

### ISSUE THREAD

**Issue by schmeiserd** [ruflin/Elastica#1035]
Elastica\Filter\Bool & Elastica\Query\Bool should be renamed for PHP 7 compatibility (see https://secure.php.net/manual/en/reserved.other-reserved-words.php).
(Even if I'm not sure if reserved words are case-sensitive at least symfony shows a deprecation warning for these classes...)

**Comment by Lumbendil** [comment]
They are already deprecated and classes have been introduced to replace them.

https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Filter/BoolFilter.php
https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Query/BoolQuery.php

**Comment by ruflin** [comment]
See also https://github.com/ruflin/Elastica/issues/1014 and https://github.com/ruflin/Elastica/issues/918 Closing this issue as I think it is resolved. Please reopen if it is a different issue.

**Comment by schmeiserd** [comment]
I see, my bad! :)
Are there any plans for the next stable release yet?

**Comment by ruflin** [comment]
3.1 is planned soonish with the most recent changes. Anything you need urgently since 3.0.1?

**Comment by schmeiserd** [comment]
No urgencies, thanks for your information! :)
