### ISSUE TITLE
Are Elastica versions tied to specific ES versions?

### ISSUE THREAD

**Issue by reedy** [ruflin/Elastica#1036]
https://github.com/ruflin/Elastica/tree/2.2.1 needs 1.7.1
https://github.com/ruflin/Elastica/tree/2.3.1 needs 1.7.3

Is it only those versions? Or are "newer" point releases ok?

i.e What version would I need to use with ES 1.7.4?

**Comment by ruflin** [comment]
All 1.7 versions and even previous versions should not be a problem with 2.3.*. The version that is stated as compatible is the one that was tested. In general as long as there are no major changes on the elasticsearch side, Elastica releases are compatible with previous and later release. Best for 1.7.4 is definitively 2.3.1

**Comment by reedy** [comment]
Perfect, cheers! :)
