### ISSUE TITLE
Add sanity checks for aggregations

### ISSUE THREAD

**Issue by greg0ire** [ruflin/Elastica#1043]
I'm new to elastic search, and I'm playing with aggregations at the moment. The first bug that hits me quite hard is when trying to use `Cardinality` : I get a big error message telling me my query is invalid. When I realized that the name of the aggregation and the field are different things, I understand my error and use `setField`, but keep wondering why not simply have such a constructor for `Cardinality` (or event `AbstractSimpleAggregation` or higher) : `public function __construct($name, $field)`.

After reading the documentation, I see that aggregations can also be generated with scripts. Maybe a sanity check could be done at some point to make sure that one at least is provided?

**Comment by ewgRa** [comment]
@greg0ire It can be done like in toArray here https://github.com/ruflin/Elastica/blob/f124e598228a6b8a6c249fde6afc07ea7eb1a771/lib/Elastica/Query/Terms.php

Can you create pull request for this?

**Comment by greg0ire** [comment]
Sure! Does it make sense to also check that only one of the parameters are set?

**Comment by greg0ire** [comment]
The doc: 

> When both field and script settings are configured for the aggregation, the script will be treated as a value script. 

So no, it does not make sense, apparently :)
