### ISSUE TITLE
URL cannot include query-string parameters

### ISSUE THREAD

**Issue by olchick** [ruflin/Elastica#1046]
I'm trying to use the new Amazon Elasticsearch service however, I'm getting the following error when trying to use update document:

`When Content-Type:application/x-www-form-urlencoded, URL cannot include query-string parameters (after '?'): '/users/user/1/_update?version=2&retry_on_conflict=0'`

Also I found this post about [Amazon Elasticsearch Service Limits](http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-limits.html)

So it seems the Elasticsearch service doesn't like to receive query-string parameters.

I saw code in updateDocument function and there is always set $options even if I don't want use their. 

I use Elastica v.2.3.1

**Comment by ruflin** [comment]
Passing this params per query is default in elasticsarch as far as I know: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#_parameters_3 Does Amazon have any recommendations what to do in these cases? This seems more to be an issue with the implementation of elasticsearch in AWS then Elastica. 

The improvement that could be made probably on the Elastica side is trying to not set any default params if none set here: https://github.com/ruflin/Elastica/blob/f35835e8308ec9e0b62842155603c32118a2ffc6/lib/Elastica/Client.php#L337
