### ISSUE TITLE
MLT "like" value

### ISSUE THREAD

**Issue by sebesvn** [ruflin/Elastica#1050]
Hey all,

Wondering if this from the Elasticsearch doc:

```
{
    "more_like_this" : {
        "fields" : ["name.first", "tweet"],
        "like" : [
        {
            "_index" : "marvel",
            "_type" : "quotes",
            "doc" : {
                "name": {
                    "first": "Ben",
                    "last": "Grimm"
                },
                "tweet": "You got no idea what I'd... what I'd give to be invisible."
              }
        },
        ],
        "min_term_freq" : 1,
        "max_query_terms" : 1,
        "minimum_should_match" : 60
    }
}
```

is yet implemented?
The bit I am struggling with is the "doc" section of the "like".

My code is as follow:

```
$moreLikeThis = (new Query\MoreLikeThis())
    ->setFields([
        'name.first',
        'tweet'
    ])
    ->setLike((new Document())
        ->setIndex('myIndexName')
        ->setType('myTypeName')
        ->setData([
            'tweet'      => 'Foo',
            'name' => [
                'first' => 'Bar',
                'last' => 'Test'
            ]
        ])
    )
    ->setMinTermFrequency(1)
    ->setMinDocFrequency(1)
    ->setMinimumShouldMatch(60);
```

But it looks like the query is not generated properly. Here is what I get when I var_dump() Request::toString():

`string(398) "{"path":"myIndexName\/myTypeName\/_search","method":"GET","data":{"query":{"more_like_this":{"fields":["name.first","tweet"],"like":{"_id":"","_type":"myTypeName","_index":"myIndexName"},"min_term_freq":1,"min_doc_freq":1,"minimum_should_match":60}}},"query":{"search_type":"count"},"connection":{"config":[],"host":"localhost","port":9200,"enabled":true}}"`

The "doc" section if definitely missing? Am I not using it properly?

**Comment by ruflin** [comment]
For comparison I copy here the JSON that is part of the request you posted above:

```
{  
   "more_like_this":{  
      "fields":[  
         "name.first",
         "tweet"
      ],
      "like":{  
         "_id":"",
         "_type":"myTypeName",
         "_index":"myIndexName"
      },
      "min_term_freq":1,
      "min_doc_freq":1,
      "minimum_should_match":60
   }
}
```

**Comment by ruflin** [comment]
In your code above you post an empty document to `setLike(...)`. Can you instead put there a document with the content inside that you use under `->setData(...)`?

**Comment by sebesvn** [comment]
I'm not sure I'm following you.
In `setLike(...)` I post a Document object on which I call `setData(...)` which, if I understand correctly, is supposed to populate the document. So in the end `setLike(...)` receives a non-empty document populated with my values.
Thanks for the help on this.

**Comment by ruflin** [comment]
@sebesvn Sorry, I missed one bracket in your code above. Now everything makes more sense :-) I was confused as you could set all this also directly with params in the constructor of Document() http://elastica.io/api/classes/Elastica.Document.html#method___construct

So what your trying should be supported and working. An example test can be found here: https://github.com/ruflin/Elastica/blob/master/test/lib/Elastica/Test/Query/MoreLikeThisTest.php#L91

The difference is that this document is received from elasticsearch. So I'm curious if there are some fields missing. Could you post the result of `print_r($moreLikesThis->toArray())` after you created the query?

**Comment by sebesvn** [comment]
@ruflin No worries :)

There is the output of `print_r($moreLikesThis->toArray())` right after I create it:
```
Array
(
    [more_like_this] => Array
        (
            [fields] => Array
                (
                    [0] => name.first
                    [1] => tweet
                )

            [like] => Array
                (
                    [_id] => 
                    [_type] => myTypeName
                    [_index] => myIndexName
                )

            [min_term_freq] => 1
            [min_doc_freq] => 1
            [minimum_should_match] => 60
        )
)
```

So the `like` section is generated since the `_index` and `_type` are here but the `doc` section inside of it is missing.
Indeed that document is not received from ES but provided directly as an input, might that be the problem? It should work though.

**Comment by ruflin** [comment]
I think the problem could be that there is no id. The toArray() function checks for an id: https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Query/MoreLikeThis.php#L220 Can you add an id to your document and see if it works? TBH not 100% sure why we are checking for the _id.

**Comment by sebesvn** [comment]
Going to try to add a "fake" id to see if it changes anything, but in the meantime I've updated my previous post.
Basically: `_id` (which is empty here) should be removed and replaced by `doc`, since I am not comparing a document received from ES but provided directly as an input.

**Comment by sebesvn** [comment]
I'm afraid that was not it, here is the output now:
```
Array
(
    [more_like_this] => Array
        (
            [fields] => Array
                (
                    [0] => name.first
                    [1] => tweet
                )

            [like] => Array
                (
                    [_id] => fake
                    [_type] => myTypeName
                    [_index] => myIndexName
                )

            [min_term_freq] => 1
            [min_doc_freq] => 1
            [minimum_should_match] => 60
        )
)
```
So the `_id` is populated but still no `doc` section. And I'm not sure it would work even if the `doc` section was here since ES would try to fetch a document from the index if `_id` is here.

We really should have 2 scenarios:
MLT on a document already in the index: provide only `_id` in the `like`
MLT on a document provided as an input (my case): provide only `doc` in the `like`

**Comment by sebesvn** [comment]
By the way is I print_r() the Document object only here is what I get:
```
Array
(
    [_id] => fake
    [_type] => myTypeName
    [_index] => myIndexName
    [_source] => Array
        (
            [tweet] => Foo
            [name] => Array
                (
                    [first] => Bar
                    [last] => Test
                )
        )
)
```
I think that MLT on a document provided as an input is actually not implemented.

`MoreLikeThis::toArray()` could look something like this:
```
public function toArray()
{
    $array = parent::toArray();
    if (isset($array['more_like_this']['like']['_id'])) {
        $doc = $array['more_like_this']['like'];
        $doc = array_intersect_key($doc, array('_index' => 1, '_type' => 1, '_id' => 1));
        $array['more_like_this']['like'] = $doc;
    } elseif (isset($array['more_like_this']['like']['_source'])) {
        $doc = $array['more_like_this']['like'];
        $doc['doc'] = $array['more_like_this']['like']['_source'];
        $array['more_like_this']['like'] = $doc;
    }
    return $array;
}
```

**Comment by ruflin** [comment]
@sebesvn It seems like you are right and MLT currently only works with existing ES objects :-( The code provided by you above looks good to me. Could you open a PR with this change and perhaps also add small test? I would probably add a comment line in the code above to explain what the two cases are.

**Comment by sebesvn** [comment]
Hi @ruflin 

#1051

**Comment by ruflin** [comment]
@sebesvn Thanks. See comment.

**Comment by ruflin** [comment]
Closing this one as #1051 got merged.
