### ISSUE TITLE
Query by array of id result return doesn't sort according to the array of id passed in

### ISSUE THREAD

**Issue by pangminfu** [ruflin/Elastica#1052]
Hi,

I'm using elastica 3.0, I had an issue of the sorting order when query by array of id and the result return is not the same order as the array of id passed in

**Comment by ruflin** [comment]
Can you provide some code and examples?

**Comment by pangminfu** [comment]
this is my query
        `$query = new Query();
        
        $query->setSize(count($articleIDs));
        
        $qb = new \Elastica\Query\Ids();
        
        foreach ($articleIDs as $articleID) {
            $qb->addId($articleID);
        }
        $query->setQuery($qb);`

**Comment by ruflin** [comment]
I think you got the answer here: http://stackoverflow.com/questions/35769643/elasticsearch-query-by-array-of-id-result-returned-is-not-sorted-by-the-array-of  Please don't double post and for questions please use the elastica google group, not the Github issues: https://groups.google.com/forum/#!forum/elastica-php-client
