### ISSUE TITLE
Meeting / Discussion about direction

### ISSUE THREAD

**Issue by merk** [ruflin/Elastica#1053]
In #944 @ruflin invited anyone available to take part in a discussion about progressing the library. I have a few minutes spare and wanted to note down a few talking points.

I see any basic implementation of Elastica into an application as generally requiring up to 3 different things for search:
1. Being able to manage index metadata and creation or modification to indexes as the application changes. #810
2. Populating indexes with data, either in bulk or as changes happen
3. Search indexes in any supported way and get results back (optionally also having access to the original objects that were indexed) #811 #1017

**Comment by ruflin** [comment]
I think that is a good high level summary. There is an additional part which is about providing access to elasticsearch stats and changing elasticsearch configuration. But these are less common use cases.

**Comment by merk** [comment]
Sorry @ruflin, I've been flat out and havent had an opportunity to organise time for a discussion.

Do you have any time over the next few days?

**Comment by ruflin** [comment]
@merk We can try, but the next few days are a little bit unpredictable on my side as a new family member will join us ;-)

**Comment by merk** [comment]
Congrats! Lets leave it a while then. I've got a bit of spare time and I'm trying to work out how to tackle point 1.

**Comment by ewgRa** [comment]
@ruflin Congrats :)

**Comment by merk** [comment]
With #1017 merged, I've pushed a bare bones test of what it might look like to implement Doctrine result processing that gives you access to the original doctrine objects in search results.

I expect this repository to also handle guessing of type properties based on doctrine metadata to help with #810, when we know what #810 might look like.

**Comment by ruflin** [comment]
@merk That is quite nice and compact.
