### ISSUE TITLE
Improvement: add lucene syntax

### ISSUE THREAD

**Issue by IgorDePaula** [ruflin/Elastica#1054]
The elasticsearch permit the use of lucene syntax, but I tried and fails.

**Comment by ruflin** [comment]
By lucene syntax you mean using it in query_string? Can you provide some examples that didn't work?

**Comment by IgorDePaula** [comment]
I tried with multimach because I need search in many fileds. By lucene syntax I mean "+field:value -field:value". I see this in a book about elasticsearch.

**Comment by ruflin** [comment]
Can you try if that works in QueryString queries? It could be an escaping problem on the Elastica side. Please also provide a code example. That makes it easiest to reproduce and test.

**Comment by IgorDePaula** [comment]
Ok, I will try and the response I post here.

2016-03-11 11:52 GMT-03:00 Nicolas Ruflin <notifications@github.com>:

**Comment by IgorDePaula** [comment]
Ok, with querystring it works. Thanks.
