### ISSUE TITLE
Incompatible with PHP7

### ISSUE THREAD

**Issue by IgorDePaula** [ruflin/Elastica#1059]
I tried with PHP7, and received this error above. I tried update the lib, but without success.

```Fatal error: Uncaught Error: Call to undefined function Elastica\Transport\curl_init() in /var/www/html/uploadelastica/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php:208 Stack trace: #0 /var/www/html/uploadelastica/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php(50): Elastica\Transport\Http->_getConnection(true) #1 /var/www/html/uploadelastica/vendor/ruflin/elastica/lib/Elastica/Request.php(171): Elastica\Transport\Http->exec(Object(Elastica\Request), Array) #2 /var/www/html/uploadelastica/vendor/ruflin/elastica/lib/Elastica/Client.php(626): Elastica\Request->send() #3 /var/www/html/uploadelastica/vendor/ruflin/elastica/lib/Elastica/Index.php(514): Elastica\Client->request('test/test/', 'POST', Array, Array) #4 /var/www/html/uploadelastica/vendor/ruflin/elastica/lib/Elastica/Type.php(519): Elastica\Index->request('test/test/', 'POST', Array, Array) #5 /var/www/html/uploadelastica/vendor/ruflin/elastica/lib/Elastica/Type.php(88): Elastica\Type->request('test/', 'POST', Array, Array) #6 /var/www/html/uploadel in /var/www/html/uploadelastica/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php on line 208```

**Comment by ruflin** [comment]
This looks more like your php7 installation doesn't have curl installed.

**Comment by IgorDePaula** [comment]
I was careful to install this library, but still did not work.

2016-03-14 4:24 GMT-03:00 Nicolas Ruflin <notifications@github.com>:

**Comment by IgorDePaula** [comment]
You noticed that he is complaining that curl_init function is part of the
namespace Elastica when curl_init is part of the global namespace?

2016-03-14 9:52 GMT-03:00 principe.borodin@gmail.com <
principe.borodin@gmail.com>:

**Comment by ruflin** [comment]
How did you install Elastica? Composer? What does your autoloader look like?

**Comment by IgorDePaula** [comment]
Yes, installation by composer. And I used your autoload, of composer.
Em 15/03/2016 05:03, "Nicolas Ruflin" <notifications@github.com> escreveu:

**Comment by ewgRa** [comment]
try to run "php -i | grep curl" at your installation server. You must have something "php -i | grep curl
/etc/php5/cli/conf.d/20-curl.ini,
curl
" in answer.

It is definitely not installed php curl extension on server.

**Comment by IgorDePaula** [comment]
Yes, my system has the 20-curl.ini file.

2016-03-15 6:28 GMT-03:00 Evgeniy Sokolov <notifications@github.com>:

**Comment by ewgRa** [comment]
@IgorDePaula You can have it, but it can be disabled, or not used for php-fpm for example. You need to be sure that it is enabled.

**Comment by IgorDePaula** [comment]
```
igor@igor-GA-78LMT-USB3 ~$ php -i | grep curl
/etc/php/7.0/cli/conf.d/20-curl.ini,
curl
igor@igor-GA-78LMT-USB3 ~$
```

**Comment by IgorDePaula** [comment]
Sorry, anything do it works.

**Comment by ruflin** [comment]
@IgorDePaula In case some else finds this issue, perhaps you can post what the problem on your side was in the end and how you resolved it?
