### ISSUE TITLE
Elasticsearch is not running or is not healthy.

### ISSUE THREAD

**Issue by merk** [ruflin/Elastica#1068]
I am trying to set up the docker environment on OSX 10.11 with docker toolbox.

The Makefile run target fails with the following message:

```
➜  Elastica git:(resultset-builder) make run RUN="make phpunit"
docker run -v /Users/tim/Sites/Elastica:/elastica ruflin/elastica make phpunit
Waiting on elasticsearch(elasticsearch:9200) to start................
Elasticsearch is not running or is not healthy.
Address: elasticsearch:9200

make: *** [run] Error 1
```

It is beyond my knowledge to debug further - It doesnt look like i can gain entry to the docker image ruflin/elastica without going through the entry point to debug why ES isnt starting?

**Comment by ruflin** [comment]
Just run it again. Sometime the waiting period is too low ... I should increase it.

**Comment by merk** [comment]
Doesnt seem to help, running it half a dozen times or waiting a few minutes between runs still results in the same error.

**Comment by merk** [comment]
It appears that the run target is not correct to get up and running: no matter how many times it runs it appears to me like the entrypoint script will fail. Could it be that the run target does not set up the appropriate containers required to run the tests? The documentation in CONTRIBUTING might need updating in that case.

Running the individual steps in the 'tests' target results in the test cases executing.

**Comment by ruflin** [comment]
Can you try to run `make tests` ?

**Comment by merk** [comment]
`make tests` or the individual steps in that target bring everything up, but the documentation in CONTRIBUTING.md talks about `make run` which doesnt work.

**Comment by ruflin** [comment]
Ok, I think I need to update the docs here :-(

**Comment by mtdavidson** [comment]
Just came across the same error `make tests` works no problem but no luck with the commands in `CONTRIBUTING.md`.

**Comment by ruflin** [comment]
Argh, I still didn't update the CONTRIBUTING.md :-( @mtdavidson Could you open a PR with the change?
