### ISSUE TITLE
php Notice in \Elastica\Index::getAliases()

### ISSUE THREAD

**Issue by aeytom** [ruflin/Elastica#1078]
If es index has no alias a php notice occurs (missing array index)

Line 437: `$data = $responseData[$this->getName()];`

Es 2.3.1
Elastica 3.1.1

**Comment by natelenart** [comment]
+1

Came to report this issue, but saw it's already here.

**Comment by ewgRa** [comment]
I think it is not about "If es index has no alias", it is about - "if there is no index with this name in ES".

Question is what to do in this case. Throw something like MissingIndexException, or just return empty array. Like this index haven't aliases.

**Comment by ruflin** [comment]
@aeytom Does this happen if you use an Alias name to create the index object and then use getAliases()?

**Comment by gbprod** [comment]
+1
Only happens if php `error_reporting` setting is set to `-1`
@ruflin I can create a pull request with a fix if you want

**Comment by ruflin** [comment]
Fixed in https://github.com/ruflin/Elastica/pull/1080
