### ISSUE TITLE
No search type for [scroll] 

### ISSUE THREAD

**Issue by Antoniossss** [ruflin/Elastica#1087]
I wanted to use scroll api to fetch some large ammount of data and hit this error.
`No search type for [scroll]`. I have found ou, that removing single line (commented one below)
\Elastica\Scroll#next()

```
    public function next()
    {
        $this->_saveOptions();

        $this->_search->setOption(Search::OPTION_SCROLL, $this->expiryTime);
        $this->_search->setOption(Search::OPTION_SCROLL_ID, $this->_nextScrollId);
//        $this->_search->setOption(Search::OPTION_SEARCH_TYPE, Search::OPTION_SEARCH_TYPE_SCROLL);
        $this->_setScrollId($this->_search->search());

        $this->_revertOptions();
    }

```

Fixes this issue. However i dont know what is the impact of removing this line to the rest of the system.

**Comment by ruflin** [comment]
@Antoniossss Which Elastica version and which Elasticsearch version are you using?

**Comment by Antoniossss** [comment]
@ruflin It is under the hood of CakePHP's ES plugin 
cakephp/elastic-search                1.0.x-dev 7a983d6
and the plugin has following dependencies:
requires
cakephp/cakephp ~3.2
ruflin/elastica ~3.1

**Comment by ruflin** [comment]
And which elasticsearch version are you using?

**Comment by Antoniossss** [comment]
2.3.1

**Comment by ruflin** [comment]
Hm, my first idea was that it is because of a new / old elasticsearch version, but not sure about this. Can you share a little bit more of your code?

**Comment by Antoniossss** [comment]
```
 /** @var Search $search */
        $search = $myTypeType->connection()->getIndex("myIndex")->createSearch($filtered);
        $search->setOption("size", "5000");
        $search->getQuery()->setFields(["_id"]);
        $scroll = $search->addType("myType")->scroll('10s');
        $ids = [];
        do {
            $scroll->next();
            $results = $scroll->current();
            foreach ($results->getResults() as $result) {
                $ids[] = $result->getId();
            }
        } while ($results->count() > 0);
```

**Comment by ruflin** [comment]
@Antoniossss I didn't have the time yet to look into this in detail. You could do me a big favor if you could create an integration test in our test suite with this and open a PR. Like this we directly see if it is related to an elasticsearch version or something else.

**Comment by Antoniossss** [comment]
@ruflin no rush with that, I am using modified sources for that. 

Sure, ill try to find some time to write test for that case.

**Comment by Antoniossss** [comment]
@ruflin 
As far as I can say there is no such search type (maybe not anymore)
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-type.html

SearchAPi requires only scroll_id to be provided and scroll=TTL nothing more.
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html

I had some troubles with test env so I did not add test case as promised.

**Comment by ruflin** [comment]
We should definitively do some refactoring here as count and scan are deprecated and completely removed in 5.0. Did you push a PR with the changes?

**Comment by ruflin** [comment]
BTW: What was the issue with the test env?

**Comment by Antoniossss** [comment]
@ruflin No, as I didnt know is this really the fix here or just my luck ;) It is not tested on v5 anyway. 

As for test environement I had some troubles with working docker container (Windows :P) So nothing Elastica specific.

**Comment by ruflin** [comment]
Oh, Windows :-) Feel free to open a PR without tests so someone else can potentially add them.

**Comment by Tobion** [comment]
Closing because this has been fixed with https://github.com/ruflin/Elastica/commit/9465a9111275df3d6dc31b1da63614d9edddddae#diff-224448d8b4c503195ecc00695250a1c4
