### ISSUE TITLE
[range] query does not support ["fieldname"] [index: "indexname"]

### ISSUE THREAD

**Issue by redayoub** [ruflin/Elastica#1088]
Hello,

I'm tryning to use range filter in my query but I get this message :

`
[range] query does not support [price_amount] [index: elane] 
`

```
$filters = new \Elastica\Filter\Bool();
$filters->addMust(new \Elastica\Filter\Term(['category.id' => $category]));

$range = new Elastica\Filter\Range();
$range->addField('price_amount', [$minPrice, $maxPrice]);
$filters->addMust($range);

$filteredQuery = new \Elastica\Query\Filtered($query_part, $filters);

$query = new \Elastica\Query();
$query->setQuery($filteredQuery);
```

When I perform the same query using a rest request it works : 

```javascript
POST /elane/ad/_search
{
    "query":{
        "filtered":{
            "filter":{
                "bool":{
                    "must":[
                        {
                            "term":{
                                "category.id":4
                            }
                        },
                        {
                            "range": {
                               "price_amount": {
                                  "from": 10,
                                  "to": 200000
                               }
                            }
                        }
                    ]
                }
            }
        }
    }            
}
```

FYI, I'm using FOSElasticaBundle. Any help please ?

**Comment by ruflin** [comment]
Which Elastica version and which Elasticsearch version are you using?

**Comment by redayoub** [comment]
I'm using elasticsearch 2.3.2 and  "friendsofsymfony/elastica-bundle": "dev-master#6206199", "ruflin/elastica": "3.1.1 as 2.99.0".

**Comment by ruflin** [comment]
Lets ignore the FOS bundle for the moment, as it looks like it doesn't play any role in the above code (correct me if I'm wrong). Side note: As far as I remember there are some issues with FOS and ES 2.0. Could have changed in the meantime.

Could you provide the following output here adding it after the lines above:

```
print_r($query->toArray());
```

It would be good to see how the structure generated by Elastica is different from the above.

**Comment by redayoub** [comment]
Same structure:

```php
Array ( 
	[query] => Array ( 
		[filtered] => Array ( 
			[filter] => Array ( 
				[bool] => Array ( 
					[must] => Array ( 
						[0] => Array ( 
							[term] => Array ( [category.id] => 4 ) 
						) 
						[1] => Array ( 
							[range] => Array ( [price_amount] => Array ( [0] => 1 [1] => 3 ) ) 
						) 
					) 
				) 
			) 
		) 
	)
)
```

**Comment by ruflin** [comment]
There is a different in the price_amount. The from / to stuff is needed. Can you try:

Replace
```
$range->addField('price_amount', [$minPrice, $maxPrice]);
```

with
```
$range->addField('price_amount', ["from:" $minPrice, "to": $maxPrice]);
```

**Comment by redayoub** [comment]
It's working, but with: 

`
$range->addField('price_amount', ["from" => $minPrice, "to" => $maxPrice]);
`

Thanks a lot.

**Comment by ruflin** [comment]
Good to hear. Will close the issue.
