### ISSUE TITLE
erreur 404 DOC 

### ISSUE THREAD

**Issue by r-leitao** [ruflin/Elastica#1095]
You have a problem in URL : http://elastica.io/api/classes/Elastica.Transport.AwsAuthV4.html

Can we have an example for use Elastica with a connection ElasticSearch AWS Please.

**Comment by ruflin** [comment]
I recently split up the API docs by version. The url for the latest one is: http://elastica.io/api/latest/classes/Elastica.Transport.AwsAuthV4.html

From where did you get the above version?

**Comment by r-leitao** [comment]
It's ok. 
Thank you for your prompt response
