### ISSUE TITLE
How to return only specific fields from entity using fos_elastica

### ISSUE THREAD

**Issue by olehismaylov** [ruflin/Elastica#1098]
Here is my finder
$finder = $this->container->get('fos_elastica.finder.index.type');
$result = $finder->find('string_to_find');
My entity consists of 20 properties and elastic has only 3 fields.
in $result I will have all 20 properties. How  I can have only these 3 properties which I do search on.
Generally I would like to know how I can handle properties  which will be in result variable?

here is config.yml
`persistence:model:  MyBundle\Entity\EntityName`

**Comment by ruflin** [comment]
@olehismaylov This looks more like an issue related to FOSElastica?

**Comment by Tobion** [comment]
Closing as this issue is not about Elastica.
