### ISSUE TITLE
[nested] failed to find nested object under path [variants] [index: msb_dev] 

### ISSUE THREAD

**Issue by ibasaw** [ruflin/Elastica#1102]
hi,

ruflin 3.2 + foselasticabundle dev-master + sylius 0.18 + ES 2.0

Don't have this error on sylius 0.17

    fos_elastica:
    clients:
        default: { host: %service_elastic_host%, port: %service_elastic_port%, logger: true }
    indexes:
        sylius:
            index_name: msb_%kernel.environment%
            client: default
            finder: ~
            settings:
                index:
                    analysis:
                          analyzer:
                              default:
                                  type: custom
                                  tokenizer: standard
                                  filter: [asciifolding, lowercase, my_ngram, my_filter, worddelimiter, en_stemmer]
                              my_analyzer_autocomplete:
                                  type: snowball
                                  tokenizer: lowercase
                                  filter: [my_ngram, my_filter, asciifolding]
                          filter:
                              my_ngram:
                                  type: nGram
                                  min_gram: 4
                                  max_gram: 15
                              my_filter:
                                  type: length
                                  min: 0
                                  max: 2000
                              en_stemmer:
                                  type: stemmer
                                  language: light_english
                              worddelimiter:
                                  type: word_delimiter
            types:
               product:
                   mappings:
                       name:
                           type: string
                       description: ~
                       slug: ~
                       color: ~
                       price:
                          type: integer
                       channels:
                          type: string
                          index: not_analyzed
                       taxons:
                          type: string
                          index: not_analyzed
                       size: ~
                       made_of:
                          type: string
                          index: not_analyzed
                   persistence:
                       driver: orm
                       model: Sylius\Component\Core\Model\Product
                       model_to_elastica_transformer:
                          service: sylius.search.transformers.model.product
                       provider: ~
                       listener: ~
                       finder: ~

               search_log:
                  mappings:
                      search_term: ~
                      ip_address: ~

**Comment by ruflin** [comment]
As these config files are not supported by Elastica I assume the above problem is not related to Elastica. Please open the issue in the relate project. Also provide there some more information if possible
