### ISSUE TITLE
Is any plan to update for elasticsearch 2.3.3

### ISSUE THREAD

**Issue by eit** [ruflin/Elastica#1116]
just wondering do you have any plan about 2.3.3?

**Comment by ruflin** [comment]
Currently not. There is a 2.3 branch in case someone wants to backport stuff to 2.3 but so far all "promised" contributions didn't happen. Any specific thing you are looking for?

**Comment by Antoniossss** [comment]
@eit works for me with ES2.3.3

**Comment by eit** [comment]
Exactly, I have upgraded 2.3.3 already. It works. Thank you guys.

**Comment by ruflin** [comment]
@eit Rereading the post I realised you referred to elasticsearch and not Elastica. So all should be working with the most recent Elastica release. Great to hear it works.
