### ISSUE TITLE
Elastic Search Server Down

### ISSUE THREAD

**Issue by nirajan-panthee** [ruflin/Elastica#1117]
I am getting

`[2016-06-17 07:15:12] request.CRITICAL: Uncaught PHP Exception Elastica\Exception\Connection\HttpException: "Couldn't connect to host, Elasticsearch down?" at /var/www/project/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php line 167 {"exception":"[object] (Elastica\\Exception\\Connection\\HttpException(code: 0): Couldn't connect to host, Elasticsearch down? at /var/www/project/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php:167)"} []`

above error when visiting the page which does elastic query in my prod environment while "`fos:elastica:populate`" is running fine. I am using FOSElasticaBundle
 .The system is running fine in staging server and my local machine. Only difference between staging and production is that in production server elasticsearch server and database server are separated from application server. Need help urgently.

**Comment by ruflin** [comment]
I'm not expert on the FOS Elastic bundle and what the populate command does, but the above error looks like either the host is not configured correctly or elasticsearch cannot be reached. What have you put inside the configuration as host?

**Comment by nirajan-panthee** [comment]
I have setup new server, and now its working on that, thank you for your help.
