### ISSUE TITLE
Setting empty headers inc curl_setopt causes Internal Server Error 500 

### ISSUE THREAD

**Issue by Antoniossss** [ruflin/Elastica#1123]
I just ran into such problem. This must be related to specific php/curl installation as Elastica works fine on my local dev env but causes err 500 on production.

I have found out that in `Elastica\Transport\Http` the line 152  `curl_setopt($conn, CURLOPT_HTTPHEADER, $headers);` causes the crash while `$headers` is empty. 
`
        if(!empty($headers)){
            curl_setopt($conn, CURLOPT_HTTPHEADER, $headers);
        }`

fixes the isssue for me and still works lokally. It is a matter of discussion should it be handled by Elastica or env should have different curl instalation that does not crash on empty headers.

**Comment by ruflin** [comment]
The part I'm not sure I understand to 100% is why headers can be empty. Which version of Elastica are you using? As in master line 152 seems to be a different line.

**Comment by Tobion** [comment]
The headers are usually empty as long as you don't add custom ones. But normally it doesn't cause a problem. 

@Antoniossss What CURL, PHP and OS version did the empty headers cause a problem with? Is this still relevant for you?

**Comment by Antoniossss** [comment]
As far as i recall we ended up half a year ago with php and modules update
so it is not relevant anymore. Thank you for your time and keep up the good
work!

14.03.2017 20:42 "Tobias Schultze" <notifications@github.com> napisał(a):
