### ISSUE TITLE
`filter` and `post_filter` are not the same - why did one get depracated in favour of the other????

### ISSUE THREAD

**Issue by Antoniossss** [ruflin/Elastica#1138]
What i have found out in the code:
```
   /**
     * Set Filter.
     *
     * @param \Elastica\Query\AbstractQuery $filter Filter object
     *
     * @return $this
     *
     * @link    https://github.com/elasticsearch/elasticsearch/issues/7422
     * @deprecated Use Elastica\Query::setPostFilter() instead, this method will be removed in further Elastica releases
     */
    public function setFilter($filter)
    {
        if ($filter instanceof AbstractFilter) {
            trigger_error('Deprecated: Elastica\Query::setFilter() passing filter as AbstractFilter is deprecated. Pass instance of AbstractQuery instead.', E_USER_DEPRECATED);
        } elseif (!($filter instanceof AbstractQuery)) {
            throw new InvalidException('Filter must be instance of AbstractQuery');
        }

        trigger_error('Deprecated: Elastica\Query::setFilter() is deprecated and will be removed in further Elastica releases. Use Elastica\Query::setPostFilter() instead.', E_USER_DEPRECATED);

        return $this->setPostFilter($filter);
    }

```

Why `setFilter` is depracated in favor of post_filter while they are NOT EQUIVALENT.

`filter` context is executed BEFORE `query` on filtered results, while `post_filter` is executed AFTER `query`. Moreover filtered query can be cached by ES while query cannot. 

What happend here???

**Comment by Antoniossss** [comment]
According to https://github.com/elastic/elasticsearch/issues/7422 it is the same in fact. But still ES docs are not that clear about that. So how to get filtered query now ??

**Comment by ruflin** [comment]
@Antoniossss Is your question on how to do in elasticsearch directly or in Elastica? Also which ES version are you referring to?

**Comment by Antoniossss** [comment]
This was question about Elastica and ES 2.3.x. Sorry for confusion, but I just didnt noticed that there `Elastica\Query` is not extending `AbstractQuery` thus I was looking for `addFilter` method in wrong class. Anyway I will close this issue as I made unnecessary confusion :( sorry bout that.

**Comment by ruflin** [comment]
Yeah, the naming there is for historical reasons not great.
