### ISSUE TITLE
Elastica / Elastcisearch / Pydio error

### ISSUE THREAD

**Issue by afm-mike** [ruflin/Elastica#1144]
From pydio web gui: So I googled about, and installed composer, got the pydio plugin enabled, installed Elastica in plugin dir, made sure elasticsearch is running / working, all latest coder versions, , then get this, ‘Internal Server Error’ when trying to access any ws in pydio web.:

[Tue Jul 19 08:45:11.300123 2016] [:error] [pid 27628] [client 1.2.3.4:62767] PHP Fatal error: Class ‘Elastica\\Client’ not found in /var/www/pydio/plugins/index.elasticsearch/class.AjxpElasticSearch.php on line 61, referer: http://1.2.3.4:8449/welcome/

OR try to index from cli:

php cmd.php -u=mike -p=XXXXXXXXXXXXXXXXXXXX! -a=index -r=archived_data
PHP Parse error: syntax error, unexpected ‘/’, expecting identifier (T_STRING) in /var/www/pydio/plugins/index.elasticsearch/class.AjxpElasticSearch.php on line 61

Line 61 is 1st line here:

$this->client = new Elastica\Client(array(
       "host" => $this->getFilteredOption("ELASTICSEARCH_HOST"),
       "port" => $this->getFilteredOption("ELASTICSEARCH_PORT"))
);

To no avail, I have tried changing line 61 to:

$this->client = new \Elastica\Client(array(

Can anyone point me in the right direction?  Thanks,

**Comment by afm-mike** [comment]
In case it matters:

Elastica:  3.2.1
Elasticsearch:  2.3.4
PHP:  5.6.23
java version "1.7.0_101"

Any thoughts on the issue?

**Comment by ruflin** [comment]
There seems to be an issue with your autoloader. Do you use composer to generate the autoloader? How exactly did you install Elastica?

**Comment by afm-mike** [comment]
I used composer.  Let's see,, I:

(1)  I created a plugin folder called index.elasticsearch in the pydio plugin directry
(2)  I downlaoded from github a zip file of Elastica and unzipped it in my home directory to Elastica-master
(3)  I then copied the /home/mike/Elastica-master/lib/Elastica folder to the index.elasticsearch folder, so there is a subfolder in index.elasticsearch called Elastica
(4)  I changed owner to that folder and all its files to www-data:www-data
(5)  I installed the pydio plugin files into index.elasticsearch

**Comment by afm-mike** [comment]
Saw this from Charles at pydio (so I am hoping it is just a version compatibility issue...):

...wait for 6.4.2, coming very very soon … we have upgraded the elasticsearch plugin to be compatible with last version of elastica AND elasticsearch.

**Comment by ruflin** [comment]
Your above steps don't really look like you used composer. I would expect you to add elastica to you composer.json file and run something like `composer update`.

I don't know about pydio. But to be honest I don't think it is an issue with pydio and version incompatibility but more related to you setup. Elastica\Client exists since the first version of Elastica.

**Comment by afm-mike** [comment]
I did use composer, as I recall, but I may not remember the steps I did, but I'll try it again this evening and post here.  Thank you!

**Comment by afm-mike** [comment]
I had the wrong json file.  I used this initially:
{
    "require": {
        "elasticsearch/elasticsearch": "~2.0"
    }
}

and had the issue.  Now I just used this:

{ "require": { "ruflin/elastica": "dev-master" } }

and I can now get into a ws w/o issue after activating the elaasticsearch plugin. However, if I type a search term, I get an error, like: no such index [index: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]. I will check with pydio to see if I need to build the index from the command line first, unlike the Lucene plugin. Thanks

**Comment by afm-mike** [comment]
OK, got it working, and what a difference so far in terms of build speed of index.  Finally :-)

**Comment by afm-mike** [comment]
By the way, is there any optimization I should do for Elastica and/or Elasticsearch?  Single node, 8-core FX-8370, 32GB ram, Raid-5.

**Comment by ruflin** [comment]
Glad you found a solution. Closing this issue.

About the specs: That depends on lots of factors so there is no single simple answer. Best is you start wit the default config it an check if you hit any issue.
