### ISSUE TITLE
minimum_match accepts not only int but string

### ISSUE THREAD

**Issue by topikito** [ruflin/Elastica#1149]
I was trying to run a `Terms` query with `minimum_match` and passing a percentage but was getting "wrong" results. Inspected the method and noticed that its only accepting `int`.

I can't find anything on the ElasticSearch docu about this (only finding `minimum_should_match`) but I ran manually a query against ES and confirmed that you can send "minimum_match" as a string (percentage).

Before doing a PR, I'd like to confirm this.

I'm using `Elastica 2.3.*` - Still being `int` in `3.*`

**Comment by ruflin** [comment]
You are definitively right and minimum_should_match should also support percentages: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-minimum-should-match.html There are even multiple conditionals which I was not aware of, so going with string is a good idea.

**Comment by topikito** [comment]
Awesome @ruflin - Testing-wise: right now all tests are using `int` for this purpose. How do you wanna attack this new approach? Dividing two test per method as one for `int` and one for `string`? I'm happy to do a PR (I've already modified the type hinting, but need to confirm how the tests should be)

**Comment by ruflin** [comment]
As we will switch to string, the verification of the information will be much harder on the client side. But I hope in case invalid strings are provided, elasticsearch will return an error. For the testing I suggest we test all the valid values and check if they still work. We should still keep some tests where ints are passed to make sure we keep BC compatibility. Does this answer your question?

Thanks a lot for directly doing a PR.

BTW: I reopend the issue as I think we should keep it open until the PR is merged.

**Comment by topikito** [comment]
Hi @ruflin,

I tried contacting you outside GitHub but no luck (Twitter).

I'm experiencing this issue when running the tests:

```
☁  Elastica [fix-minimum-match-type-hinting|MERGING] ⚡ make run RUN="make phpunit"
docker run -v /path/to/repo/Elastica:/elastica ruflin/elastica make phpunit
Waiting on elasticsearch(elasticsearch:9200) to start...............................
Elasticsearch is not running or is not healthy.
Address: elasticsearch:9200

make: *** [run] Error 1
```

Any idea?

**Comment by ruflin** [comment]
Oh, just saw the message now. Sorry. What happens if you just run `make tests` ?

**Comment by topikito** [comment]
Thanks @ruflin : this worked `make tests`

I was following the `CONTRIBUTION` file. With this "test", if no errors are raised, shall I assume its ok for me to PR ?

**Comment by ruflin** [comment]
Great. We should about CONTRIBUTING.md :-( 

You should definitively open a PR ;-)
