### ISSUE TITLE
How to use highlight_query with Elastica?

### ISSUE THREAD

**Issue by anacicconi** [ruflin/Elastica#1154]
I'm new to Elastica and I'm searching for a way to highlight nested query results with highlight_query. I checked the code and $query->setHighlight() accepts only an array as a parameter. Maybe there's another way to achieve this result using Elastica. Could you give me an advice? 

This is the json query I'm trying to translate to Elastica:

    {
        "query": {
            "bool": {
                "must": [
            {
                "match": {
                "publishAt": "2016"
              }
            },
            {
                "nested": {
                "path": "translations",
                "query": {
                    "multi_match": {
                        "query": "leadership",
                    "fields": [
                            "translations.*"
                        ]
                  }
                }
              }
            },
            {
                "nested": {
                "path": "translations",
                "query": {
                    "bool": {
                        "must": [
                      {
                          "match": {
                          "translations.locale": "fr"
                        }
                      }
                    ]
                  }
                }
              }
            }
          ]
        }
      },
      "highlight": {
            "highlight_query": {
                "match": {
                    "translations.*": "leadership"
          }
        },
        "fields": {
                "translations.*": {}
        }
      }

I'm using FosElasticaBundle and I have this query without the highlight:

    $query = new Query();
    $bool = new Bool();

    $yearQuery     = new Match();
    $yearQuery->setField('publishAt', 2016);
    $bool->addMust($yearQuery);

    $nestedQuery  = new Query\Nested();
    $nestedQuery->setPath('translations');

    $multiMatch = new Query\MultiMatch();
    $multiMatch->setQuery($string);
    $multiMatch->setFields('translations.*');
    $nestedQuery->setQuery($multiMatch);

    $nestedQuery2  = new Query\Nested();
    $nestedQuery2->setPath('translations');

    $nestedBool  = new Bool();
    $localeQuery = new Match();
    $localeQuery->setField('translations.locale', $request->getLocale());
    $nestedBool->addMust($localeQuery);
    $nestedQuery2->setQuery($nestedBool);

    $bool->addMust($nestedQuery);
    $bool->addMust($nestedQuery2);

    $query->setQuery($bool);

    $results = $finder->findHybrid($query);

**Comment by ruflin** [comment]
Best is to have a look at the tests that use the hightlight query: https://github.com/ruflin/Elastica/blob/master/test/lib/Elastica/Test/Query/HighlightTest.php

**Comment by anacicconi** [comment]
I finally found the solution to my problem. I was doing the wrong query and I haven't add 'include_in_parent: true' to my config. If this can help someone, the query looks like this now:

Elastic query:

    {
        "query": {
            "bool": {
                "must": [
                    {
                        "match": {
                        "updatedAt": "2016"
                        }
                    },
                    {
                        "match": {
                        "translations.locale": "fr"
                        }
                    },
                    {
                        "multi_match": {
                            "query": "leadership",
                            "fields": [
                                "translations.*"
                            ]
                        }
                    }
                ]
            }
        },
        "highlight": {
            "fields": {
                "translations.*": {}
            }
        }
    }

And using Elastica:

        $query = new Query();
        $bool = new Bool();

        $stringQuery = new Query\MultiMatch();
        $stringQuery->setQuery($string);
        $stringQuery->setFields('translations.*');
        $bool->addMust($stringQuery);

        $updateQuery = new Match();
        $updateQuery->setField('updatedAt', $year);
        $bool->addMust($updateQuery);

        $localeQuery = new Match();
        $localeQuery->setField('translations.locale', $request->getLocale());
        $bool->addMust($localeQuery);
        $query->setQuery($bool);

        $query->setHighlight(array(
            "fields" => array("translations.*" => new \stdClass())
        ));

        $resultSet      = $index->search($query);
        $results        = $this->getResponse($resultSet, $request->getLocale());

The config of my index:

    indexes:
        my_index:
            client: default
            finder: ~ 
            types:
                article:
                    mappings:
                        updatedAt:
                            date: { type: date, format: "yyyy" }
                        translations:
                            type: nested
                            include_in_parent: true
                            properties:
                                title: ~
                                introduction: ~
                                locale: ~

**Comment by ruflin** [comment]
Great that you found the solution and thanks for providing it here for others.

**Comment by anacicconi** [comment]
@ruflin just another question. Is it possible to do highlight_query with Elastica?

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html#_highlight_query
