### ISSUE TITLE
 Meta Source index.elasticsearch does not implement the initMeta method

### ISSUE THREAD

**Issue by afm-mike** [ruflin/Elastica#1155]
Arghhh, I realize this is not your issue, but you got me straightened out on the last issue, prior to this upgrade.  I upgraded to the latest pydio version, 6.4.2, now get this, any idea whatI need to do to fix this?

It as working fine before I upgraded :-(

PHP Fatal error: Uncaught exception ‘AJXP_Exception’ with message ‘Error while loading repository feature : Meta Source index.elasticsearch does not implement the initMeta method.’ in /var/www/pydio/core/classes/class.ConfService.php:1718
Stack trace:
#0 /var/www/pydio/core/classes/class.ConfService.php(1612): ConfService->loadRepositoryDriverInst(Object(Repository))
#1 /var/www/pydio/cmd.php(204): ConfService::loadDriverForRepository(Object(Repository))
#2 {main}
thrown in /var/www/pydio/core/classes/class.ConfService.php on line 1718

**Comment by afm-mike** [comment]
I reinstalled 6.4.2,, and it seems to work now, so I will chalk it up to operator error. thanks

**Comment by ruflin** [comment]
Glad you found a solution. Closing this issue.
