### ISSUE TITLE
Is it possible for Now to use async Request on Top of Guzzle Transport?

### ISSUE THREAD

**Issue by ovr** [ruflin/Elastica#1156]
Hey!

> Is it possible for Now to use async Request on Top of Guzzle Transport?

As an example - bulk insert

Thanks

@ruflin

**Comment by ruflin** [comment]
I'm not aware of the details on how this works in Guzzle, but I assume it need would need some changes in https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Transport/Guzzle.php

**Comment by ovr** [comment]
What do you think about added async methods

```
$elastica->asyncAddDocuments() -> supported for Guzzle Transport
```

And return `Promise`

If it's okey I can implement?

**Comment by ruflin** [comment]
@ovr Sorry for the late reply. This definitively sounds interesting. I'm curious how well this will fit into the current way Elastica handles connection. +1 on discussing this one some code.

**Comment by ovr** [comment]
@ruflin On upcoming weekend-s I am going to prepare a small PR related this issue and show a way how to implement it

**Comment by ruflin** [comment]
Cool, looking forward to it.

**Comment by Tobion** [comment]
Closing. Please open a PR if you want to move forward with this.
