### ISSUE TITLE
Match all query returns no results.

### ISSUE THREAD

**Issue by JTubex** [ruflin/Elastica#1159]
I'm creating a  [match all query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html#query-dsl-match-query-zero) like this: 

``` php
$query = new Query();
$matchQuery = new Query\Match(Query\Match::ZERO_TERM_ALL, $keyword);
$query->setQuery($matchQuery);
```

Currently it returns no results, but because the constant ZERO_TERM_ALL in Elastica\Query\Match has 'all' as value. I think this should be changed to '_all'.

**Comment by ruflin** [comment]
Not sure if you use the constant as expected. Here is an example: https://github.com/ruflin/Elastica/blob/master/test/lib/Elastica/Test/Query/MatchTest.php#L175

**Comment by Tobion** [comment]
Closing for the reasons given by @ruflin
