### ISSUE TITLE
deleteByQuery: QueryParsingException

### ISSUE THREAD

**Issue by olchick** [ruflin/Elastica#1162]
When I use deleteByQuery() method with parameter NULL (for delete all documents), I cought QueryParsingException: No query registered for [query].

I dump query before send request:
`[
  "query" => [
    "query" => [
      "match_all" => {}
    ]
  ]
]
`

**Comment by ruflin** [comment]
Which Elastica version are you using? Which elasticsearch version are you using?

**Comment by olchick** [comment]
"name": "ruflin/elastica",
"version": "dev-master",

elasticsearch-1.5.2

**Comment by ruflin** [comment]
dev-maste is only compatible with elasticsearch 2.x. But I didn't test it this is actually the issue. I can't remember that we had to change things in the match_all query. Could you briefly test if you have the same problem with ES 2.x?

**Comment by olchick** [comment]
It works for ES 2.x. 

But still query: `[ "query" => [ "query" => [ "match_all" => {} ] ] ] `, instead of `[ "query" => [ "match_all" => {} ] ] `

Anywhere, Thank you for your answer.

**Comment by ruflin** [comment]
@olchick Not sure I fully get your comment. The result is as expected with elasticsearch 2.x? Or does it just not throw an error with elasticsearch 2.x but not work? Can you share your php code?

**Comment by olchick** [comment]
It's work for elasticsearch 2.x.
Thank you for your answer.

**Comment by ruflin** [comment]
Ok, in this case I'm closing this issue. If you want it to work with elasticsearch 1.x, you need to use Elastica 2.x. Please reopen if that is not the case.
