### ISSUE TITLE
Elastica refrence for learning 

### ISSUE THREAD

**Issue by DBARUNNER** [ruflin/Elastica#1167]
Hello 
i know raw query of elasticsearch but i want to work with elastica,  Elastica.io have not all the elastica query please if you guid me how to learn elastica and  tell me a good refrence to learn elastica

**Comment by ruflin** [comment]
Best is to use the API as reference guide: http://elastica.io/api/latest/ In most cases if you know which query you want to use for elasticsearch, there will be a class with the same name in Elastica. An other great source for code examples is the test suite: https://github.com/ruflin/Elastica/tree/master/test/lib/Elastica/Test

Unfortunately it is true that the Elastica docs are not very extensive. Contributions are always welcome.
