### ISSUE TITLE
Using lookup parameters for terms query

### ISSUE THREAD

**Issue by nishantsaini** [ruflin/Elastica#1171]
@ruflin 
How can I generate Terms query with lookup, of following type:
`"terms" : {
      "user" : {
        "index" : "users",
        "type" : "user",
        "id" : "2",
        "path" : "followers"
      }
    }
  }`
I'm referring [this example](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-terms-query.html#_terms_lookup_twitter_example)
I tried the following:
```
$termsFilter = new Terms('user');
$termsFilter->setParams(['type' => 'user', 'id' => 2, 'path' => 'followers', 'index' =>'users']);
```
The resulting query for above code is:
`"terms" : {      
        "index" : "users",
        "type" : "user",
        "id" : "2",
        "path" : "followers"
        "user" : []
      }
  }`

Is support for lookup not implemented?
ES version: 2.3

**Comment by ruflin** [comment]
It seems like currently Terms Query always assume that the value for the terms key is an array which is not the case in this lookup example. This would need some extension to the logic of the Terms query. What you can always to is using the raw query: http://elastica.io/example/raw-array-query.html

**Comment by nishantsaini** [comment]
@ruflin : Thanks for the suggestion :+1:
