### ISSUE TITLE
Querybuilder must be compatible with Elasticsearch 2.X

### ISSUE THREAD

**Issue by piwii** [ruflin/Elastica#1175]
Query geo_distance is no posssible with current query builder, we need to add lib/Elastica/QueryBuilder/Version/Version2X.php to be compatible with elasticsearch 2.X

**Comment by piwii** [comment]
Fix in #1176

**Comment by ruflin** [comment]
Closing as https://github.com/ruflin/Elastica/pull/1176 was merged. Thanks a lot to directly fix it.
