### ISSUE TITLE
Upgrade to Elasticsearch 5.0

### ISSUE THREAD

**Issue by ruflin** [ruflin/Elastica#1184]
Elasticsearch 5.0 brings several breaking changes which affect Elastica. This issue is to track the open tasks to make Elastica fully compatible with elasticsearch 5.0.
- [x] Remove all depercated methods as this is a major release
- [x] Remove filters as filters are replaced by query
- [ ] Testing
  - [ ] Fix tests which are currently skipped because of incompatibility
  - [ ] Fix `Set fielddata=true on [answer] in order to load fielddata in memory` tests
- [x] Implement percolate query and remove Percolator: https://www.elastic.co/guide/en/elasticsearch/reference/5.0/query-dsl-percolate-query.html
- [x] Remove image plugin support
- [x] Double check which PHP versions should be supported
- [x] Remove filtered query in favor of Bool queries
- [x] Add Painless as script language

**Comment by Zyqsempai** [comment]
Hi there, i will be glad to help you with this migration, please give me some short description, for example for "Remove image plugin support", do you want to completely delete it from project? Or give some other task!

**Comment by ruflin** [comment]
@Zyqsempai Great to hear. What I already did is removing all the filters and skip all the tests which do not pass at the moment. I added a message to each of this tests on why they don't pass (see https://travis-ci.org/ruflin/Elastica/jobs/167274669#L2135). We need to go through each of this test an figure out how it should be fixed. Most of them should be an easy fix.

To start simple: I think the image plugin is not under active development any more. So we should remove this one completely from the code and tests.

**Comment by Zyqsempai** [comment]
ok then i will start with image plugin a then move on to tests

**Comment by Zyqsempai** [comment]
So, what about this type of skipped tests, "script.inline is not enabled. This is required for this test", i checked your elasticsearch.yml and i found this "script.inline: on" i also tried to add something like this "script.engine.groovy.inline.aggs: on" and no results, do you know source of this problem?

**Comment by Zyqsempai** [comment]
Also, this one "Skipped because of 5.0: unknown setting [index.merge.policy.merge_factor] did you mean [index.merge.policy.max_merge_at_once]" this is strange because according to this https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_setting_changes.html#_merge_and_merge_throttling_settings , this error mast appear after 2.4 version migration, anyway it seams like we can't fix it for Version > 2.4

**Comment by ruflin** [comment]
@Zyqsempai Sorry for the delay in answering, was on vacation last week. About the issues above: Didn't check them in detail yet. For some option it can be that they don't exist anymore and we have to remove them or rename them.

**Comment by p365labs** [comment]
Hi @ruflin regarding this error 
I have a look here https://www.elastic.co/guide/en/elasticsearch/reference/1.7/index-modules-merge.html, seems that merge_factor has been removed and the PolicyFactor has been deprecated since 1.6 elasticsearch version. I had a look at source code of ES and in ES5.0\ES5.x\master this feature is not present. 
I've opened a PR --> https://github.com/ruflin/Elastica/pull/1192 for this

**Comment by p365labs** [comment]
dear @ruflin and @Zyqsempai I'm trying to help you too, if I can :) now I'm working on remove all the deprecations. I would like to understand better another point of this issue : "_Double check which PHP versions should be supported_" how do you want to deal with it ? If you have a look at here http://php.net/supported-versions.php, php 5.4 and 5.5 has been dropped active versions are 7.0 and 5.6 (active support will end januare the 2017).  I will drop **5.4** for sure and evaluate dropping also **5.5**, but leaving 5.6. What do u guess ?

**Comment by ruflin** [comment]
The above topics have been discussed here: https://gitter.im/ruflin/Elastica?at=580c7bc4305a10335db2114f

**Comment by p365labs** [comment]
I'll work now  on scripts.inline which does not seem to be enabled / work as expected.

**Comment by Zyqsempai** [comment]
I will work on plugins problems, such as "delete-by-query plugin not installed." and "elasticsearch-mapper-attachments plugin not installed."

**Comment by ruflin** [comment]
@Zyqsempai @p365labs About the PHP versions. I opened https://github.com/ruflin/Elastica/pull/1201 to check if everything is fine with PHP 7.1. To add it is a no brainer. More complex is the question about which PHP versions should we still support. Currently we support up to 5.4. 5.4 and 5.5 already reached EOL some time ago. The reason I kept it in is because I know of some larger projects that use Elastica and are still on PHP 5.4. I'm quite sure we should drop support for PHP 5.4, not 100% sure about 5.5. One reason I would also drop 5.5 is that I assume when people update from 5.4, the could directly go to 5.6 so 5.5 is not really needed. In addition, as we have quite a few breaking changes for elasticsearch 5.0, people using it will have to change their code anyways and "potentially" this are also more up-to-date projects.

At the same time, if we don't break any of the PHP version, why should we remove them? 

What are your thoughts?

**Comment by Zyqsempai** [comment]
@ruflin Hi there, i think that we don't need to worry about versions at this moment, because we don't face any problem now, and we can delete them in any time, this issue are called "Upgrade to Elasticsearch 5.0", i think we don't need to mix issues. Let's finish all the staff that are realy related to upgrade.

**Comment by ruflin** [comment]
@Zyqsempai The reason I mix the two is because this issue is for me also the only blocking thing for the next major release and I only want to drop support for PHP version in major release (if possible).

**Comment by Zyqsempai** [comment]
@ruflin This make sense and if we really have only one opportunity to delete them, then we should do that, you're right. And i think that we need to keep only 5.6 and above.

**Comment by p365labs** [comment]
even if this is not a the main theme for this issue, I agree with @ruflin

**Comment by p365labs** [comment]
Hi all, I will work on Scripts and update to painless script, if it's ok 4 u guys

**Comment by ruflin** [comment]
@p365labs @Zyqsempai Based on your inputs and the following additional reasons I decided to also remove PHP 5.5

* https://github.com/ruflin/Elastica/issues/944 is not possible without 5.6
* There are very few BC changes from 5.5 to 5.6. So I don't see any real reason people could not upgrade their PHP version
* I want to use the most recent dependencies for testing, for example phpunit. I can't do that with 5.5.

PR https://github.com/ruflin/Elastica/pull/1202 was updated accordingly.

**Comment by ruflin** [comment]
@p365labs @Zyqsempai I was thinking of doing a 5.0.0-beta1 in the next days. I'm aware that there are still some open tasks but I think most of them seem to be related to tests which need to be updated an not Elastica itself. Having a beta will also get more feedback of what could be broken with 5.0. WDYT?

**Comment by p365labs** [comment]
@ruflin  @Zyqsempai : Having a beta will allow Elastica's users installing the package with more ease and trying it on their project. Which means more feedbacks for us on the major version of Elastica. so 👍

**Comment by Zyqsempai** [comment]
@ruflin Great idea! I agree.
