### ISSUE TITLE
Post Filter - Elastic search performance advice

### ISSUE THREAD

**Issue by idhard** [ruflin/Elastica#1187]
According to the documentation : 

https://www.elastic.co/guide/en/elasticsearch/guide/current/_post_filter.html

> Use a post_filter only if you need to differentially filter search results and aggregations. Sometimes people will use post_filter for regular searches.
> 
> Don’t do this! The nature of the post_filter means it runs after the query, so any performance benefit of filtering (such as caches) is lost completely.
> 
> The post_filter should be used only in combination with aggregations, and only when you need differential filtering.

And i have noticed that the Query builder is setting the filters in the post_filter parent. 

i have followed some of the related issues on this topic but still im confused about the implementation of this class.

should we use  filtered queries instead of Query in order to follow the performance advice  ?

**Comment by p365labs** [comment]
Hi @idhard , when u say "And i have noticed that the Query builder is setting the filters in the post_filter parent." where exactly QueryBuilder is setting filters in the post_filters ? can u show me some code ?

**Comment by Tobion** [comment]
Closing as the query builder does not set filters at all as pointed out by @p365labs
