### ISSUE TITLE
AND/OR to must and Filtered Queries

### ISSUE THREAD

**Issue by jimmykirk** [ruflin/Elastica#1194]
Hello,

I am using Elasticsearch 2.4 and the current release of Elastica.

I am porting some of my elasticsearch javascript stuff to elastica and have seen some stuff where I'm simply not sure if Elastica can do what I want(or after looking through the docs, maybe I'm approaching this incorrectly).

One such instance is the following: Adding an and/or to a must doesn't seem to be available(possibly deprecated).

Additionally, I get a message in my IDE about filtered being deprecated. I'd appreciate any assistance on these and thank you for your library! :)

```
GET /test_index/_search
{
  "size": 250,
  "query": {
    "filtered": {    // <====== FILTERED QUERY
      "query": {
        "match_all": {}
      },
      "filter": {
        "bool": {
          "must": [
            {
              "query_string": {
                "query": "test"
              }
            },
            {
              "or": [    // <====== OR array beneath MUST
                {
                  "term": {
                    "test_field_1": "value1"
                  },
                  "term": {
                    "test_field_2": "value2"
                  }
                }
              ]
            },
            {
              "or": [    // <====== OR array beneath MUST
                {
                  "term": {
                    "test_field_3": "value3"
                  },
                  "term": {
                    "test_field_3": "value4"
                  }
                }
              ]
            }
          ]
        }
      }
    }
  }
```

**Comment by ruflin** [comment]
For the bool queries, have a look at the test cases here: https://github.com/ruflin/Elastica/blob/master/test/lib/Elastica/Test/Query/BoolQueryTest.php Let me know if this helps.

Filtered query is deprecated because it is also deprecated in elasticsearch and should be replaced by a bool query: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-filtered-query.html

**Comment by jimmykirk** [comment]
Thank you @ruflin 
I was able to convert my queries over. However, the only issue I have remaining is that creating the has child with bool queries seems to have a bug.

I have several bool queries [like this](http://imgur.com/a/tDj4u.jpg) in an array. I want to add those to my has child object so that they are all inside. If I add a single boolQuery object to the hasChild constructor, it works as intended. 

However, if I add the array it works, but also spawns a matchAll query object [as seen here](http://imgur.com/a/1pzrn.jpg).

I see the BaseQuery create function checks the item submitted and spawns this matchAll object if it evaluates to empty. Perhaps I'm adding these bool queries the wrong way? Should I add them to another object instead of submitting an array?

**Comment by ruflin** [comment]
@jimmykirk Glad you got it working. Will close this issue then. Please reopen if you think there is a potential bug in the library that must be fixed.
