### ISSUE TITLE
Response getError method returning array

### ISSUE THREAD

**Issue by bitgandtter** [ruflin/Elastica#1221]
Using version 2.3.1
Elasticsearch 5.x

got exception 

> Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Wrong parameters for Elastica\Exception\ResponseException([string $message [, long $code [, Throwable $previous = NULL]]])"

reviewing the code i notice that getError method of Response class return an array instead of an string

**Comment by p365labs** [comment]
release 2.3.1 of Elastica library has been released for Elasticsearch version 1.7.3.
Have a look here :
https://github.com/ruflin/Elastica/releases?after=3.0.0-beta1

If you want to use Elasticsearch 5.0.0 you should use Elastica 5.0.0-beta1. Beware that this is a beta version, use it  for testing purposes and not for production one, any feedback will be really 
appreciated.

**Comment by bitgandtter** [comment]
Elastic 5.x its already GA, came out of beta and RC a month ago. This issue seems to be because the new version ways to handle errors. But since Elastic 5.x brings a lot of new enhancements speed among them a lot of people will start to use it. In my personal case i will for a new project, the one throw me this error and pretend to migrate other ones.

So it will be great to handle this new version

**Comment by p365labs** [comment]
If you use Elasticsearch 5.0 you should use **[Elastica 5.0.0-beta1](https://github.com/ruflin/Elastica/releases)**
- getError now return a string :
https://github.com/ruflin/Elastica/blob/8fa05bb677ab49e62e2af3bdfa62f7d9b6de761c/lib/Elastica/Response.php#L82

- the only version of Elastica that was returning an array was from 3.0.0-beta1 to 3.1.0: https://github.com/ruflin/Elastica/commit/99d7cd147c469e20e0c8e550c431712edda4dd19#diff-b364251d02e70310f3c6e443372397d3R81

**Comment by ruflin** [comment]
@bitgandtter As @p365labs state, for Elasticsearch 5.0 you need to use Elastica 5.0. Going to close this issue. In case you have issues with Elastica 5.0 and elasticsearch 5.0 please let us know. In case there are still some questions, feel free to reopen the issue.
