### ISSUE TITLE
How to define multiple hosts (multiple nodes in cluster)?

### ISSUE THREAD

**Issue by aguvillalba** [ruflin/Elastica#1226]
Hi Ruflin,

Is it possible to define more than 1 host in the config of the client? We have a cluster with 3 nodes, so if we define only 1 host to connect the client to, what if this node is down? In the ElasticSearch-PHP library, they allow to have multiple hosts for the client, is it possible something similar in Elastica?

Thank you very much for your work.

Best regards,
Agustin.

**Comment by ruflin** [comment]
You can pass an array of `connections` to the clients: https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Client.php#L36 Like this you have multiple hosts. Closing this as I think the above answers the question. Please reopen if not the case.
