### ISSUE TITLE
can i write eash query of elasticsearch in raw format array query of elastica ?

### ISSUE THREAD

**Issue by DBARUNNER** [ruflin/Elastica#1227]
I am using elastica 2.2 now i upgrade my elasticsearch to 5.0.0 as you know elastica 2.2 is not supporting ealsticsearch 5.0.0 if i upgrade elastica it need new version of  php that it will cause more error with other aplication code, that's why i want to user elastica raw query to can do eash query of elasticsearch 5 can i do or no ?

**Comment by ruflin** [comment]
Which PHP Version are you using? To be honest the best to figure out if the above works is to try it out. As you are still on Elastica 2.2 I assume you were using elasticsearch 1.x before? Especially for error formats you should already have more luck with using Elastica 3.x at least.

**Comment by DBARUNNER** [comment]
PHP Version that i am using is 5.5 and i cant upgrade it to new version of php because of my other application code, now i want to user raw query of elastica my question is can i do each query of elasticsearch in raw format or no ?

**Comment by DBARUNNER** [comment]
I am using PHP Version 5.5 I cant upgrade it to new Version because of my other application code.
now I want to use raw query of Elastica my question is, can I do each query of elasticsearch 5.0.0 in format of raw query ?

**Comment by ruflin** [comment]
Elastica should be full compatible with PHP 5.5. We removed it because we don't test it anymore. All you have to do is to remove the PHP required version from the composer file. As far as I remember, there is even a param to overwrite it. This should work at the moment.

**Comment by DBARUNNER** [comment]
yeas it work fine with PHP 5.5 my question is is it work with Elasticsearch 5.0.0 ?

**Comment by ruflin** [comment]
Elastica 5.0 works fine with Elasticsearch 5.0. And that is what I mean. You can use Elastica 5.0 if you do the above changes to the composer file even with PHP 5.5.

**Comment by DBARUNNER** [comment]
if you please tell me how to remove php required version from ther composer file ? please help i will be grate full from you

**Comment by ruflin** [comment]
Have a look at `--ignore-platform-reqs` under https://getcomposer.org/doc/03-cli.md That "should" work.

**Comment by DBARUNNER** [comment]
@ruflin, just answear this quesion i will be thankfull.
Can I run each elasticsearch query in ther format of Elastica JSON raw query ?

**Comment by DBARUNNER** [comment]
@ruflin, just answear this quesion i will be thankfull.
Can I run each elasticsearch query in  format of Elastica JSON raw query ?

**Comment by ruflin** [comment]
@DBARUNNER I think yes, at least I'm not aware of one that doesn't work :-) Closing this issue as I think your initial issues is solved. For questions in the future best use the elastica google group: https://groups.google.com/forum/#!forum/elastica-php-client
