### ISSUE TITLE
Docs: search over multiple indexes/types?

### ISSUE THREAD

**Issue by nickdunn** [ruflin/Elastica#123]
(Alert: I have never used Lucene or ElasticSearch, currently working it out for myself, so apologies if this is incorrect or stupid)

The [inline docs state](https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Type.php#L9):

> Search over different indices and types is not supported yet

However [the ElasticSearch guide states](http://www.elasticsearch.org/guide/reference/api/search/indices-types.html):

> The search API can be applied to multiple types within an index, and across multiple indices. For example, we can search on all documents across all types within the twitter index

Are the Elastica docs incorrect, and ElasticSearch does indeed support searching across multiple indexes/types from a single query? If so, does/will Elastica also support this?

**Comment by hpatoio** [comment]
@nickdunn how did you solved this ? Do you have an example to share  ?
