### ISSUE TITLE
Convert Elastica\Query object to raw json?

### ISSUE THREAD

**Issue by jimmykirk** [ruflin/Elastica#1233]
All,

I am currently in the process of upgrading to Elasticsearch 5.1 and am finding that some of my queries are failing. Things like type=>parent_type have been resolved within Elastica. However, some of my queries succeed but return zero results. Is it possible to dump the raw json from an Elastica\Query object so that I can do some debugging in the dev console of kibana?

Regards,

Jimmy

**Comment by jimmykirk** [comment]
Shortly after posting this, I took a break and approached the issue with a clear head. For all wondering... 

From the Elastica\Query object, call the toArray() method and then use json_encode. Now to figure out why my stuff breaks down.

**Comment by ruflin** [comment]
Great you got one step further. In case your error is not Elastica related, please close the issue. If not, let us know how we can help.

**Comment by jimmykirk** [comment]
Thank you for Elastica and your help always... and yes, it was breaking changes to ElasticSearch that was my issue.
