### ISSUE TITLE
Unnecessary request to ES when iterating over ResultSets using Scroll

### ISSUE THREAD

**Issue by chriskicker** [ruflin/Elastica#1234]
There is one unnecessary call to ES API when using Elastica\Scroll. The last call (in next method) always sets `$this->_currentResultSet` with empty Elastica\ResultSet. It could be omitted.
The solution is quite simple. In rewind method number of total pages could be count
`$this->totalPages = ceil($scroll->current()->getTotalHits() / $scroll->current()->count());`

Then in next method request should be sent only if there is next page `$this->currentPage <= $this->totalPages;`
In next method `$this->currentPage` should be incremented.

**Comment by pawelbaranski** [comment]
With large data set it may have major impact on performance. In our case we gained 25% boost

**Comment by ruflin** [comment]
SGTM. Can you open a PR with this change?

**Comment by Tobion** [comment]
@chriskicker can you create a PR please?
