### ISSUE TITLE
OR in BoolQuery filter

### ISSUE THREAD

**Issue by szepczynski** [ruflin/Elastica#1235]
Hi,

I have a query like this:

```
{
  "query": {
    "bool": {
      "must": {
        "match_all": {}
      },
      "filter": {
        "or": [
          {
            "geo_distance": {
              "distance": "15km",
              "departureLocation.coords": {
                "lat": 52.4,
                "lon": 16.9
              }
            }
          },
          {
            "nested": {
              "path": "stopovers",
              "filter": {
                "geo_distance": {
                  "distance": "15km",
                  "stopovers.location.coords": {
                    "lat": 52.4,
                    "lon": 16.9
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}
```

I have an `or` statement in filter part. How I can write OR condition in filter part? There is Elastica/Filter/BoolOr which is deprecated. Is possible to write these condition and not using deprecated classes?

**Comment by ruflin** [comment]
Instead of filters you have to pass queries objects to it. See http://elastica.io/api/latest/classes/Elastica.Query.BoolQuery.html#method_addFilter The effect will be the same. Closing this issue as I think this solves your question. Please reopen if not.

**Comment by szepczynski** [comment]
Yeah, I know that. I use Elastica\Query\BoolQuery but i must use `OR` statement in filter part of BoolQuery and I cannot see how do that without using deprecated Elastica/Filter/BoolOr. Please look at my elasticsearch query and filter part.

I have code:
```
        $arrivalCoords = new GeoDistance('arrivalLocation.coords', $location, $distance);

        $stopovers = new Nested();
        $stopovers->setPath('stopovers');
        $stopovers->setParam('filter', new GeoDistance('stopovers.location.coords', $location, $distance));


        $boolQuery->addFilter($orQuery);
```

In the last line I need join $arrivalCoords and $stopovers with `OR` statement. How I can do that?

**Comment by ruflin** [comment]
Or filter was replaced with Bool in 5.0: https://www.elastic.co/guide/en/elasticsearch/reference/5.0/query-dsl-or-filter.html

I think what you are looking for is `should` and `minimum_should_match`: https://www.elastic.co/guide/en/elasticsearch/reference/5.0/query-dsl-bool-query.html

So if you are using elasticsearch 5.0 the above query should actually return an error. Which ES version are you on? Which Elastica version?

**Comment by szepczynski** [comment]
Ok, thanks for clarification. I don't follow changes in ES 5. I rewrite my es query to:

```
{
  "query": {
    "bool": {
      "must": {
        "match_all": {}
      },
      "filter": {
        "bool": {
          "should": [
            {
              "geo_distance": {
                "distance": "15km",
                "departureLocation.coords": {
                  "lat": 52.4,
                  "lon": 16.9
                }
              }
            },
            {
              "nested": {
                "path": "stopovers",
                "query": {
                  "geo_distance": {
                    "distance": "15km",
                    "stopovers.location.coords": {
                      "lat": 52.4,
                      "lon": 16.9
                    }
                  }
                }
              }
            }
          ]
        }
      }
    }
  }
}
```

And now I know how to write the missing `$orQuery`:

```
$departureCoords = new GeoDistance('departureLocation.coords', $location, $distance);

$stopovers = new Nested();
$stopovers->setPath('stopovers');
$stopovers->setQuery(new GeoDistance('stopovers.location.coords', $location, $distance));


$orQuery = new BoolQuery();
$orQuery->addShould($departureCoords);
$orQuery->addShould($stopovers);

$boolQuery->addFilter($orQuery);
```

Thanks for help, I didn't find this in documentation!

**Comment by ruflin** [comment]
Glad you found a solution and thanks for posting it. Yeah, Elastica docs are not very extensive :-(
