### ISSUE TITLE
Support for query string parameter request_cache

### ISSUE THREAD

**Issue by ilanrivers** [ruflin/Elastica#1241]
It appears that the library does not support request_cache as documented here:
https://www.elastic.co/guide/en/elasticsearch/reference/current/shard-request-cache.html#_enabling_and_disabling_caching_per_request

**Comment by ruflin** [comment]
It seems we don't have a constant for it yet, but should be able to pass any option to `->search(...)` that you need. https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Search.php

**Comment by ilanrivers** [comment]
Opened a PR : https://github.com/ruflin/Elastica/pull/1243

**Comment by p365labs** [comment]
yep, @ruflin pr was https://github.com/ruflin/Elastica/pull/1243

**Comment by ruflin** [comment]
Thanks guys
