### ISSUE TITLE
Deprecated: Filters are deprecated. Use queries in filter context.

### ISSUE THREAD

**Issue by iamfinky** [ruflin/Elastica#1247]
So following an upgrade to Elastica 3.2.3, a bunch of my queries are failing because I'm using \Elastica\Filter\BoolAnd() which has been deprecated in favour of using queries in filter context.

However, there appear to be no examples or documentation on how to do this other than creating the JSON for the queries by hand.

Can anyone provide an example of how to convert an 'old' \Elastica\Query which uses setPostFilter or setFilter to the new "filter context" form please?

**Comment by ruflin** [comment]
@iamfinky Which elasticsearch version are you using? Just want to make sure you use compatible versions.

**Comment by iamfinky** [comment]
@ruflin So I'm using 2.3.1 - is this compatible with this version of Elastica?

Either way, it would be good to understand how these "filter contexts" are used.

**Comment by ruflin** [comment]
Yes, these version are compatible. What you can do is just create `Elastica/Query/BoolAnd()` and pass it to `setFilter` method.

**Comment by Tobion** [comment]
Closing as the solution has been given.
