### ISSUE TITLE
Request: Support "ingest-attachment" pipeline

### ISSUE THREAD

**Issue by osnard** [ruflin/Elastica#1248]
Original request from Google group (https://groups.google.com/forum/#!topic/elastica-php-client/D48Zc_qr9Mc)

I want to index office files. I'm using ElasticSearch 5 and therefore the "mapper-attachments" plugin is deprecated. The docs tell me to use "ingest-attachment". I've already set up a type/mapping and the pipeline [1], but now I need to tell ElastichSearch to actually use that pipeline when indexing a document of that type. At the moment I' using code like that

    $elasticaIndex = $this->getBackend()->getIndex(); //returns a \Elastica\Index object
    $type = $elasticaIndex->getType( 'office' );
    $docs = [];
    foreach( $documentConfigs as $dc ) {
	    $docs[] = new \Elastica\Document( $dc['id'], $dc ); //$dc contains a field 'data' with the base64 encoded file
    }
    
    $result = $type->addDocuments( $docs );
    $elasticaIndex->refresh();

I believe I somehow need set "pipeline=attachment" in the Bulk-Request. But I don't know how. Any help would be much appreciated!

[1] https://www.elastic.co/guide/en/elasticsearch/plugins/5.x/using-ingest-attachment.html

**Comment by ruflin** [comment]
The problem is that currently there is not really pipeline support in Elastica and we should definitively add it.

As far as I can see, even though mapper attachment is deprecated, it should still work. At least it does in our tests: https://github.com/ruflin/Elastica/blob/4666078db27d2574171c9fe1bba5d7782b2ae7cf/test/lib/Elastica/Test/IndexTest.php#L215

**Comment by dabroek** [comment]
Instead of calling `addDocuments` on the client directly, I've solved this by setting a request param on a `Bulk` request:

```php
$bulk = new Elastica\Bulk($this->client);
$bulk->setType($type);
$bulk->setRequestParam('pipelines', 'processor');
$bulk->addDocuments($documents);
$bulk->send();
```

**Comment by osnard** [comment]
This sounds like a nice workaround. Thanks for sharing!
