### ISSUE TITLE
[range] query does not support [date] [index: story]

### ISSUE THREAD

**Issue by shiveshk** [ruflin/Elastica#1256]
Hello,

I'm tryning to use range filter in my query but I get this message :
[range] query does not support [date] [index: story] at C:\\xampp\\htdocs\\KonnecteZ\\vendor\\ruflin\\elastica\\lib\\Elastica\\Transport\\Http.php:170)"}

$qb = new \Elastica\QueryBuilder();
$query = new \Elastica\Query($qb->query()->range('systemCreatedAt', array('gt' => $fromDate)));
$query = new \Elastica\Query($qb->query()->range('systemCreatedAt', array('lt' => $toDate)));
$result = $finder->find($query);

FYI, I'm using FOSElasticaBundle. Any help please ?

**Comment by ruflin** [comment]
Which version of Elastica and Elasticsearch are you using? It seems more like you get an error from elasticsearch directly.

**Comment by shiveshk** [comment]
Sorry to bother you guys
problem is resolved, I was missing some basic think in writing query
You can close issue now.
