### ISSUE TITLE
Search::count() modifies query

### ISSUE THREAD

**Issue by z38** [ruflin/Elastica#1261]
When calling `Elastica\Search::count($query)` with a `Elastica\Query`, the query gets modified. Specifically, the param `size` is set to zero.

Example:
```php
$client = new Elastica\Client();
$search = new Elastica\Search($client);

$query = new Elastica\Query();
var_dump($query->hasParam('size')); // false
$search->count($query);
var_dump($query->hasParam('size')); // true
```

I'm not sure whether this is the intended behavior, please feel free to close this issue in case it is expected to work like this.

**Comment by ruflin** [comment]
I think the idea here was to set a default. Will it have any affect on your querey? Does it also reset if you set a size before?

**Comment by z38** [comment]
As it's not documented, I didn't expect that the query gets modified and assumed it will be the same after counting. The param is set to `0` in every case.

I was trying to figure out if this should be fixed here or in FOSElasticaBundle (which is tracked in [#1215](https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/1215) now).

**Comment by XWB** [comment]
@z38 Everyone using Elastica could face this issue, not just `FOSElasticaBundle`.

**Comment by XWB** [comment]
https://github.com/ruflin/Elastica/pull/1264
