### ISSUE TITLE
Add Geo bounds aggregation feature

### ISSUE THREAD

**Issue by cobak78** [ruflin/Elastica#1270]
First, thank for an awesome library.

Looking for new features to add on my api, I can't find the geo bound aggregation inside metric aggregations. As elasticsearch explains here. https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-geobounds-aggregation.html

It's something to be expected on the library roadmap?

Thanks

**Comment by ruflin** [comment]
Closing as https://github.com/ruflin/Elastica/pull/1271 was merged.
