### ISSUE TITLE
2.1.0 release does not have `test` folder.

### ISSUE THREAD

**Issue by JWZH** [ruflin/Elastica#1274]
I downloaded version [2.1.0](https://github.com/ruflin/Elastica/archive/2.1.0.tar.gz) and this is the directory structure: 
```
➜  Downloads cd Elastica-2.1.0
➜  Elastica-2.1.0 ls
ansible  CHANGELOG.md  composer.json  CONTRIBUTING.md  docker-compose.yml  Dockerfile  env  lib  LICENSE.txt  Makefile  phpdoc.dist.xml  README.md  Vagrantfile
```
There is not `test` folder in the root directory and this seems inconsistent with the `autoload` in  `composer.json`
```
➜  Elastica-2.1.0 cat composer.json| jq '.autoload'
{
  "psr-4": {
    "Elastica\\": "lib/Elastica/",
    "Elastica\\Test\\": "test/lib/Elastica/Test/"
  }
}
```
Is is possible the `composer.json` be updated or the `test` folder be added ?

**Comment by ruflin** [comment]
This was solved in later versions by moving tests under `autoload-dev`: https://github.com/ruflin/Elastica/blob/2.3.1/composer.json#L33 2.1.0 is quite an old version. I would recommend you to update to a more recent 2.x version.

**Comment by thaiphv** [comment]
@ruflin, do later versions work with ES 1.5?

**Comment by Tobion** [comment]
Closing as this is expected. If you want to have the tests (to run unit tests in vendor library or whatever reason) you can install it with composer --prefer-source.
