### ISSUE TITLE
Class Elastica\Client not found

### ISSUE THREAD

**Issue by daVinciCEB** [ruflin/Elastica#1278]
I'm trying to test the library to see if I can use it for my project. I just copied and pasted the code from the [Elastica Installation Page](http://elastica.io/getting-started/installation.html) to autoload the functions so that I could test it, but whenever I try to run my file it tells me that Elastica\Client class is not found.
I put in some echo's to try and find what is going wrong, and it looks like the file is not found, however, I know I'm using the correct path to the file, because when I use require_once to the file it can find it just fine.

```
function __autoload_elastica ($class) {
    $path = str_replace('\\', '/', substr($class, 1));
    if (file_exists('/php_scripts/Elastica/' . $path . '.php')) {
        require_once('/php_scripts/Elastica/' . $path . '.php');
    }
}
spl_autoload_register('__autoload_elastica');

$elasticaClient = new \Elastica\Client(array(
    'host' => $ELASTIC_HOST,
    'port' => $ELASTIC_PORT
));
```
This is the code, copied and pasted directly from the elastica.io installation page. The only thing that I changed is the path in the autoload function.

**Comment by ruflin** [comment]
TBH I haven't checked the code on the Elastica for quite some time as nowadays most people use composer to install the dependency which does the magic for you. One thing I spotted above, is that you have `'/php_scripts/Elastica/'` but I think this should be `'/php_scripts/'`?

**Comment by daVinciCEB** [comment]
The reason I had `'/php_scripts/Elastica/'` is because it is supposed to point to the `lib` folder in your repository (so that the autoloader can then find the file paths and the classes correctly), and that is the path that points to it.

I actually was able to figure it out on my own, using composer and comparing the differences in the `git clone` installation and the composer installation. The reason that this is happening is because when you do the normal `git clone`, it doesn't load the Psr library files, or the Elasticsearch library files. Because of this, the initialization of the `\Elastica\Client` class fails (since it uses both of these libraries), and then the class can't be found.

You should update the documentation and the dependencies section to include that they need to download and load these libraries as well when installing through `git clone`.

Other than that, I love the library! Installing through composer was able to resolve all of the errors, and it's perfect for what I'm trying to do!

**Comment by ruflin** [comment]
Got it. I kind of blindly assumed it fails because it cannot find the file. But it failed because of missing dependency. We definitively must update our docs. If you have time for a PR https://github.com/ruflin/elastica.io ... ;-)

Glad to hear you like the library.

I'm going to close the issue as I think it was resolved.
