### ISSUE TITLE
how you can add aggregation of type sum_bucket? am i right that it is not possible?

### ISSUE THREAD

**Issue by matak** [ruflin/Elastica#1279]
`
"sum_costs": {
      "sum_bucket": {
        "buckets_path": "per_month>per_month_costs"
      }
    }
`

**Comment by ruflin** [comment]
We currently don't have the `sum_bucket` aggregation as an object. You can always create a query / aggreation with a raw array object: http://elastica.io/example/raw-array-query.html

BTW: It is fairly easy to add a new aggregation. See https://github.com/ruflin/Elastica/tree/master/lib/Elastica/Aggregation for examples. Interested in opening a PR? :-)

**Comment by matak** [comment]
raw-array-query is fine, but it is not possible to combine it, if you build your query in functions, and query is quite complex you dont know exactly on which level you are, so it would helped me if i can insert raw array to the fluent structure if you understand?

PR? what does it mean?

**Comment by ruflin** [comment]
You should be able to add raw parts by using `setParams` or / and `setRawParams`, but I never tried to for this use case.

PR stands for Pull Request. You could fork the Elastica repository and open a Pull Request with this new feature.

**Comment by matak** [comment]
ok i will try PR, thanks
