### ISSUE TITLE
Type->exists() not returning correct data

### ISSUE THREAD

**Issue by daVinciCEB** [ruflin/Elastica#1280]
I have a function that checks to see if a type exists in the index that I am creating. I have already created the type on my server, but when running `Type->exists()`, I am receiving false.

I checked the underlying code in the `exists()` function and tested it to see what the endpoint is returning, and it is returning a 404 not found, even though when I go to the type endpoint in the browser I can see it clearly.

**Comment by daVinciCEB** [comment]
Side note, it looks like this is only happening on the `Type->exists()`, since I'm using `Index-exists()` and that seems to be fine.

**Comment by ruflin** [comment]
Which version of Elastica and Elasticsearch are you using?

**Comment by daVinciCEB** [comment]
latest versions of both

**Comment by ruflin** [comment]
We have some tests for `exists()` here and they seem to be ok: https://github.com/ruflin/Elastica/blob/master/test/Elastica/TypeTest.php#L899 Can you be more precise which versions you are using. Latest changes on a daily base ;-)

**Comment by daVinciCEB** [comment]
Let me run some tests on it and see what it could be.

**Comment by deguif** [comment]
Closing as `type` is not anymore supported since ES 7.x
