### ISSUE TITLE
Filter Query with Aggregation

### ISSUE THREAD

**Issue by kdlug** [ruflin/Elastica#1289]
What is the best way to aggregate filtered query (perform an aggregation at the end of a search request, on filtered results) ? Since Elastica 5 Query class has only setPostFilter() method but in this case aggregations are performed before filtering.

**Comment by ruflin** [comment]
You can always use `raw query` for that in Elastica: http://elastica.io/example/raw-array-query.html

But we should definitively add support for this on an "object" level in Elastica. Interested in opening a PR for it?

**Comment by elshobokshy** [comment]
I am looking to do the same thing .. Still not possible without raw queries? As raw queries will force me to re-writ all of my code.

**Comment by ruflin** [comment]
I don't remember that someone opened a PR to add this feature, so it seems to be still not available.

@elshobokshy If the above works for you, you can just use `setParam` on your query object and don't have to use raw queries.
