### ISSUE TITLE
[5.2] Index::setSettings broken?

### ISSUE THREAD

**Issue by nickygerritsen** [ruflin/Elastica#1295]
It seems that in 5.2+ `setSettings` on an `Index` is broken. It tries to set the settings on the whole cluster instead of only the index.

In 5.1 this still works.

If I take a short look at the code it seems `Elasticsearch\Endpoints\Cluster\Settings\Put` is the wrong class and we should use `Elasticsearch\Endpoints\Indices\Settings\Put` instead?

**Comment by ruflin** [comment]
@nickygerritsen Thanks for reporting. I think you are right. Could you open a PR with a bug fix?

@ewgRa FYI

**Comment by ewgRa** [comment]
@nickygerritsen I think you are right. Can you make pull request? It is trivial, and would be nice to cover this case by test.

**Comment by nickygerritsen** [comment]
On it!
