### ISSUE TITLE
Close index

### ISSUE THREAD

**Issue by Mikevandee** [ruflin/Elastica#1300]
Please use the _close endpoint for closing index.
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-open-close.html

**Comment by p365labs** [comment]
@Mikevandee why are you thinking Elastica did not use that methods for opening and closing indices ? 

Have a look here ***[Elastica\Index.php](https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Index.php#L360)***

**Comment by Mikevandee** [comment]
Sorry I had a miss match in elasticsearch version. And called _dissmis not _close.
