### ISSUE TITLE
Elastica should set the Content-Type header when sending json via Http

### ISSUE THREAD

**Issue by nomoa** [ruflin/Elastica#1301]
Not setting `Content-Type` header in the request headers will now produce (elasticsearch 5.3) a deprecation warning in elastic logs.
I think that Elastica should set this header when sending json.
The deprecation warning is :
`[2017-05-11T13:40:27,556][WARN ][o.e.d.r.RestController   ] Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.`

**Comment by ruflin** [comment]
@nomoa 200% agree. Could you open a PR for that?

**Comment by camohub** [comment]
I have this problem with older version of Elastica but now Elasticsearch 6 throws an error Content-Type header [application/x-www-form-urlencoded] is not supported 
I need to find out how to set headers for request. Can somebody show me the way how to do it?
