### ISSUE TITLE
Adjacency Matrix Aggregation

### ISSUE THREAD

**Issue by mtdavidson** [ruflin/Elastica#1307]
I'm looking at doing a PR to add the [`Adjacency Matrix Aggregation`](https://www.elastic.co/guide/en/elasticsearch/reference/5.3/search-aggregations-bucket-adjacency-matrix-aggregation.html) introduced in 5.3. The library is currently targeted to do 5.2 so need to upgrade it to 5.3 before I can do this, happy to attempt a PR for this as well. 

@ruflin Is there anything blocking upgrading the library to target 5.3 or even 5.4?

**Comment by ruflin** [comment]
@mtdavidson Can't think of anything holding us back going to 5.3 or event 5.4. Perhaps you can do 2 PR's. One updating the docker images to 5.4 and an other one with the Matrix part. Like this we know in case things break with 5.4.

**Comment by deguif** [comment]
Closing as it was implemented in #1642
