### ISSUE TITLE
Missing support for span queries

### ISSUE THREAD

**Issue by alekitto** [ruflin/Elastica#1316]
`span_*` queries are currently unimplemented in Elastica; this is evident looking into the QueryBuilder class which throw a `NotImplementedException` for every `span_` method.

Documentation on the span queries can be found here: https://www.elastic.co/guide/en/elasticsearch/reference/current/span-queries.html

**Comment by ruflin** [comment]
@alekitto Good point. Interested to do a contribution? :-D

**Comment by alekitto** [comment]
@ruflin I've submitted a WIP PR for this, i'll try to complete it during this weekend.
