### ISSUE TITLE
Problem mapping all parameters of a curl query to Elastica

### ISSUE THREAD

**Issue by Nanocl** [ruflin/Elastica#1326]
I've the following query:

{
    "query": {
        "bool": {
            "should": [
            {
                "match": {
                    "title": {
                        "type": "phrase_prefix",
                        "query": "{QUERY}",
                        "max_expansions": 50,
                        "operator":  "and",
                        "slop":  10,
                        "boost": 2
                    }
                }
            },
            {
                "multi_match": {
                    "type": "phrase_prefix",
                    "query": "{QUERY}",
                    "fields": [
                        "teaser"
                    ],
                    "operator": "and"
                }
            },
            {
                "multi_match": {
                    "query": "{QUERY}",
                    "fields": [
                        "title"
                    ],
                    "operator": "and",
                    "fuzziness" : "AUTO",
                    "boost": 2
                }
            }
            ]
        }
    }
}

That works good if I send the request via curl.  
But I've some problems to generate exactly the same query using the Elastica framework. What I've already built is the following:

$boolQuery = new BoolQuery();

$matchTitle = new Match();
$matchTitle->setFieldType('title', 'phrase_prefix')
    ->setFieldQuery('title', $this->queryString)
    ->setFieldMaxExpansions('title', 50)
    ->setFieldOperator('title', 'and')
    ->setFieldBoost('title', 2);
$boolQuery->addShould($matchTitle);

$matchTeaser = new MultiMatch();
$matchTeaser->setType(MultiMatch::TYPE_PHRASE_PREFIX)
    ->setQuery($this->queryString)
    ->setFields(['teaser'])
    ->setOperator(MultiMatch::OPERATOR_AND);
$boolQuery->addShould($matchTeaser);

$matchFuzzy = new MultiMatch();
$matchFuzzy->setQuery($this->queryString)
    ->setFields(['title'])
    ->setOperator(MultiMatch::OPERATOR_AND)
    ->setFuzziness(MultiMatch::FUZZINESS_AUTO);
$boolQuery->addShould($matchFuzzy);

F.e. I've found no way to set the slop on the Match and the boost on MultiMatch.

**Comment by ruflin** [comment]
Each query type should have the method `setParam(key, value)`. Could you try to use this?

**Comment by Nanocl** [comment]
That's not the best solution but it works and solves my problem. Thanks!

**Comment by ruflin** [comment]
@Nanocl Happy to accept a PR to add support for SetSlop. Most of these functions are only nicer proxies for setParam(...).
