### ISSUE TITLE
Not issue: I am looking to implement two functions.

### ISSUE THREAD

**Issue by helloakhilg** [ruflin/Elastica#1328]
Thanks for this plugin.
I am looking to implement two functions as:

1.  Sorting based on exact result
**Ex.** If somone search samsung s7 then i can get the result for both samsung & s7. I need to sort as samsung s7 should come first.

2. Search the nearest match or auto correct if spell mistake. 

**Ex.** Lets say someone search **iphona** by mistake. So system can able to find iphone products

Can you please give me right direction to implemnet this.

**Comment by ruflin** [comment]
I think you are looking for something like Fuzzy queries? https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-fuzzy-query.html If oyu know what queries your looking for in elasticsearch, using it in Elastica should be quite forward. Closing this as I think it's not Elastica related, but please feel free to open.
