### ISSUE TITLE
SetMinimunNumberShouldMatch ?

### ISSUE THREAD

**Issue by Mbt21** [ruflin/Elastica#1329]
I getting message this
Deprecated: Deprecated: Elastica\Query::setMinimumNumberShouldMatch() is deprecated and will be removed in further Elastica releases. Use Elastica\Query::setMinimumShouldMatch() instead. in/var/www/html/extensions/Elastica/vendor/ruflin/elastica/lib/Elastica/Query/BoolQuery.php on line 105

how to fixit?

**Comment by ruflin** [comment]
Not sure I can add anything to the above message? Did you switch the method? Or perhaps I miss the point?

**Comment by Mbt21** [comment]
I don't know to fixed this problem, I already to instal on mediawiki see https://testwiki.wiki locate bug at searching page. What method do you mean?

**Comment by ruflin** [comment]
In the error you posted above it states:

  > Deprecated: Elastica\Query::setMinimumNumberShouldMatch() is deprecated and will be removed in further Elastica releases. Use Elastica\Query::setMinimumShouldMatch() instead. "

So you should replace `setMinimumNumberShouldMatch` with `setMinimumShouldMatch`

**Comment by Mbt21** [comment]
why you can't changed in this file so can't bug in other mediawiki Instalations?

**Comment by Mbt21** [comment]
@ruflin where I can edit? I have some edit but error

**Comment by Mbt21** [comment]
see this display bug https://testwiki.wiki/wiki/Special:Search/Elastic

**Comment by ruflin** [comment]
Ok, so you are using mediawiki. And mediawiki has Elastica as a dependency. It's up to mediawiki to switch to a newer dependency. The reason it is shown has to do with your `error_reporting` settings which you should adjust: http://php.net/manual/en/function.error-reporting.php Closing this as it is not an Elastica issue. But you can still continue the discussion if you have further questions.
