### ISSUE TITLE
Javascript language plugin support deprecated in ES 5.0.0

### ISSUE THREAD

**Issue by yashtodi94** [ruflin/Elastica#1342]
The elasticsearch javascript language plugin is deprecated. Should the `LANG_JS` constant be removed from 'library/Elastica/Script/AbstractScript.php' ?

Reference: https://www.elastic.co/guide/en/elasticsearch/plugins/current/lang-javascript.html

**Comment by p365labs** [comment]
yes the Javascript it's not the only scripting language deprecated in ES 5.x (groovy, etc); but these are deprecated and will be removed in the next major. The idea is to remove it in the 6.x release.

**Comment by yashtodi94** [comment]
Oh ok. I suggested it because I struggled with it for an hour :)
This issue can be closed.

Just to satisfy my curiosity, whats the reason behind it being released in 6.x release? Is it to provide some kind of backward compatibility or something similar?

**Comment by p365labs** [comment]
Usually deprecating represent a warning to developers or users, that the functionality will be removed soon. It's a period of time the deprecated functionalities still work, which allow developers to migrate to the new one (in this specific example migrate to the *painless* scripting language). That's the reason why LANG_JS is still in the current Elastica Release.

you can find some references here : 
- (ES Scripting)[https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting.html]
- (Painless scripting)[https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-painless.html]

**Comment by p365labs** [comment]
@ruflin  this isssue can be closed

**Comment by ruflin** [comment]
@p365labs Thanks. As these were removed in 6.0 I think we should remove them from the code base as the next release of master is probably going to be 6.0. WDYT?

**Comment by p365labs** [comment]
hi @ruflin, yes LGTM ! I'm would like to have a test environment to tests es5 indices against ES6.0 (cause 6.0 still mantain compatibility with ES 5.0 multiple type indices....). From the 7.0 the will drop support for this kind of indices. So at the momento I'm trying to update the tests environment to test it against 5.0 indices even with ES5 and ES6 and I would like to push it on the same branch of #1340 ... let's see what happen then.

**Comment by ruflin** [comment]
Curious to see what you are up to. The part I worry is that this could make our test suite quite a bit more complex. It would mean you have to create 5.x indices and then upgrade to 6.0.

**Comment by p365labs** [comment]
ur right! For the moment I'm just trying to understand which level of compatibility have 5.x indices with 6.x and +;

The idea for the moment is to execute tests on a ES5.0 cluster snapshotting that indices and restore on a 6.0-beta1 cluster and execute the tests again. 

Maybe could be a good point for start an issue and prepare some tasks to reach 6.x release.

**Comment by ruflin** [comment]
In general 5.x indices are compatible to be migrated to 6.x but all indices created on 6.x will only support 6.x feature for example like no types. Agree to move this discussion to #1340 and create a separate github issue on what needs to be done.
