### ISSUE TITLE
Version 5.x compatible with ES 2.4.x?

### ISSUE THREAD

**Issue by aguvillalba** [ruflin/Elastica#1343]
Hi,
Is Elastica v5.x compatible with ES 2.4.x? Because I'm trying to run Elastica 3.2.3 under PHP 7 but there some issues with it.

Thanks in advance.

**Comment by p365labs** [comment]
There are a lot of BC breaks on Elastica 5.x. In order to use it u should upgrade Elasticsearch 5.x.
Have a look [here](http://elastica.io/2016/11/09/release-5-dot-0-0-beta1/) you could also check the [official blog post](https://www.elastic.co/blog/elasticsearch-5-0-0-released)from elastic.co

**Comment by ruflin** [comment]
Closing this issue as I think this is answered. Please reopen if this is not the case.
