### ISSUE TITLE
Upgrade to Elasticsearch 6.0

### ISSUE THREAD

**Issue by p365labs** [ruflin/Elastica#1345]
This issue is to track the open tasks to make Elastica fully compatible with elasticsearch 6.0.
Elasticsearch introduces many [breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking-changes-6.0.html) follow a list of things I discovered with 6.0. 
I think we should start from here, I've tried to replicate the same issue we created for ES5 upgrade.
We should merge #1340 on master and start creating PR's on that (a I have a couple ready).

At the moment there's a PR #1340 where I have skipped all the failing tests and tried to references some errors on ES documentation or directly to the ES source code on github. 

The main issues are related to the removal of multiple types per index: more or less **25 tests**. 

- [x] Testing : Fix tests which are currently skipped because of incompatibility
- [x] Join Fields implemented over hierarchy relationship between types
- [x] New way of ingesting documents (through pipeline ingestion and ingestion-attachment plugin), with tests.
- [x] Implement attachment processor
- [x] Implement Pipeline & Processors
- [x] ES 6 remove multiple type per indices. 6.0 
- [x] Remove attachment plugin
- [x] drop php 5.x support
- [x] switch elasticsearch-php to dev-master until they release a stable version for ES6 (the re-set a version on composer)
- [x] ES 6 support only strict boolean type

@ruflin and the others  what do u think ?

**Comment by ruflin** [comment]
LGTM 👍

**Comment by p365labs** [comment]
great! so if we merge the #1340 then we can start creating PRs

**Comment by ruflin** [comment]
Done, see my comments there.

**Comment by p365labs** [comment]
@ruflin Hi, I will take this week to solve the 70% of tests skipping related to Type BC on Elasticsearch 6.0 (only 1 type per indices).  Just a note to take it in mind  (and maybe to add in the task list): the guys of elasticsearch/elasticsearch-php are updating their code in the dev-master in order to make it pass tests on ES 6.0. After their rework maybe something should be updated also in Elastica but I'm not sure (is just a note to remind us a review after it). 

Most important thing is that in dev-master (so probably in the next release of the client) they have dropped support for PHP 5.X... we should start thinking on it before implementing the new client version and probably this is the right place to start discussing on it.

what do u think ?
(i'll update tasks list)

**Comment by ruflin** [comment]
@p365labs Thanks for all the work on this so far. 

* We definitively have to update to the most recent version of elasticsearch-php as soon as the changes are in from @polyfractal I don't expect anything major to break on our side.
* We should also drop support for 5.x especially as we rely on the official client. I see Elastic in the future mainly as a high level client which is on top of the official client, so it fully relies on it. We should follow the official client model. Not keeping it compatible will also simplify our code base. At least that is my point of view :-)

**Comment by p365labs** [comment]
@ruflin  
- I'll make some tests with the new elasticsearch-php client 
- I agree with you, in order to move in the same direction of the elasticaserch-php client we should drop support for php 5.x

**Comment by polyfractal** [comment]
Hey all :)

Sorry for the delay on the 6.0 release, ran into a few unexpected problems (both in ES-PHP and upstream in core).  I'm hoping to have the tests passing again today or tomorrow, followed quickly by a release so you all can start working on a tagged release instead of dev-master.

I don't expect any of it to impact Elastica, the changes have been mostly test cleanup and getting Travis to play nicely.  I merged some 6.0 specific commits about a month ago, but iirc they were all API additions, nothing that should break bwc.

I'll ping you all once I cut a 6.0 branch and tag a release!

**Comment by ruflin** [comment]
@p365labs Agree on working with `dev-master`. I was even thinking of making that default in the master branch. The only problem it will cause is that I will have to start with release branches. Nothing really bad but I like the lean release process I have now :-) In any case, that is a decision we can make later. Lets switch it to `dev-master`.

**Comment by p365labs** [comment]
@ruflin I agree with you I think for the moment we can use this flow. This is something we can start thinking after we have released a stable version for ES 6.0.

**Comment by p365labs** [comment]
@ruflin PR #1356 switch to dev-master and drop php5 support ready :)

**Comment by polyfractal** [comment]
Just FYI, I cut a 6.0 branch and tagged `v6.0.0-beta1` (https://github.com/elastic/elasticsearch-php/tree/v6.0.0-beta1) if you want to use that.  I don't really expect anything to change before `v6.0.0`, but figured a beta would be a good idea in case you turn up anything broken during the integration and before Elasticsearch 6.0 is GA. :)

At some point I have plans to default ES-PHP `dev-master` to track Elasticsearch master (aka 7.0 at this point), but need to make some changes to the travis config first... don't see that happening for awhile to be honest :)

**Comment by p365labs** [comment]
Thanks @polyfractal we already have a PR that switch to dev-master of es-php. We can also switch it to beta1 branch. Thanks a lot!

**Comment by p365labs** [comment]
we have now 37~ tests skipped, most of them are related to the change with JOIN FIELDS. I'll work this week on it :)

**Comment by ruflin** [comment]
That is great. Really appreciate all the work you put in this so far and the very high quality of your PR's. My main job is hitting merge :-)

**Comment by p365labs** [comment]
Thx @ruflin a lot of fun here :)

**Comment by p365labs** [comment]
I'm working at the moment on "Implement tests for ingest-attachment plugin" it will take a bit as now attachment are managed by Ingest Pipelines, which are not implemented in Elastica, so I need to implement it first and the attachment one.

**Comment by p365labs** [comment]
@ruflin I added Pipeline and Processors as we need it in order to implement and test the ingest-attachment plugin.

**Comment by ruflin** [comment]
Looking at the still skipped tests it seems that most of them are related to using more then 1 type in the tests: https://travis-ci.org/ruflin/Elastica/jobs/274954547 Based on this my assumption is that the code base itself is fully compatible with ES 6.0 but our tests are not fully up-to-date.

**Comment by p365labs** [comment]
Yes that is true, but not completely : 

the failing tests are related to two main problems :

- the new ingest-attachment plugin did not use an attachment field on an index but uses a Processor in a pipeline. So 4 tests in **IndexTest.class** should be removed and must implement the flow with the attachment processor, which now exists (that's why I did not implement a functional test on that processor I would like to do it in a separate PR).  
- JOIN FIELDS : all the other tests failing are related to parent/child mapping. In the [roadmap document](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/removal-of-types.html#_parent_child_without_mapping_types) it is explicitly explained that ```New indices no longer support the old-style of parent/child and should use the join field instead.```

So the first point is not that complex and I should do it in a couple of days. The new *Join field * is something that should be implemented from scratch. It will take a bit more in the sense I have to study it first.

We're not far to release a beta for testing Elastica against ES6

**Comment by p365labs** [comment]
Only join fields need to be implemented to make all tests pass.

**Comment by ruflin** [comment]
@p365labs With the last PR closed, it seems we can close this one?

**Comment by p365labs** [comment]
Hi the tests are fixed right now. Yes we can close this one, now we should wait for elasticsearch-php to release a stable version and check if everything works. What about linting and releasing a beta version of Elastica 6 ?

**Comment by ruflin** [comment]
@p365labs Was thinking the same. But I need to check with @polyfractal if he plans any prerelease like a beta1?

**Comment by p365labs** [comment]
@ruflin ok, we are already using a beta1 pre-release of elasticsearch-php client :) 

```"elasticsearch/elasticsearch": "6.0.0-beta1"```

**Comment by ruflin** [comment]
Ah yeah, missed that. I suggest we do then a 6.0.0-beta1 release? Any other PR's we should urgently get in?

**Comment by p365labs** [comment]
completely agree ! 
The only pr pending for me valuable could be the one for php 7.2.. but it's still in WIP and more than this PHP 7.2 is planned to be released on November the 30rd; so I will release the beta1 first.
Eventually we will release a new beta. It is just to release a beta1 and having a version available.
What do u think @ruflin ?

**Comment by ruflin** [comment]
Agree. The 7.2 would be nice to have in but before or after beta1 does not really matter. Will try to find some time to push a beta1 release today/tomorrow.

**Comment by ruflin** [comment]
Closing this issue based on the above comments. Release is out: http://elastica.io/2017/10/05/release-6-dot-0-0-beta1/
