### ISSUE TITLE
No way to delete a type?

### ISSUE THREAD

**Issue by nickdunn** [ruflin/Elastica#135]
I can see methods to delete indexes (`Elastica_Index::delete`) and delete entries (`Elastica_Type::deleteById`) but no way to delete a specific type (`Elastica_Type::delete`?). Is this omitted from Elastica because it is not possible with ElasticSearch, or has it been overlooked?

Thanks!

**Comment by ruflin** [comment]
Closing this one as the delete type part was implemented and exist does not seem to be necessary.
