### ISSUE TITLE
link to examples on elastica.io is incorrect

### ISSUE THREAD

**Issue by yehosef** [ruflin/Elastica#1357]
points to https://github.com/ruflin/Elastica/tree/master/test/lib/Elastica/Test 
which is a 404

**Comment by ruflin** [comment]
Where did you find this link?

**Comment by yehosef** [comment]
sorry for not including it.  From

http://elastica.io/examples/

I click on the link test suite of Elastica
<https://github.com/ruflin/Elastica/tree/master/test/lib/Elastica/Test> which
takes me to

https://github.com/ruflin/Elastica/tree/master/test/lib/Elastica/Test

when it seems it should take me to

https://github.com/ruflin/Elastica/tree/master/test/Elastica

Thanks again for the lib - it's really great!

**Comment by ruflin** [comment]
Ah, got it: The link has changed to: https://github.com/ruflin/Elastica/tree/master/test/Elastica

This is the file that would need fixing: https://github.com/ruflin/Elastica.io/blob/master/source/examples/index.markdown
