### ISSUE TITLE
Can't update document with upsert when it doesn't exist

### ISSUE THREAD

**Issue by matigda** [ruflin/Elastica#1371]
I've been looking for similar issue or test in library but couldn't find it. 
I actually used code from here:
http://elastica.io/migration/0.90.2/upsert.html but mine looks like that:

      $script = new Script('ctx._source.sizes.addAll(['XL', 'S']);');
      $script->setUpsert([ 'sizes' => ['L'] ]);
      $script->setId(3);

      $this->type->updateDocument($script);

and I'm getting error from elastica that says:  

> [filters][3]: document missing [index: app]

I have printed out $requestData in Elastica\Client::updateDocument and it looks like that:

```
array:3 [
  "script" => "ctx._source.sizes.addAll(['XL', 'S']);"
  "params" => array:1 [
    "_id" => "3"
  ]
  "upsert" => array:5 [
    "sizes" => ['L']
  ]
]
```
So I tested the request with REST client and I'm getting the same error. This is probably due to "_id" param in "params" section. I went through code and don't know how to get rid off "params" section that is on the same level as "script" and "upsert".

When I create the document and then send this request, then everything is ok.

I see that in Elastica\Test\TypeTest::testUpdateDocumentWithFieldsSource there is test for it, but with empty id so I assume elastic creates new document each time.

**Comment by ruflin** [comment]
Which Elastica and Elasticsearch version are you using?

**Comment by matigda** [comment]
I installed FOS with "composer require" and assumed that version 5.x will be downloaded automatically, but it's 4.x version. Thank you and sorry for the trouble ;-)
