### ISSUE TITLE
Bug with PHP 7.2

### ISSUE THREAD

**Issue by kukulich** [ruflin/Elastica#1377]
`Warning: count(): Parameter must be an array or an object that implements Countable` in https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Query.php#L333

**Comment by p365labs** [comment]
can you show us the code that generate this error ?

**Comment by kukulich** [comment]
The bug is here: https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Query.php#L425

`Elastica\Query\AbstractQuery` doesn't implement `Countable`.

**Comment by p365labs** [comment]
I confirm that @kukulich is right. 
PHP 7.2 change a bit [count() function](https://github.com/php/php-src/blob/php-7.2.0RC2/UPGRADING) (search for Countable).

```count() now raises a warning when an invalid parameter is passed. Only arrays and objects implementing the Countable interface should be passed.```

I think could it be useful having a PR ready to be merged when PHP 7.2 will be released, at the moment PHP 7.2 is a Release Candidate 2, so not ready for production use.

**Comment by ruflin** [comment]
@kukulich Thanks for reporting. Always good to have people testing early with future versions.

I'm ok with getting a fix in before GA is out as I assume it will not be a breaking change?

@p365labs Thanks for starting the work on this.

**Comment by p365labs** [comment]
hi all! I think we can close this one as this PR #1378 solves the problem :)
