### ISSUE TITLE
Bug in min_doc_count

### ISSUE THREAD

**Issue by osavchenko** [ruflin/Elastica#1379]
In [this lines of code](https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Aggregation/AbstractTermsAggregation.php#L16-L19) we can assign string value to `min_doc_count` and get elastic error. Should we convert value to int here?

**Comment by p365labs** [comment]
ok but phpdoc is clear *@param int $count*
as the code previously supported php 5.x this was the only way. 
Anyway I think u got the point , but if we want to follow that path, 
considering that we have now switched to php 7.0+, it would be really
interesting moving to strict type hinting. 

I already discuss that in another
Pr or Issue with @ruflin. My suggestion is the same. Let's have a minimum version
of Elastica working with ES6.0 and then we can arrange that task.

**Comment by osavchenko** [comment]
Yes, strict type it's the best way. I'll update my PR, thank you

**Comment by p365labs** [comment]
@osavchenko #1548

**Comment by osavchenko** [comment]
Related to Global Typehint Change
