### ISSUE TITLE
Simple scan and scroll example

### ISSUE THREAD

**Issue by bkvaiude** [ruflin/Elastica#1381]
Hello,

I need a help to implement scroll functionality, but it seems [API doc](http://elastica.io/getting-started/search-documents.html) is out dated.

I have tried following approach with given code, it didn't workout

```
foreach ($search->scanAndScroll() as $scrollId => $resultSet) {
    // ... handle Elastica\ResultSet
}
```

## My code

```
    public function getProfiles($query, $scrollId=null)
    {   

        // if($scrollId===null)
        // {
            $this->search
                ->setOption(Elastica\Search::OPTION_SIZE, '1');//Getting error [Elastica\Exception\ResponseException] request [/_search/scroll] contains unrecognized parameter: [size]  
    
        // }
        // else
        //     $this->search->clearOptions();
        
        $this->search
            ->setOption(Elastica\Search::OPTION_SCROLL, '50s')
            ->setOption(Elastica\Search::OPTION_SCROLL_ID, $scrollId);

        $query = new Elastica\Query('{"query":{"bool":{"must":{"term":{"memberstatus":"Active"}}}}}');

        $this->search->setQuery($query);
        // $resultSet = $this->search->search();//Approach ONE
        // return $resultSet;

        foreach ($this->search->scroll() as $scrollId => $resultSet) {//Approach TWO
            echo "__________________________________________________________";
            print_r($resultSet);
            ob_flush();
        }
        // exit("---------------===================================-----------------");
    }
```

Can you please help with sample code?

**Comment by bkvaiude** [comment]
Got one [sample](https://github.com/ruflin/Elastica/blob/master/test/Elastica/ScrollTest.php).
Thanks for the test cases! :+1:

**Comment by Joozty** [comment]
I think this should be corrected. Where is the code of [API doc](http://elastica.io/examples/)? I can fix it

**Comment by ruflin** [comment]
@Joozty Docs are in this repo: https://github.com/ruflin/elastica.io

**Comment by jmada** [comment]
Where I can found a concrete example? :(

**Comment by Joozty** [comment]
@jmada It depends on which version do you use because in newest version `scanAndScroll method` was deprecated.

**Comment by jmada** [comment]
@Joozty I'm using the '^5.3' versión with ES 6.0.1

**Comment by camohub** [comment]
Hi, I need to use Elastica 5.3 with ES2 and call the scroll api. scanAndScroll is gone and I try to do it via request() call like:
    ````$elastic->getIndex( 'event' )->request( '_search?scroll=7s&amp;search_type=scan', 'POST', ['size' => 1000, 'sort' => '_doc'] )->getData();````
in the next round I call requset() this way:
````$elastic->request( '_search/scroll', 'POST', ['scroll' => '7s', 'scroll_id' => $scrollData['_scroll_id']] )->getData();````
but it kill the server with low memory issue. Can you tell me how to do it in kombination of Elastica 5.3 and ES2.1? 
I really dont know where is the probblem.
