### ISSUE TITLE
How to avoid: "Fielddata is disabled on text fields by default. Set fielddata=true on [price] in order to load fielddata in memory by uninverting the inverted index." ??

### ISSUE THREAD

**Issue by StefanGlaesser** [ruflin/Elastica#1389]
Hello,

I'm running elasticsearch 5.6.3 in an symfony 2.8.28 project, using "friendsofsymfony/elastica-bundle": "dev-master" which includes the ruflin/Elastica package in version 5.3.0

When I add any kind of aggregation to my query, I always get
"Fielddata is disabled on text fields by default. Set fielddata=true on [price] in order to load fielddata in memory by uninverting the inverted index." 

My code works on older installations without any problem. What should or can I do?

**Comment by p365labs** [comment]
looks like you did not enabled fielddata : 
have a look [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/fielddata.html#_fielddata_is_disabled_on_literal_text_literal_fields_by_default) hope this could help!

**Comment by StefanGlaesser** [comment]
That was not the problem as the price is an float and not a textfield. But I've got the issue: I've indexed my data all as string types and not the prices as floats. I've explicitly typecasted the records from the database like this:

    $price = (float)$rowDb['price'];

Then it worked :)

**Comment by elshobokshy** [comment]
I did it this way : 

`'field_name' => array('type' => 'text', 'fielddata'=>'true')`
