### ISSUE TITLE
/_count instead of /_search API call?

### ISSUE THREAD

**Issue by burzum** [ruflin/Elastica#1390]
How can I generate a query that uses the `_count` API instead of the `_search` API?

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-count.html

I couldn't figure out how to generate a call to `/_search/` using Elastica.

**Comment by ruflin** [comment]
Is that what you are looking for? http://elastica.io/api/latest/classes/Elastica.Search.html#method_count

**Comment by burzum** [comment]
@ruflin yes and no. I haven't seen a single query using the API I've linked. While this methods is returning the count of the result set it is using the `_search` API and not `_count`? The reason I want to use `_count` is that `_count` seems to be more efficient than `_search` for just getting the count. And I really need just a count in this case.

**Comment by p365labs** [comment]
There is no difference ... some years ago the team at Elasticsearch discussed on **_count**
[here](https://github.com/elastic/elasticsearch/issues/13928) Which is, in fact, a **shortcut** of the _search API with size set to 0.

we could also implement _count into Elastica (as _count on REST API still exists) but as the guys of Elasticsearch leave that endpoint as it is a ***"comvenient simple sugar"***

**Comment by burzum** [comment]
@p365labs thank you! I haven't seen that. Do you have any suggestion on how to deal with large result sets then? We've got an error message or warning when we had more than, I think it was 10k results. For now we increased the size but would prefer to have a better solution to get the count of a filtered query.
