### ISSUE TITLE
Allowed memory size of xxx bytes exhausted Elastica

### ISSUE THREAD

**Issue by insomniac20101** [ruflin/Elastica#1394]
Hi, plz help to solve problem
Allowed memory size of 134217728 bytes exhausted (tried to allocate 64 bytes) in /usr/share/nginx/html/vendor/ruflin/elastica/lib/Elastica/JSON.php on line 32
Thank you

**Comment by p365labs** [comment]
- Hi which version of Elastica r u using ?
- can u describe better what are u trying to do maybe showing us a piece of src code ?

**Comment by insomniac20101** [comment]
hi, Elastic version 2.3.
We are using Amazon AWS EC2 instance as application server. Elastic also here. all worked fine more that 6-8 months . we didnt do any changes .. but last month we got 2-3 error as showned upper. Memory size problem. 

EC2 - T2 medium

website : https://megamart.az
when we do restart of server it again works normally.

**Comment by ruflin** [comment]
How much memory do you have allocated for PHP? Could it be that you have some large queries you send to ES? Queries that grew over time or that you have some large responses with lots of entries? Allocating more memory should be a short term fix but you should have a closer look from your above error message to see if there  is a stack trace with more details on which line in your code causes it.

**Comment by tomekit** [comment]
Experiencing same problem. What's weird it happens on `live`, but doesn't happen on testing environment built from live (same data).
I've got 8GB limit, which is already horribly wrong. When I do profile the code it uses less than 1GB.

This is the error:
`Environment: live, hostname: live-core5
Fatal Error (E_ERROR): Allowed memory size of 8589934592 bytes exhausted (tried to allocate 20480 bytes)
in file `.../vendor/ruflin/elastica/lib/Elastica/JSON.php:34`
UniqueID: 5b1a35c67ea4c`

I am looking for a way to get the full stack trace from FATAL.

Why this might be? That looks like big raw response from ElasticSearch that can't fit in. 
I am requesting 450 documents, it's really unlikely to be bigger than few hundred MBs.

**Comment by ruflin** [comment]
Which Elastica version are you using?

**Comment by tomekit** [comment]
Thanks for your response, I've update my answer, it wasn't the Elastica the issue finally.

**Comment by arkmuay** [comment]
What it was ?...

**Comment by tomekit** [comment]
In my case it was:

> This problem was due to my specific edge case with the environment configuration. There was some recursive issue which was fetching enormous amount of data from ES, failing eventually on one of the request. Nothing wrong with ELASTICA !

**Comment by arkmuay** [comment]
Ok thanks I think it's the same... thanks
