### ISSUE TITLE
Missing support for BucketSelector aggregation?

### ISSUE THREAD

**Issue by george-ionita** [ruflin/Elastica#1397]
Shouldn't there be a "BucketSelector" class in /Elastica/Aggregation? 

https://www.elastic.co/guide/en/elasticsearch/reference/5.5/search-aggregations-pipeline-bucket-selector-aggregation.html

Using Elastica 5.3, ElasticSearch 5.5.

**Comment by p365labs** [comment]
yes you're right :) it's missing. Maybe you could do implement it and create a PR ?

**Comment by george-ionita** [comment]
I needed it yesterday so I wrote it, will make a PR in a bit :)

**Comment by gontrocolo** [comment]
Hey @george-ionita , its been a year since you wrote that. Any update on this?
Thanks :)

**Comment by maltehuebner** [comment]
I added the `BucketSelector` aggregation in #1554.
