### ISSUE TITLE
Waiting for index fill

### ISSUE THREAD

**Issue by Nanocl** [ruflin/Elastica#1400]
I'm trying to test the Elasticsearch communication (ES 5.3) via PHPUnit.
I have the following setup:

protected function setUp() {
  parent::setUp();

  self::$indexName = strtolower(uniqid('PHPUnit_'));
  self::$searchClient = $this->getApplicationServiceLocator()->get('MyNamespace\ElasticSearchClient');
  self::$articleIdList = [
    'even' => [],
    'odd' => [],
  ];

  $searchIndex = new Index(self::$searchClient->getClient(), self::$indexName);
  $searchIndex->create();

  $documentCount = 10000;
  $searchDocumentBulk = new Bulk(self::$searchClient->getClient());
  $searchDocumentBulk->setIndex($searchIndex);
  for ($id = 1; $id <= $documentCount; $id++) {
    $article = [
      'client' => 'test',
      'content' => 'PHPUnit Test Text ' . ($id % 2 === 0 ? 'even' : 'odd') . ' ' . $id,
    ];
    $searchDocumentBulk->addDocument(new ElasticaDocument($id, $article, 'test_type'));
    self::$articleIdList[($id % 2 === 0 ? 'even' : 'odd')][] = $id;
  }
  $response = $searchDocumentBulk->send();
  $this->assertEquals($documentCount, $response->count());
  $searchIndex->flush();
}

Everything works fine, there's no exception etc.
But the problem is that all query tests which follow, will fail because no results were found. I guess the reason is that the tests start before the index is built completely. But I found no way to wait until the index is fullfilled with the articles. Is this a bug or is my code wrong?

**Comment by Nanocl** [comment]
I also tried to replace flush by refresh but the problem still exists.

**Comment by ruflin** [comment]
Did you have a look at the existing Elastica test suite to compare on how it is handled there?

**Comment by Nanocl** [comment]
Yes i already had a look at the existing test suite. But the problem is that I found only unit tests but no integration tests which make "real" calls to the elasticsearch server.

**Comment by p365labs** [comment]
inside test directory you'll find *unit* and *functional* tests. Our test suite uses Docker to execute functional tests against a real Elasticsearch cluster. I've had a look at your code and this will be the the correct code to make it work inside our test suite :

```    /**
     * @group functional
     */
    public function testIssue1400()
    {
        $client = $this->_getClient();
        $index = $this->_createIndex();
        $type = $index->getType('bulk_test');


        $documentCount = 1000;
        $bulk = new Bulk($client);
        $bulk->setIndex($index);

        $articles = [];
        for ($id = 1; $id <= $documentCount; $id++) {
            $articles[] = $type->createDocument($id, [
                'client' => 'test',
                'content' => 'PHPUnit Test Text ' . ($id % 2 === 0 ? 'even' : 'odd') . ' ' . $id,
            ]);
        }

        $bulk->addDocuments($articles);
        $response = $bulk->send();

        $this->assertEquals($documentCount, $response->count());
    }```

I think we can close this issue.
