### ISSUE TITLE
CrossIndex

### ISSUE THREAD

**Issue by p365labs** [ruflin/Elastica#1404]
Hi All, following what I said on #1402 I notice that we still have CrossIndex class which is deprecated.

What about to remove it from master, and so to have it removed from next Elastica release ?

what people guess about it  ? @ruflin  ?

**Comment by ruflin** [comment]
+1 on removing it. I was at first hesitant to remove it as Reindex in ES did not support reindex from Remote. But now it does so this functionality is much better to be used from ES directly.
