### ISSUE TITLE
Allow specify routing per document

### ISSUE THREAD

**Issue by Koc** [ruflin/Elastica#1405]
For now we can specify routing only per `Action`.

When we want batch reindex documents with custom routing - we should create `Bulk`, create `Action` per each document and after this send this bulk. In fact - we have inlined methods `Index::updateDocuments()`, `Client::updateDocuments()`, `Bulk::addDocument()`.

It would be nice add `Document::setRouting()`.

**Comment by ruflin** [comment]
@Koc Interested to open a PR with this addition?

**Comment by Koc** [comment]
Yes, of course, will do

**Comment by Koc** [comment]
I'm so sorry. This already implemented: https://github.com/ruflin/Elastica/blob/master/lib/Elastica/AbstractUpdateAction.php#L236 (`Document` extends from this class),

**Comment by ruflin** [comment]
@Koc I should known, sorry :-( Too many features :-D Thanks for the feedback on the issue.
