### ISSUE TITLE
Docker & Docker compose version

### ISSUE THREAD

**Issue by p365labs** [ruflin/Elastica#1406]
We have fixed versions of Docker and docker-compose on .travis.yml,
what happened is that it looks like TRAVIS updates their images frequently
using last Docker&Docker-compose. 

What happened is that build fails as we do not have allowed ``` --allow-downgrades.``` 
option and so build broke.

I think we have 3 options in order to avoid builds failing due to travis images upgrades :
- enable ```--allow-downgrades``` option on travis and we still have under control our code,
and when we get that point we should retest-it with latest version and if everything works update our *.travis.yml* file
- install the latest version (docker-ce without specifying the version)
- let Travis upgrade their images and use that default versions

The quicker solutions are the second and the third one... but gave us less control, the first one
leave Elastica total control on the build, but with the downside that we should do sometime a commit in order to upgrade Docker & docker-compose.

People & @ruflin what do you think about that ?

**Comment by ruflin** [comment]
I like option one as I prefer that CI runs today and in 2 months should be the same.
