### ISSUE TITLE
Bug in content-type header

### ISSUE THREAD

**Issue by gtavasoli** [ruflin/Elastica#1413]
I upgraded Elasticsearch to version 6.0.0 and this error occurred for me.

> Content-Type header [application\/x-www-form-urlencoded] is not supported

I fixed it by add two line of code to exec method of Http class of Transport.

```
$headers[] = 'Accept: application/json';
$headers[] = 'Content-Type: application/json';
```

**Comment by p365labs** [comment]
Hi @gtavasoli can you show us the code which generate that error ?

**Comment by gtavasoli** [comment]
This is my code as a part of CakePHP project:

```
$query = ['size' => 0, 'query' => ['bool' => ['must' => [['match' => ['from.peer_id' => ['query' => $id]]]]]]];
$query['query']['bool']['must'][] = ['range' => ['date' => ['gte' => $this->start_date_mili, 'lte' => $this->end_date_mili, 'format' => 'epoch_millis']]];
$query['aggs'] = ['dayOfWeek' => ['terms' => ['script' => ['source' => 'doc[\'date\'].date.dayOfWeek', 'lang' => 'painless']]]];
$query = json_encode($query);

$client = new Client(Configure::read('elastic_config'));
$index = $client->getIndex(Configure::read('tg_index'));
$path = $index->getName() . '/_search';
$response = $client->request($path, Request::GET, $query);

$responseArray = $response->getData();
```

**Comment by p365labs** [comment]
@gtavasoli just to understand instead of building the path of the query to execute what happen if you try to use the Search Object ?

```
        $search = new Search($client);
        $resultSet  = $search->search($query);
```

**Comment by ruflin** [comment]
@gtavasoli Which version of Elastica does CakePHP use?

**Comment by gtavasoli** [comment]
Last version (6.0.0)

**Comment by p365labs** [comment]
It sounds a bit weird as this commit 3e3a1affd1b8097ed942ae2364c454ae6872e201 (12/05/2017) sets a default Content-Type.  which is ```Request::DEFAULT_CONTENT_TYPE```

I'll have a look a bit deeper into this 👍 . Anyway @gtavasoli have u tried the piece of code I've sent u a day ago ?

**Comment by gtavasoli** [comment]
Yes, it did not work!
