### ISSUE TITLE
Deprecated field [inline] used, expected [source] instead

### ISSUE THREAD

**Issue by kukulich** [ruflin/Elastica#1416]
Elasticsearch 5.6 sends warning "Deprecated field [inline] used, expected [source] instead" in response header "Warning".

It's caused by https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Script/Script.php#L58

And here is second place where `'source'` should be supported: https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Script/AbstractScript.php#L66

**Comment by p365labs** [comment]
@kukulich yes it has been deprecated and ```inline``` will be removed in favour of source in ES 7.0. The reference could be found (here](https://github.com/elastic/elasticsearch/pull/25127).
