### ISSUE TITLE
\Elastica\Transport\Http uses deprecated each() function

### ISSUE THREAD

**Issue by mkosiedowski** [ruflin/Elastica#1423]
`\Elastica\Transport\Http` code uses `each()` function which is deprecated as of PHP 7.2. This results in flooding logs with `E_DEPRECATED` entries. 

https://github.com/ruflin/Elastica/blob/23f2bf0c7cfdc15a219ada33bb17a4367b5ffddb/lib/Elastica/Transport/Http.php#L118

**Comment by viilveer** [comment]
Same problem is in MultiBuilder:
https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Multi/MultiBuilder.php

Maybe you can create a fix for this also. This should be last one according to github code search.

**Comment by mkosiedowski** [comment]
Sure, please see the new commit in the same PR

**Comment by viilveer** [comment]
Cool. Looks fine by me.

**Comment by franmomu** [comment]
Hi, should this be done in 5.x as well? I've just updated to php 7.2 with that branch.

**Comment by ruflin** [comment]
@franmomu Haven't checked the 5.x branch, but if it's not there, it should also be added there. Can you open a PR?
