### ISSUE TITLE
Bug when create ResultSet with an empty Query in V6.0.0 ?

### ISSUE THREAD

**Issue by aiflu** [ruflin/Elastica#1426]
Hello,
I don’t know if it’s a bug or not. When I wanted to create a ResultSet object with an empty Query object, I got php error : 

    Severity: Parsing Error --> syntax error, unexpected '->' (T_OBJECT_OPERATOR) my_path/Elastica/Query.php 333

Here is my test code (environment: Elastica 6.0.0, php 7.1):

    $resultSetBuilder = new \Elastica\ResultSet\DefaultBuilder();
    $resultSet = $resultSetBuilder->buildResultSet(new \Elastica\Response('{}', 200), new \Elastica\Query());

For some reason, I only need to use the lib Elastica for dealing with the Elasticsearch json response, especially for the aggregation functions (which are only available in ResultSet, like: hasAggregations() etc.). So I try to pass an empty Query object to the buildResultSet function, which worked well with the previous version of the Elastica (5.3.0)
After digging the lib code, I found that “→toArray()” is new in the version 6.0.0. I think the problem is that the “post_filter” may not the right object even it is set.

Can someone help?

Thanks.

**Comment by ruflin** [comment]
I wonder why in your case `post_filter` is set at all? I would expect the if statement to end after the first comparison because it is not set. Are you doing anything with PostFilter?

**Comment by aiflu** [comment]
@ruflin Thank you at first. I wonder too.
It seems that the `post_filter`is set all the time. But I didn't use post_filter at all. As it's a filter after aggregation, so I don't need it in my project at all.
I've searched `post_filter` in all my code, I could only find it in `/Elastica/Query.php` and `/Elastica/Suggest/CandidateGenerator/DirectGenerator.php`. Both files are the lib files, and their setting functions have the same name `setPostFilter`. So I've searched also `setPostFilter` in all my code, but I've found nothing. So I don't understand.

Here is how I debug: I could add `die` before

    $resultSet = $resultSetBuilder->buildResultSet(new \Elastica\Response('{}', 200), new \Elastica\Query());
or at the end of the Query `__construct`.
But I couldn't add `die` at the beginning of the `toArray()` in Query, because I got "syntax error" before. What I couldn't understand is that the error line is after the `die`, how could the code pass the `die`?

**Comment by aiflu** [comment]
@ruflin I've figured out the problem. It's the php version. Is the lib 6.0.0 compatible with php5.6? I've tested locally the same code. With php7.x, all pass, but with php5.6, I've the error. I don't know why, but I'm sure it's the php version caused the error. So I'll update the Php to 7.x to avoid the problem.
Thanks a lot.

**Comment by ruflin** [comment]
Oh, I thought you are using 7.1 as you mentioned in your initial PR description.

We removed compatibility for 5.6 recently. Seems like we forgot to update the Website with this. Sorry about that. 

@carusogabriel Interested to also take this one on? It's in the Elastica.io repo.

**Comment by carusogabriel** [comment]
@ruflin Gonna search and update the docs 📜

**Comment by ruflin** [comment]
That should help: https://github.com/ruflin/elastica.io

**Comment by aiflu** [comment]
@ruflin Thanks a lot. Sorry for the wrong php version in the initial PR description.
Thanks for the doc, I usually read the doc at http://elastica.io/, never thought there's a git where I can find the doc for the previous versions. I'll close this issue.

**Comment by ruflin** [comment]
For the API you can even put the version you are interested in into the URL: http://elastica.io/api/5.0.0/
