### ISSUE TITLE
Call to a member function toArray() on array

### ISSUE THREAD

**Issue by rafaelschmitt** [ruflin/Elastica#1429]
When i run a query then i get this error `Call to a member function toArray() on array`

My Setup:
----
- symfony/symfony v3.3.8
- friendsofsymfony/elastica-bundle dev-master 96c79eb
- elasticsearch/elasticsearch v6.0.0
- ruflin/elastica 6.0.0
- Elastic-Server Version: 6.0.0

Error:
----
```txt
Call to a member function toArray() on array
```

**Entry-point:** (use of FOSElasticaBundle)
```php
$adapter = $finder->createPaginatorAdapter($aqb->getQuery());
$aggData = $adapter->getAggregations();
```

**stack-trace:**
```txt
Symfony\Component\Debug\Exception\FatalThrowableError:
Call to a member function toArray() on array

  at vendor/ruflin/elastica/lib/Elastica/Query.php:333
  at Elastica\Query->toArray()
     (vendor/ruflin/elastica/lib/Elastica/Search.php:455)
  at Elastica\Search->search()
     (vendor/ruflin/elastica/lib/Elastica/Type.php:356)
  at Elastica\Type->search(object(Query))
     (vendor/friendsofsymfony/elastica-bundle/src/Paginator/RawPaginatorAdapter.php:107)
  at FOS\ElasticaBundle\Paginator\RawPaginatorAdapter->getAggregations()
     (src/ggm/ClassifiedAdBundle/Controller/AdvertController.php:455)
  at ggm\ClassifiedAdBundle\Controller\AdvertController->overviewAction(object(Request), 'literatur')
  at call_user_func_array(array(object(AdvertController), 'overviewAction'), array(object(Request), 'literatur'))
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:153)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:171)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/app_dev.php:31)
  at require('/home/kokoloko/projects/php/portal-webapp-2/web/app_dev.php')
     (vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/Resources/router.php:42)
```

Problem
----

The problem is caused by the change of this line in `Elastica/lib/Elastica/Query.php`:
https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Query.php#L333

(see commit: https://github.com/ruflin/Elastica/commit/136e36680eaad95fe5fa0a922ad4673d64e34213)

**Comment by rafaelschmitt** [comment]
Additional info: Actually we set our `post_filter` (like all other things) manually via rawQuery in a array-structure, e.g.:

```php
$rawQuery['post_filter'] = [
    'bool' => [
        'must' => [
            //...
        ]
    ]
];

$this->query->setRawQuery($rawQuery);
```

So calling `toArray()` on `post_filter` will crash:

```php
namespace Elastica;

class Query extends Param
{
    //...
    if (isset($this->_params['post_filter']) && 0 === count(($this->_params['post_filter'])->toArray())) {
        unset($this->_params['post_filter']);
    }
```

Maybe a check if it is already a array would fix this:

```php
namespace Elastica;

class Query extends Param
{
    //...
    if (isset($this->_params['post_filter']) && 0 === count(is_array($this->_params['post_filter']) ? $this->_params['post_filter'] : $this->_params['post_filter']->toArray())) {
        unset($this->_params['post_filter']);
    }
```

**Comment by rafaelschmitt** [comment]
We added a temporary workaround for this. But it would be nice, if you could continue to set the "post_filter" as a raw array, like all other filters.

```php
// same definition like before
$postFilters = [
    'bool' => [
        'must' => [
            //...
        ]
    ]
];

$postFilterQuery = new \Elastica\Query\BoolQuery();
foreach($postFilters as $boolOccur => $filters) {
    $postFilterQuery->setParam($boolOccur, $filters);
}
$this->query->setPostFilter($postFilterQuery);
```

**Comment by ruflin** [comment]
@rafaelschmitt Thanks for digging into this and provide all the details. I think I now fully understand why it happens but not 100% sure about the solution yet.

In Elastica in quite a few places we keep things as object until they they are converted to an array in the `toArray` functions.  That is also the case here with the `post_filter` as we set it here as an object: https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Query.php#L427 I even wonder if it worked previously? So perhaps this even fixed a bug :-D

I understand the need for your request to set it "manually" as a pure array but I wonder how we should accomodate for it in a more general way because the same problem can arise with other `toArray` methods if params were set manually.

@p365labs as you made the change, perhaps you can share some more thoughts?

**Comment by rafaelschmitt** [comment]
@ruflin Thx for your reply and happy new year! ;) Yes, it worked previously without `AbstractQuery` objects, if you use `setRawQuery` (like we do)

Setting a Query fully as raw array worked, also with `post_filter`, e.g.:
```php
$query = new Elastica\Query();
$query->setRawQuery([
    "query" => [
      "bool" => [
        "must" => [
          [
            "match" => [
              "title" => "Search"
            ]
          ]
        ],
        "filter" => [
          "bool" => [
            "must" => [
              [
                "terms" => [
                  "segment" => [
                    "article"
                  ]
                ]
              ],
              [
                "range" => [
                  "accessDate" => [
                    "gte" => "2017-07-01",
                    "lt" => "2017-11-21"
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ],
    "post_filter" => [
      "bool" => [
        // ...
      ]
    ]
]);
```

Now, it still works, but without `post_filter`, because of the new `toArray()` call on `post_filter` in `Query` class (so `$this->_params['post_filter']` is expected to be a object of `AbstractQuery`, even if you set it via `setRawQuery`)

The Query class provides a `setRawQuery` method (which is very very nice ;D ) to set a query manually with array structure. Filling a query via objects is also nice. But i think, if you set the `post_filter` via `setRawQuery`, then it should work without objects. But now it does not unfortunately, because a specific key in the array is expected to be a object, even if it was set by `setRawQuery`, what in this case (in the raw-mode case) is not correct in my opinion.

**Comment by ruflin** [comment]
@rafaelschmitt To move forward, I suggest you open a PR with the "fix" as the above is kind of a breaking change on our side we didn't intend to do. We can afterwards still figure out a more generic way on how we deal with these things.
