### ISSUE TITLE
Problem with exact search query with Elastica QueryBuilder

### ISSUE THREAD

**Issue by yvoloshin** [ruflin/Elastica#1433]
Hello,

I'm having a problem with an Elastica QueryBuilder exact search in a Symfony app. The Elastica version is 2.1, which depends on Elasticsearch 1.5.2. I posted this question on stackoverflow, but haven't gotten any answers.  
I'm searching an index where one of the fields is mapped as

    majors:
       type: string
       index : not_analyzed

This field is a student's major that can have one or more words, such as "Ancient History". The value of the "majors" field is passed to the query in an array called $params as $params['majors'].

The query is set up like this:

    /** @var  ElasticaFactory $ef */
    protected $ef;
    public function __construct(ElasticaFactory $ef)
    {
      $this->ef = $ef;
    }

    $query = $this->ef->createQuery();
    $qb = $this->ef->createQueryBuilder();
    $bool = $qb->filter()->bool();

    $query->setQuery(
         $qb->query()->filtered(
              $qb->query()->term(),
              $bool->addShould(
                  $qb->filter()->term(
                      array('majors' => $params['majors'])
                  )
              )
         )
     );

When I run this query, I get a SearchPhaseExecutionException error. The full text of the error message is [here](https://i.imgur.com/4c4wuEa.png). The error message states "query malformed, no field", but I'm confused about what this means, since the field is passed to the query as an array. 
Stack trace shows the full contents of the request:

    Client ->request ('students/_search', 'GET', array('query' => array('filtered' => array('query' => array('term' => array()), 'filter' => array('bool' => array('should' => array(array('term' => array('majors' => 'Ancient Studies')))))))), array('from' => '0', 'size' => '10'))
    in /vagrant/persona/vendor/ruflin/elastica/lib/Elastica/Search.php at line 455 

When I set up the query as a "match" below, it works with no errors:

    $query->setQuery(
        $qb->query()->filtered(
             $qb->query()->match('majors', $params['majors']),
             $bool
        )
    );

However, a match query returns too many irrelevant results. I need specifically an exact search query.
Any help would be appreciated!

**Comment by ruflin** [comment]
Any chance you could paste the error as text? It's pretty hard to search in images :-(

Did you try to build the query for ES directly and see if it works? That would be great to see if there is an error with the Elastica query or in an issue with your query.

**Comment by yvoloshin** [comment]
Hi @ruflin,
Here is the error text:

SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[IEHwxwCSR4Cux6bxcgD6WQ][students][4]: SearchParseException[[students][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"term":[]},"filter":{"bool":{"should":[{"term":{"majors":"Art History"}}]}}}}}]]]; nested: QueryParsingException[[students] [term] query malformed, no field]; }{[IEHwxwCSR4Cux6bxcgD6WQ][students][1]: SearchParseException[[students][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"term":[]},"filter":{"bool":{"should":[{"term":{"majors":"Art History"}}]}}}}}]]]; nested: QueryParsingException[[students] [term] query malformed, no field]; }{[IEHwxwCSR4Cux6bxcgD6WQ][students][0]: SearchParseException[[students][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"term":[]},"filter":{"bool":{"should":[{"term":{"majors":"Art History"}}]}}}}}]]]; nested: QueryParsingException[[students] [term] query malformed, no field]; }{[IEHwxwCSR4Cux6bxcgD6WQ][students][3]: SearchParseException[[students][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"term":[]},"filter":{"bool":{"should":[{"term":{"majors":"Art History"}}]}}}}}]]]; nested: QueryParsingException[[students] [term] query malformed, no field]; }{[IEHwxwCSR4Cux6bxcgD6WQ][students][2]: SearchParseException[[students][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"term":[]},"filter":{"bool":{"should":[{"term":{"majors":"Art History"}}]}}}}}]]]; nested: QueryParsingException[[students] [term] query malformed, no field]; }] 

That's a great idea to build the query in ES. I'll try that. In the meantime, do you see any obvious errors in the query, or in the error text?
Thanks a lot for your help!

**Comment by yvoloshin** [comment]
I converted the query into a raw query like this:
```
$query->setRawQuery(array('query' => array('filtered' => array('query' => array('term' => array()), 'filter' => array('bool' => array('should' => array(array('term' => array('majors' => 'Art History')))))))));
```
This gave me the same error message as quoted above. Looks like there is a problem with the query itself, and not with Elastica.

**Comment by ruflin** [comment]
I'm thinking this one is the problem: `[term] query malformed, no field`. The reason is the empty `'term' => array()), `. ES 1.x has been quite some time but it could be the difference between `{}` and `[]`. Do you even need the empty term there?

For the second one which "should" work. What does your doc in ES looki like?

**Comment by yvoloshin** [comment]
I too was wondering about the empty term. When I remove it, the query looks like this:
```
$query->setRawQuery(
     array(
         'query' => array(
            'filtered' => array(
                'filter' => array(
                    'bool' => array(
                        'should' => array(
                            array(
                                'term' => array(
                                    'majors' => 'Art History'
                                     )
                                  )
                             )
                        )
                   )
              )
     )
);
```
This version returned no errors, but also no results. 
I have not been able to find out how to get ES documents in Elastica. Could you tell me how to do that?
Thanks a lot for your help!

**Comment by ruflin** [comment]
What I meant with ES documents is to use for example the Console in Kibana to build to the query in JSON or use curl to send the request. As soon as you have a working json, you can post it here and the "translation" to Elastica should be fairly straight forward.
