### ISSUE TITLE
Please add the possibility to change the request method

### ISSUE THREAD

**Issue by stefpe** [ruflin/Elastica#1441]
https://github.com/ruflin/Elastica/blob/02bf2fbb8ad6b679869af145eed89436a1c50229/lib/Elastica/Search.php#L466

Currently the request method is hardcoded and I need to change it to be able to use a proxy. My current workaround is the following:
```php
        $search = $this->indexType->createSearch($query);
//request via client, otherwise the path string generation will be prefixed again.
        $response = $this->indexType->getIndex()->getClient()->request(
            $search->getPath(),
            Request::POST,
            $search->getQuery()->toArray(),
            $options
        );
        $result = $search->getResultSetBuilder()->buildResultSet($response, $search->getQuery());
```

But what I actually wanted to do would be something like this: 
```php
$result = $this->indexType->search($query, $options, Request::POST);
```

**Comment by ruflin** [comment]
Can you share some details on why GET requests do not work with proxies? Because if that is the case, there are many other requests where this becomes an issue I would think.

**Comment by stefpe** [comment]
Because in the HTTP Transport, you are setting 
`curl_setopt($conn, CURLOPT_POSTFIELDS, $content);`
For elasticsearch somehow a GET Request with filled post body works, but a proxy which doesnt read the POST Body on a GET Request, you run into issues.

**Comment by ruflin** [comment]
Thanks for the details. I'm ok with adding this option. Can you open a PR?

In case the proxy is under your control, I think the proxy should be configured accordingly. But I can see the issue in case the proxy is not under your control.

I wonder what the proxy is that does not support it?

**Comment by ruflin** [comment]
@stefpe I just stumbled over this one: https://github.com/elastic/elasticsearch/pull/28342 It seems the official high level client moved to POST, so I wonder if we should make this even the default?

**Comment by alamirault** [comment]
PR is now merge, I think @ruflin you can close issue.
