### ISSUE TITLE
Please rename `min_word_len` to `min_word_length` on 5.3.0

### ISSUE THREAD

**Issue by shihgangliu** [ruflin/Elastica#1446]
https://github.com/ruflin/Elastica/blob/5.x/lib/Elastica/Suggest/Term.php#L91-L94

I use `ruflin/elastica` on version `5.3.0`.
There is still deprecated parameter `min_word_len` at `lib/Elastica/Suggest/Term.php#93`.
I hope could fix it, thanks.

**Comment by XWB** [comment]
https://github.com/ruflin/Elastica/pull/1447

**Comment by shihgangliu** [comment]
@XWB thank you.

**Comment by kubk** [comment]
It looks like the issue is fixed and can be closed.

**Comment by shihgangliu** [comment]
Sorry I forgot, thanks help.
