### ISSUE TITLE
Support for pipeline when indexing documents

### ISSUE THREAD

**Issue by stof** [ruflin/Elastica#1453]
Currently, the indexing methods in `Type`, `Index` and `Bulk` don't support the `pipeline` option.

AFAICT, the only way to trigger a pipeline when indexing is to instantiate the `Elasticsearch\Endpoints\Index` lower-level API myself, duplicating all the logic of `\Elastica\Type::addDocument`. Is there a better way ?

**Comment by stof** [comment]
Note that I'm using version 5.3 of the library (I'm not yet using ES 6)

**Comment by ruflin** [comment]
I haven't checked the code yet but I don't think there is a better way. But we should definitively have one (in 5.x and master). Want to take a stab at it?

**Comment by stof** [comment]
what is the process to contribute to both 5.x and master ? Should I open my PR against 5.x or master ?

**Comment by ruflin** [comment]
I suggest to open a PR against master and as soon as it's merged, cherry pick it into the 5.x branch and open a PR.
