### ISSUE TITLE
Not able to enable https for AwsAuthV4 transport

### ISSUE THREAD

**Issue by cfoehrdes** [ruflin/Elastica#1456]
We are trying to use the `AwsAuthV4` transport with ssl and are not able to pass the ssl option to it.

It seems that it is not possible because the `ssl` config param accessed in the `AwsAuthV4` class (see https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Transport/AwsAuthV4.php#L77) is never set.
The keys of the config array are limited to `bigintConversion`, `curl`, `headers` and `url` in the client when preparing the transport configuration. (see https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Client.php#L162)

**Comment by cfoehrdes** [comment]
It could be an option to pass the ssl key to the config array or maybe we could also use getParam to fetch the ssl setting, as it is done with the access keys.

**Comment by ruflin** [comment]
@cfoehrdes Feel free to open a PR for further discussions. This should make it more obvious what the changes required would be.

**Comment by cfoehrdes** [comment]
@ruflin The PR #1457 is pretty much what solves the problem

**Comment by ruflin** [comment]
Closing as https://github.com/ruflin/Elastica/pull/1457 was merged.

**Comment by aderuwe** [comment]
@ruflin Seems to have been never closed. ;)

**Comment by ruflin** [comment]
Ups, seems like I hit the wrong button. Thanks @aderuwe
