### ISSUE TITLE
Increase a coverage

### ISSUE THREAD

**Issue by dmitrijivanenko** [ruflin/Elastica#1461]
Hey, I would like to contribute to the project. Wanted to start from increasing the coverage, do you need a help with it, since now it is only 84%?

**Comment by ruflin** [comment]
@dmitrijivanenko I'm more then happy about contributions to the test suite. What I would focus on is not pure coverage number but making sure we add tests for code that is complex and has potential to break. The part that is especially valuable are the functional tests as they tell us when something in Elasticsearch changed and we need to fix it in Elastica.

**Comment by dmitrijivanenko** [comment]
@ruflin thank you, got it. I will look for such places.
