### ISSUE TITLE
Class 'Elastica\Client' not found Laravel

### ISSUE THREAD

**Issue by thiruvenkatam** [ruflin/Elastica#1463]
hi everyone.

I installed Elastic using composer in my Laravel project folder. But i am facing "Class 'Elastica\Client' not found" this error.
I followed the steps as in guide. I need help regarding this.

I will paste my controller code below.

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Elasticsearch\ClientBuilder;
use Elastica\Client as ElasticaClient;

require_once 'C:\xampp\htdocs\logistics\vendor\autoload.php';

class ClientController extends Controller
{
    //
    protected $elasticsearch;
    protected $elastica;

    public function __construct()
    {
      $this->elasticsearch  = ClientBuilder::create()->build();

      $elasticaConfig=[
        'host' => 'localhost','port' => 9200 , 'index' => 'library'
      ];

      $this->elastica = new ElasticaClient($elasticaConfig);
    }

    public function test()
    {
      dump($this->elasticsearch);

      echo "Retriving Document:\n";
      $params = [
        'index' => 'library' , 'type' => 'books' , 'id' => '1'
      ];

      $response = $this->elasticsearch->get($params);
      dump($response);
    }
}
Thanks...

**Comment by ruflin** [comment]
Which version of Elastica are you using? How exactly did you use composer to install Elastica? Normally I assume this is somehow related to your autoloader.

**Comment by thiruvenkatam** [comment]
My version Elastica v.0.20.5. I included  "ruflin/elastica": "dev-master" in my composer.jason file. How do i fix this issue.

**Comment by thiruvenkatam** [comment]
[Composer\Downloader\TransportException]
The "https://packagist.org/p/ruflin/elastica%2408283f02f2b81eb806fd867fa59d
16df55d3a1ab2a14e60199875c2f1529cd9a.json" file could not be downloaded (HT
TP/1.1 404 Not Found)

https://packagist.org/p/ruflin/elastica%2408283f02f2b81eb806fd867fa59d
16df55d3a1ab2a14e60199875c2f1529cd9a.json


The required json file is not found in this wed address

**Comment by ruflin** [comment]
That seems to be a really old version of Elastica. What Elasticsearch version are you using? Can you try if installing a newer version of Elastica works?

**Comment by thiruvenkatam** [comment]
I am using elastic search 6.2...okay will try

**Comment by ruflin** [comment]
If you use 6.2 you definitively have to install the most recent version.

**Comment by thiruvenkatam** [comment]
But installing via composer...will automatically install the latest one
right!?

**Comment by ruflin** [comment]
Can you share the exact composer file you have?

**Comment by thiruvenkatam** [comment]
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "consoletvs/charts": "^5.4",
        "cviebrock/laravel-elasticsearch": "2",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "symfony/process": "^3.4",
        "elasticsearch/elasticsearch": "~6.0",
        "ruflin/elastica": "^0.20.5"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "laravel/homestead": "^7.0",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7"

    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
}

**Comment by ruflin** [comment]
* What version of PHP do you use?
* Why do you stick to dev-master instead of a stable release?

**Comment by thiruvenkatam** [comment]
i have php version 7.0.26.
i used dev-master because i am unaware of the latest stable version.

**Comment by ruflin** [comment]
Can you try to directly install 6.0.1? https://github.com/ruflin/Elastica/releases

**Comment by thiruvenkatam** [comment]
i have downloaded the tar file where to to unzip the contents in my laravel project and what corresponding change do i need to make in my controller

**Comment by ruflin** [comment]
By installing I meant to set the appropriate config in your composer file. What I would recommend you is to remove first all the other dependencies to see if you get the right result and if it works then add the other dependencies.

**Comment by p365labs** [comment]
@thiruvenkatam update your composer with something like :

```
"ruflin/elastica" : "~6.0"
```

and then try to se if the problem is still there

**Comment by thiruvenkatam** [comment]
thanks for the help... but i still have the problem.... 
i changed the composer file and tried updating it.......i get  the below error 

Loading composer repositories with package information
file_put_contents(C:/Users/thiru/AppData/Local/Composer/repo/https---packagist.o
rg/packages.json): failed to open stream: Permission denied
https://packagist.org could not be fully loaded, package information was loaded
from the local cache and may be out of date
Updating dependencies (including require-dev)


  [Composer\Downloader\TransportException]
  The "https://packagist.org/p/ruflin/elastica%2408283f02f2b81eb806fd867fa59d
  16df55d3a1ab2a14e60199875c2f1529cd9a.json" file could not be downloaded (HT
  TP/1.1 404 Not Found)

**Comment by ruflin** [comment]
Can you try a completely empty composer file with only Elastica inside to see if you get it working?

**Comment by bkanber** [comment]
It sounds like you are having problems with Composer on Windows. This doesn't seem like an Elastica problem to me. You should try confirming that the vendor directory contains the correct repositories, perhaps reinstall composer or clear its caches.
