### ISSUE TITLE
Can't resolve host

### ISSUE THREAD

**Issue by IgorDePaula** [ruflin/Elastica#1470]
I readed aome issues and none resolve my problem: Can't resolve host

![selecao_197](https://user-images.githubusercontent.com/2833993/36808723-af66db2c-1ca4-11e8-8f62-6e6fd93eddde.png)

![els](https://user-images.githubusercontent.com/2833993/36808828-fe722e1a-1ca4-11e8-8f83-231e54b0d418.png)

```php
<?php
use Elastica\Client as ElasticaClient;
 $config = [
                'host' =>  env('ELASTICSEARCH_HOST', 'https://xxxxxxxxxxxxxx-txf2c57vaupiv7ij6haeusfgsdi.us-east-1.es.amazonaws.com'),
                'port' => 443,
                'transport' => 'Http'
            ];
            return new ElasticaClient($config, null);
```

**Comment by ruflin** [comment]
Which version of Elastica are you using? Also the AWS version of Elasticsearch uses some special authentication in some cases. There is a special transport for that in Elastica: https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Transport/AwsAuthV4.php But TBH never tested to tried it on my end.

**Comment by andrey1s** [comment]
try config
```php
$config = [
'url' =>  env('ELASTICSEARCH_HOST', 'https://xxxxxxxxxxxxxx-txf2c57vaupiv7ij6haeusfgsdi.us-east-1.es.amazonaws.com:443/'),
'transport' => 'Http'
];
```
or
$config = [
'host' =>  env('ELASTICSEARCH_HOST', 'xxxxxxxxxxxxxx-txf2c57vaupiv7ij6haeusfgsdi.us-east-1.es.amazonaws.com'),
'port' => 443,
'transport' => 'Https'
];
```

**Comment by IgorDePaula** [comment]
@ruflin I used elastica 6.0,latest version, and aws elastic search 2.3 (which has type support yet).

@andrey1s I tried both configs, without success.

**Comment by IgorDePaula** [comment]
@ruflin using AwsAuthV4 transport, I got this error?

"cURL error 6: Could not resolve host: https (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)"

**Comment by IgorDePaula** [comment]
@ruflin 
cURL error 6: CURLE_COULDNT_RESOLVE_HOST (6)

Couldn't resolve host. The given remote host was not resolved.

**Comment by ruflin** [comment]
Elastica 6.0 is not compatible with ES 2.3. 

Having said that I would at least the host resolving to still work. I'm wondering if there is something happening in the middle here? Do you see anything in the ES logs?

**Comment by IgorDePaula** [comment]
No, I see nothing in ES logs. What version you recommend me?

**Comment by ruflin** [comment]
I had to look up the versions: 3.2.3 should be compatible with ES 2.x (for sure 2.4).

**Comment by IgorDePaula** [comment]
Thanks, I will test tomorrow

2018-03-11 17:00 GMT-03:00 Nicolas Ruflin <notifications@github.com>:

**Comment by IgorDePaula** [comment]
I install the elastica version 3.2.3 and receive the same error yet. =/

**Comment by ruflin** [comment]
Let's ping @jeskew on this as he did the initial implementation. Perhaps he knows more?

@IgorDePaula Can you double check for typos?

**Comment by IgorDePaula** [comment]
@ruflin, sorry, I not understand.

2018-03-14 4:56 GMT-03:00 Nicolas Ruflin <notifications@github.com>:

**Comment by ruflin** [comment]
@IgorDePaula One of the last guesses I had is that there are some typos in the host config. Could you also try with and without a `/` at the end of the url?

**Comment by p365labs** [comment]
It looks like Elastica is not able to reach that Host:

```
do you have a security group which restrict access to port 443 ?
```

maybe your terminal access is whitelisted instead the application do the curl from another IP
which is not allowed to access that IP ?

**Comment by IgorDePaula** [comment]
Yes, I"ll try both suggetions. Thanks.

2018-03-16 10:26 GMT-03:00 Federico Panini <notifications@github.com>:

**Comment by IgorDePaula** [comment]
@ruflin I discovery the error, simple.

I invaded your lib, and depurated your code, which host the lib was got, I see https://https://, i.e., duplicated schema http(s). I removed the schema http from my host address config, and now it connect.

Thanks for your patience.
