### ISSUE TITLE
Fix code in 5.x to fulfill guidelines

### ISSUE THREAD

**Issue by cjost1988** [ruflin/Elastica#1483]
Currently there are files in the `5.x` branch which do not fulfill linter requirements:

* \Elastica\Bulk\Action
* \Elastica\Test\BulkTest
* \Elastica\Test\BulkAction\UpdateDocumentTest

Here are the changes that should be changed: [Changes](https://gist.github.com/cjost1988/1a4d871b195bf7cb1da0639334ad8603)

If I've the time I'll create a PR at the weekend, if no one else wants to fix it.

**Comment by ruflin** [comment]
@cjost1988 A PR would be more then welcome 🎉
