### ISSUE TITLE
curl:(6) Could not resolve host:elasticsearch

### ISSUE THREAD

**Issue by yangjingying1993** [ruflin/Elastica#1486]
I am trying to run some elastic commands through curl.

On command prompt, when i type: curl -XGET -H "charset=UTF-8" elasticsearch:9200/test/ddh/_search -d "{ """query""" : { """match""" : { """name""" : """邓第晖"""} } }"

But, the command gives me error: Could not resolve host: elasticsearch

**Comment by ruflin** [comment]
This seems to be a question related to elasticsearch not Elastica. Best use the discuss form for this: https://discuss.elastic.co/
