### ISSUE TITLE
$data['script'] is required

### ISSUE THREAD

**Issue by elshobokshy** [ruflin/Elastica#1487]
Whenever I try to write $qb->filter()->script(...) I get the error mentioned in the title, what am I doing wrong?

**Comment by ruflin** [comment]
Could you share a bit more code and the full error message?

**Comment by elshobokshy** [comment]
Full error message : 
`Fatal error: Uncaught exception 'Elastica\Exception\InvalidException' with message '$data['script'] is required' in /var/www/vendor/ruflin/elastica/lib/Elastica/Script.php:119 Stack trace: #0 /var/www/vendor/ruflin/elastica/lib/Elastica/Script.php(99): Elastica\Script::_createFromArray(Array) #1 /var/www/vendor/ruflin/elastica/lib/Elastica/Filter/Script.php(43): Elastica\Script::create(Array) #2 /var/www/vendor/ruflin/elastica/lib/Elastica/Filter/Script.php(30): Elastica\Filter\Script->setScript(Array) #3 /var/www/vendor/ruflin/elastica/lib/Elastica/QueryBuilder/DSL/Filter.php(435): Elastica\Filter\Script->__construct(Array) #4 [internal function]: Elastica\QueryBuilder\DSL\Filter->script(Array) #5 /var/www/vendor/ruflin/elastica/lib/Elastica/QueryBuilder/Facade.php(62): call_user_func_array(Array, Array) #6 /var/www/htdocs/adm54140/achatsReport.php(57): Elastica\QueryBuilder\Facade->__call('script', Array) #7 /var/www/htdocs/adm54140/achatsReport.php(57): Elastica\QueryBuilder\Facade->script(Array) #8 {main} thrown in /var/www/vendor/ruflin/elastica/lib/Elastica/Script.php on line 119 array(4) { ["code"]=> string(7) "E_ERROR" ["message"]=> string(1020) "Uncaught exception 'Elastica\Exception\InvalidException' with message '$data['script'] is required' in /var/www/vendor/ruflin/elastica/lib/Elastica/Script.php:119 Stack trace: #0 /var/www/vendor/ruflin/elastica/lib/Elastica/Script.php(99): Elastica\Script::_createFromArray(Array) #1 /var/www/vendor/ruflin/elastica/lib/Elastica/Filter/Script.php(43): Elastica\Script::create(Array) #2 /var/www/vendor/ruflin/elastica/lib/Elastica/Filter/Script.php(30): Elastica\Filter\Script->setScript(Array) #3 /var/www/vendor/ruflin/elastica/lib/Elastica/QueryBuilder/DSL/Filter.php(435): Elastica\Filter\Script->__construct(Array) #4 [internal function]: Elastica\QueryBuilder\DSL\Filter->script(Array) #5 /var/www/vendor/ruflin/elastica/lib/Elastica/QueryBuilder/Facade.php(62): call_user_func_array(Array, Array) #6 /var/www/htdocs/adm54140/achatsReport.php(57): Elastica\QueryBuilder\Facade->__call('script', Array) #7 /var/www/htdocs/adm54140/achatsReport.php(57): Elastica\QueryBuilder\Facade->script(Array) #8 {main} thrown" ["file"]=> string(55) "/var/www/vendor/ruflin/elastica/lib/Elastica/Script.php" ["line"]=> int(119) }`

Code is : 
```
$filtre = array();
array_push($filtre, $qb->filter()->range("achats_date_livraison", array("lte" => "$today")));
array_push($filtre, $qb->filter()->term(array('achats_type' => '2')));
array_push($filtre, $qb->filter()->script(array("source" => "doc['achats_id'].value != doc['achats_parent_id'].value")));
$addMustNot = $qb->filter()->bool()->addMustNot($qb->filter()->term(array('inBL' => '0')));
$elastica_query->setQuery(
		$qb->query()->filtered(
			$qb->query()->match_all(),
			$addMust,
			$addMustNot
		)
	)->setLimit(5000000);
```

**Comment by ruflin** [comment]
As this part of the code does not exist anymore in the most recent release, could you share which version of Elastica you are using?

**Comment by elshobokshy** [comment]
I'm using version 2.3 :) It's old I know. but I'm limited to my company's PHP version. Anyways it's okay I found another way to do it. I just wanted to point out a 'maybe bug' in an ancient version. Thanks anyways!

**Comment by ruflin** [comment]
@elshobokshy Glad you found a workaround. Have not really investigated it as it's unlikely that we will have an other release for 2.3. Hopefully you can also upgrade in the near future ;-)
