### ISSUE TITLE
ES is getting rid of mapping types - how do I use elastica without them?

### ISSUE THREAD

**Issue by mandavister** [ruflin/Elastica#1496]
"Mapping types will be completely removed in Elasticsearch 7.0.0"

https://www.elastic.co/guide/en/elasticsearch/reference/6.2/removal-of-types.html

How can I use Elastica today to be compatible with ES 7 ?

**Comment by ruflin** [comment]
The default type will be `_doc`. You should be fine when you use this as your type. Let me know if this does not work.
