### ISSUE TITLE
Cannot set field for RandomScore

### ISSUE THREAD

**Issue by waaghals** [ruflin/Elastica#1498]
From ElasticSearch 7 it is required to add a field parameter when a seed is set. This results in a deprecation warning for now.

Currently it is not possible to set the field parameter with `setRandomScore` on `Elastica\Query\FunctionScore`.

Creating the `random_score` manually seems to work:
```
$seedParam = new \stdClass();
$seedParam->seed = \date('Ymd');
$seedParam->field = '_id';
$randomScore->setParam('random_score', $seedParam);
```

**Comment by ruflin** [comment]
@waaghals Interested to open a PR for this?
