### ISSUE TITLE
Elastica\Aggregation\DateHistogram expects int as interval

### ISSUE THREAD

**Issue by Vorta** [ruflin/Elastica#1504]
From Elastica\Aggregation\Histogram which DateHistogram extends
```php
    /**
     * @param string $name     the name of this aggregation
     * @param string $field    the name of the field on which to perform the aggregation
     * @param int    $interval the interval by which documents will be bucketed
     */
    public function __construct($name, $field, $interval)
    {
        parent::__construct($name);
        $this->setField($field);
        $this->setInterval($interval);
    }
```
@param for $interval should be **string** for DateHistogram, not **int**.

Suggestion:
Change to `@param int|string    $interval`

**Comment by ruflin** [comment]
If I understand this correctly, it's mainly a documentation issue? Do you want to open a PR with the change?

**Comment by ruflin** [comment]
Resolved in https://github.com/ruflin/Elastica/pull/1534
