### ISSUE TITLE
Range Query

### ISSUE THREAD

**Issue by mssimi** [ruflin/Elastica#1512]
Hey, I'm having problem with [Elastica\Query\Range](https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Query/Range.php).

I either don't understand how to use it correctly or it is bugged.

Example code:

```php
$range = new Range();
$range->addField('productCategory.category.left', ['gte', $category->getRoot()->getLeft()]);
```

It generates query like this:

```json
"range": {
  "productCategory.category.left": [
    "gte",
    1
  ]
}
```

But it causes error: "[range] query does not support [productCategory.category.left]"

After checking elastic search [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-range-query.html).

Query should look more like this(and it works):

```json
"range": {
  "productCategory.category.left": {
    "gte" :
    1
  }
}
```
Am I doing something wrong or range filter is bugged?

Using:
elasticsearch : 6.3.0
ruflin/elastica: 6.0.2

**Comment by ruflin** [comment]
Can you try:

```
$range->addField('productCategory.category.left', {'gte': $category->getRoot()->getLeft()});
```

**Comment by mssimi** [comment]
Thx this works.
