### ISSUE TITLE
Elastica\Client - port parameter must be mandatory

### ISSUE THREAD

**Issue by ValMotta** [ruflin/Elastica#1513]
Hi guys,

I'm using Elastica for connect with Monolog to ELK stack on AWS, without PORT parameter the connection remain "on air" without any error or messages.

I think that parameter must have a default value (normaly 80) for continue without problem, or a message that alert you about it.

**Comment by ruflin** [comment]
The default port for Elasticsearch is 9200 and is also what is used as a default if not set.

I assume if you make a request with an invalid port you get an exception?

**Comment by ValMotta** [comment]
Hi Ruflin,

Try create a Client like this with a real endpoint

```
try{
$client = new \Elastica\Client(array(
    'host' => 'foo.bar',
    'timeout' => 10
));
$index = $client->getIndex('my-index');
$type = $index->getType('-test');
$doc = new \Elastica\Document('myId', array('name' => 'valerio'));
$respone = $type->addDocument($doc);
} catch (Exception $ex){
    echo $ex->getMessage();
}
```

The process ignore the timeout and remain on air indefinitely.

**Comment by ruflin** [comment]
What is if you connect to a random address that does not exist. Do you get an exception?

**Comment by p365labs** [comment]
I created a couple of tests #1546  to verify connection problems or timeouts not respected, I was not able to reproduce it. Maybe there's something more than Elastica that create this problem.
