### ISSUE TITLE
[application/x-www-form-urlencoded] is not supported

### ISSUE THREAD

**Issue by CaroleBonfre** [ruflin/Elastica#1516]
When using the raw Json query to add documents in my Elastic index, I always have the same error :  Content-Type header [application/x-www-form-urlencoded] is not supported

Here is my code : 
```
               $index = $this->client->getIndex('myIndex');

		$type = $index->getType('_doc');

		$doc = new Document(1, $jsonData);

		$type->addDocument($doc);
		$index->refresh();
```

Nothing so complicated, with simple jsonData : 

```
{
  "idobjet":"123456","info":"test","title":{}
}
```

And my client : 
```
                $this->clusterConfig = array(
			"servers" => array(
				array("host" => "myHost", "port" => 9200)
			),
			"guzzleOptions" => array(
				"curl.options" => array(
					"CURLOPT_HTTPHEADER" => array("Content-Type: application/json")
				)
			)
		);
		$this->client = new \Elastica\Client($this->clusterConfig);
```

Any idea about what is wrong here ?...

**Comment by CaroleBonfre** [comment]
I use version 2.3.1 of Elastica for project purpose

**Comment by ruflin** [comment]
Which version of Elasticsearch do you use?

**Comment by CaroleBonfre** [comment]
I solved the problem, it seems the error message was not the good one, but now it works fine.

A use ElasticSearch 6.3.0 and a add this while creating my client : 
`"headers" => array("Content-Type" => "application/json")`

I found that there was a problem with my mapping, so I am not sure of what resolved the problem but now everything works :)
