### ISSUE TITLE
Added support to parent_id query in QueryBuilder

### ISSUE THREAD

**Issue by pashaBolshov** [ruflin/Elastica#1518]
Hello

ParentId query was added in May. But it was not added in Query Builder.
Please, could you add parent_id query in Query Builder?

`$qb->query()->parent_id($type, $id, $ignoreUnmapped);`

Thanks,
Pasha

**Comment by ruflin** [comment]
@pashaBolshov Do you want to open a Pull request?

**Comment by pashaBolshov** [comment]
@ruflin No, I don't.  I have never done it. 

Please, could you fix?

Thanks,
Pasha

**Comment by ruflin** [comment]
Don't think I get to it in the next days. Perhaps someone else wants to pick it up?

**Comment by p365labs** [comment]
@pashaBolshov done :)
