### ISSUE TITLE
Release latest changes from 5.x

### ISSUE THREAD

**Issue by thePanz** [ruflin/Elastica#1526]
Could you tag-release the latest changes from the 5.x branch?

**Comment by ruflin** [comment]
Will try to get some releases done next week 🤞

**Comment by thePanz** [comment]
Great! Thanks!

**Comment by ruflin** [comment]
@thePanz Just looked into the diff. If I get this right for 5.3.3 only phpdoc changed, no code changes?

**Comment by thePanz** [comment]
Yes @ruflin , it's only a change in the php docblock :)

**Comment by ruflin** [comment]
Not sure if that is really worth a release? :-)

**Comment by thePanz** [comment]
Well, people working on projects using phpstan will be quite happy about it ;)

**Comment by ruflin** [comment]
@thePanz I pushed a tag 5.3.3: https://github.com/ruflin/Elastica/tree/5.3.3 I didn't use the release thingy on Github for it. Is that enough?

**Comment by thePanz** [comment]
Thanks @ruflin, it should be enough :)
