### ISSUE TITLE
Call to undefined method Elastica\Query::setFilter() 

### ISSUE THREAD

**Issue by imanilchaudhari** [ruflin/Elastica#1538]
Hi, I have upgraded Elastica from unknown to 6.0 and now am facing the issue of undefined method `Query::setFilter()`. I am using php7.2 on ubuntu 18.04. 

```
$elasticaQueryString = new \Elastica\Query\QueryString("*".$keyword."*");
$elasticaQuery = new \Elastica\Query();
$elasticaQuery->setQuery($elasticaQueryString);
$elasticsFilterQuery = new \Elastica\Query\BoolQuery;
$term = new \Elastica\Query\Term;
$term->setTerm('offer_price', 0);
$elasticsFilterQuery->addMustNot($term);
$elasticaQuery->setFilter($elasticsFilterQuery);
```

error
`Call to undefined method Elastica\Query::setFilter() `

**Comment by p365labs** [comment]
yep the setFilter is not in Query anymore.
I suggest you to have a look at tests 

for example:
```Elastica\Test\Query\QueryString```
