### ISSUE TITLE
3.2.* branch to create a pull request

### ISSUE THREAD

**Issue by mgallego** [ruflin/Elastica#1570]
Hi, 

I've a bug with the 3.2.3 release and PHP 7.2. 

I'm working in a solution but I don't find a right branch to make a pull request. Could you create a new branch for 3.2.* releases, please?

Thanks.

**Comment by ruflin** [comment]
@mgallego I just created a 3.x branch which should help here.

**Comment by mgallego** [comment]
Thank you!
