### ISSUE TITLE
Create 6.x branch and leave master for 7.x

### ISSUE THREAD

**Issue by p365labs** [ruflin/Elastica#1580]
The idea behind this issue is tracking the activities in order to get these 2 things done : 

- create a 6.x branch ~~and merge all stuff for 6.x branch~~
- leave on master all new implementations for 7.x 
- merge Pr's on master ~~commit, for 7.x and 6.x, in master and in 6.x branch~~

I think we should have this task to be done : 

- [x] update README.md in order to specify 6.x branch has been created
- [x] create a 6.x branch
- [x] strict_type will be on the same classes amended for type hinting but in master and not in 6.x
- [x] we could start merging PR on master which are specific for 7.x 
- [x] merge all the PR for type hinting ~~on 6.x branch and~~ on master

Here's all the PR's (TypeHinting PR tracker ~~#1548~~ )

- ~~Typehinted Aggregation namespace #1549~~ 
- ~~Typehinted Bulk namespace  review #1550~~ 
- ~~Typehinted Cluster namespace #1551~~
- ~~php7 typehints for Elastica\Type namespace #1557~~ 
- ~~Typehinted Connection namespace #1560~~
- ~~Typehinted exception namespace #1568~~ 
- ~~Typehinted Index namespace #1569~~ 
- ~~Typehinted Multi namespace #1576~~
- ~~Typehinted node namespace #1577~~ 
- ~~Typehinted processor namespace #1579~~
- ~~Typehinted query builder namespace #1583~~ 
- ~~Typehinted query namespace #1582~~
- ~~php7 typehints for Elastica\ResultSet namespace #1565~~
- ~~php7 typehints for Elastica\Rescore namespace #1566~~
- ~~php7 typehints for Elastica\Transport namespace #1558~~
- ~~php7 typehints for Elastica\Script namespace #1564~~
- ~~php7 typehints for Elastica\Suggest namespace #1562~~

~~How about it @ruflin (did I forgot something)?~~
~~@massimilianobraglia & @osavchenko please rebase your branches, I've marked in red the ones I've already checked and need rebase, don't know for the others but check if rebase is needed (at least we need the lint part) #1565 #1566 #1576 #1577 #1579 #1582 #1583~~

**Comment by ruflin** [comment]
I wonder when we should do the branch, now or after all the type hinting cleanups?

**Comment by p365labs** [comment]
yep ur right.
I've created the branch but it's better doing it after merging type_hinting PRs.
I'll remove it.

**Comment by p365labs** [comment]
@ruflin as per this discussion I updated this issue in order to keep track of what is needed for merging "TypeHinting" Pr's. 

Shell I start with this plan ?

**Comment by ruflin** [comment]
@p365labs Sounds good to me. Doing all the type hinting PR's into master instead of 6.x has also the advantage of being on the safe side. We can always backport if it becomes an issue.

**Comment by p365labs** [comment]
@ruflin what about merging #1599 before branching 6.x ?

**Comment by ruflin** [comment]
Done

**Comment by p365labs** [comment]
@ruflin & @massimilianobraglia let's rock & roll :)
- branch 6.x has been created
- I'm going to merge PR's for typehinting

**Comment by p365labs** [comment]
@massimilianobraglia 

1. are there specific PR's I have to start with or not? 
2. there are still PR's which are not passing tests can u check it?
- #1549 
- #1551

**Comment by massimilianobraglia** [comment]
1. no, I kept those very closed to their scope in order to have the merge process simple. Obviously I'm available to fix what breaks if something goes wrong :)
2. I'll check them ASAP!

**Comment by massimilianobraglia** [comment]
@p365labs I have checked the PRs. I have rebased again the aggregation PR to see if something changes. Otherwise I'll have to go deeper to see what's wrong. My other PRs should be ok now!

**Comment by p365labs** [comment]
@ruflin & @massimilianobraglia @osavchenko Hi, more than half of the PR's has been merged : 

- some just need to be rebased (I can do it if u don't mind)
- one (#1562 ) need to review my comments
- other two (#1564 #1582 ) have conflics

can u please give them a look ?

**Comment by osavchenko** [comment]
@p365labs will fix conflicts and comments. I don't mind if you rebase other. Thank you!

**Comment by massimilianobraglia** [comment]
@p365labs my last PR should be ok now!

**Comment by p365labs** [comment]
@massimilianobraglia & @osavchenko Thank you very much for the impressive work!

**Comment by ruflin** [comment]
Thanks everyone involved here to make this happen.
