### ISSUE TITLE
New release 3.2.4

### ISSUE THREAD

**Issue by mgallego** [ruflin/Elastica#1601]
Could you create a new release 3.2.4 from 3.x branch? Is for to be able to use the latest changes through composer/packagist.

This new release will be compatible with PHP 7.2 #1571 

Thank you.

**Comment by thePanz** [comment]
I am also worried about that line, most of all: if the `_params['post_flter']` is not an object, the call to `->toArray()` will break.
Are we running the same code on 5.x?

**Comment by ruflin** [comment]
I'm not sure if we made this change in 2.x or 5.x. Someone has time to check? :-)

**Comment by EliuFlorez** [comment]
Help please! https://github.com/ruflin/Elastica/issues/1597

I'm new to elastic search and I do not know how to migrate this part to version 5.x

**Comment by ruflin** [comment]
@EliuFlorez Please do not post on unrelated issues.

**Comment by mediaparttech** [comment]
I agree with @mgallego request, it will be great !

**Comment by ruflin** [comment]
I found the code in the 2.3.3 tag: https://github.com/ruflin/Elastica/blob/2.3.3/lib/Elastica/Query.php#L404 I think we should be fine with a release then. @thePanz WDYT?

**Comment by thePanz** [comment]
@ruflin fine for me!

**Comment by ruflin** [comment]
@thePanz Interested to do this release? 😇

**Comment by ruflin** [comment]
I just tagged the release: https://github.com/ruflin/Elastica/releases/tag/3.2.4

@mgallego Could you confirm that it is what you expected? Going to close this issue.

**Comment by thePanz** [comment]
Sorry @ruflin , I just read your message :) Thanks for taking care of it!

**Comment by Dave13h** [comment]
Hi @ruflin, 

Sorry for bringing this thread back up... 

Thanks for doing the 3.2.4 release, we are still in the process of migrating to a newer version but we need PHP7.2 support in the mean time. 

We can't seem to pull this new version in through composer, it doesn't seem to be listed on https://packagist.org/packages/ruflin/elastica

Is it possible to make that available through composer too? 

Cheers
Dave

**Comment by thePanz** [comment]
@ruflin is the composer integration disabled for this version?

**Comment by ruflin** [comment]
@thePanz TBH don't even know how I could enable / disable this. Any hints?

**Comment by thePanz** [comment]
@ruflin what do you see when you go to https://packagist.org/packages/ruflin/elastica ? any warnings?
You add me to the "release maintainers", so I can help with that if you want :)

**Comment by ruflin** [comment]
I did click "Update" and it seems it shows up there now.

@thePanz Where can I add you as release maintainer? Didn't find this option on Packagist.

**Comment by thePanz** [comment]
@ruflin there should be a "+" icon next to your avatar in project page (right sidebar) under the "maintainers" label :)

**Comment by ruflin** [comment]
@thePanz There it is, I was searching in the settings :-) I added `thePanz` but it has an other favicon. Hope that is you.

**Comment by thePanz** [comment]
@ruflin yep, it's me :D
