### ISSUE TITLE
Error: Class 'Psr\Log\NullLogger' not found

### ISSUE THREAD

**Issue by camohub** [ruflin/Elastica#1604]
Hi there, I have a project without Composer. So I downloaded a new version of Elastica and according [documentation](https://elastica.io/getting-started/installation.html#section-include) I made a loader file which looks like 
```
<?php

spl_autoload_register(function($class) {
	$path = str_replace('\\', '/', substr($class, 0));

	if (file_exists( __DIR__ . '/' . $path . '.php' ))
	{
		require_once( __DIR__ . '/' . $path . '.php' );
	}
});
```
It seems it works. But when application try to run Elastica/Client __construct() it throws me an error: **Class 'Psr\Log\NullLogger' not found in C:\wamp64\www\indexApi\libs\Elastica\lib\Elastica\Client.php:94** As I see there is no NullLogger class at all. In Elastica/Client __construct is the line 
```
        $this->_logger = $logger ?: new NullLogger();
```
When I check it the $logger is NULL so new NullLogger() is called ever time and it throws me this error. I am on PHP 7.1.16. Do you know what should I do to fix it? 
Thanks.

**Comment by p365labs** [comment]
Hi actually I discourage the use of Elastica and in general this kind of libraries without composer, anyway, if you want to try it without the use of composer first you should consider libraries **required** by composer 

```JSON
"php": "^7.0",
"psr/log": "~1.0",
"elasticsearch/elasticsearch": "^6.0"```

which should be installed and autoloaded too.

**Comment by camohub** [comment]
Ah yes I understand. I will try it. Thanks.

**Comment by p365labs** [comment]
@camohub did u solved?

**Comment by camohub** [comment]
Yes it works. But its really messy....

**Comment by p365labs** [comment]
if there's something we can help about ur implementation feel free to ask otherwise I think we could close this issue. what do u think @camohub ?

**Comment by camohub** [comment]
Yes of course. Thank you.
