### ISSUE TITLE
Discussion on Migration 2.x to 5.x

### ISSUE THREAD

**Issue by EliuFlorez** [ruflin/Elastica#1609]
#Inglesh
What differences or improvements can I get to migrate ElasticSearch 2.x to 5.x. Since I need to optimize my queries with more than 1 million records. It will be that my documents or query is wrong or due to the ElasticSearch version.

#Spainsh
Que diferencias o mejoras puedo obtener a migra ElasticSearch 2.x a 5.x. Ya que requiero optimizar mis consultas con mas de 1 millon de registros. Sera que mis documentos o query esta mal o se debe a la version de ElasticSearch.

Venezuelan from Mexico.

**Comment by ruflin** [comment]
I assume this is related to https://github.com/ruflin/Elastica/issues/1597 If it is about optimisations in Elasticsearch you better ask in https://discuss.elastic.co/c/elasticsearch

**Comment by thePanz** [comment]
Should we close this issue @EliuFlorez  @ruflin ?
