### ISSUE TITLE
Composite aggregationEdit will be added?

### ISSUE THREAD

**Issue by EliuFlorez** [ruflin/Elastica#1612]
A multi-bucket aggregation that creates composite buckets from different sources.

Unlike the other multi-bucket aggregation the composite aggregation can be used to paginate all buckets from a multi-level aggregation efficiently.

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-composite-aggregation.html

**Comment by ruflin** [comment]
@EliuFlorez Would be great to have it. Interested to open a PR? :-)

**Comment by EliuFlorez** [comment]
@ruflin 
Clear to present a PR. But I am still very new in ElasticSearch and I would like to clarify the differences between version 2.x to 6.x of elasticSearch.

Since in the project that I am working the 'indix' was the database of each domain. and the type were the tables with all their properties. but now in version 6 multiple type are not allowed in the same index.

Do I have to create every index for my database table? or how else can I do it?

If you are very kind to help a little. since in the forums they have not helped me.

**Comment by ruflin** [comment]
As usual, the answer is it depends :-)

In most cases when you were using multiple types before, you should switch to multiple indices. The assumption here is that each table you have the data format is pretty different. If the data structure is 95% identical across your tables, it could be worth just using one index and have a field for filtering.

Does this help?

**Comment by EliuFlorez** [comment]
@ruflin Thanks that helps my doubt to establish multiple index for each tables or in the case that the data are almost the same an indelificative type of index. Thank you! I keep working on the changes. : D

**Comment by Ciloe** [comment]
@itkg-ppottie and @ruflin when this PR #1804 Will be merged ?
