### ISSUE TITLE
Query\Ids support values of type: START_OBJECT

### ISSUE THREAD

**Issue by EliuFlorez** [ruflin/Elastica#1613]
Query\Ids support values of type: START_OBJECT

The errors appear when trying to scroll the Query Scroll.

If the Scroll object is required, it will confirm.

![error-scroll](https://user-images.githubusercontent.com/784787/53768742-8e963e80-3e8e-11e9-9203-b5003eecf363.png)

**Comment by ruflin** [comment]
What version of Elastica and Elasticsearch is this? Do you have by chance the JSON that is sent to Elasticsearch?

**Comment by EliuFlorez** [comment]
It's my mistake. Hahaha
