### ISSUE TITLE
Missing parent aggregation

### ISSUE THREAD

**Issue by SosthenG** [ruflin/Elastica#1614]
Version 6.6 introduced the [ParentAggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-parent-aggregation.html) which is missing in Elastica.

I worked on it on my own fork because I needed it.

Before I can open a PR I have one question: is there a good way to handle the class name? "Parent" is a reserved word so I named the class "ParentAggregation" and overrided the _getBaseName method to return "parent" which seems to allow the params conversion to work.
But I'm not sure it was the good way to do it...

Actually it seems that for the GlobalAggregation the solution was to add a special case to the toArray method of the AbstractAggregation, I'm not sure which one is the best.

**Comment by ruflin** [comment]
It's always a tricky one with the reserved names. Could you open your PR with what you have right now so we can discuss it directly in the code. At least for me, that would make it easier.

**Comment by SosthenG** [comment]
Ok, done https://github.com/ruflin/Elastica/pull/1616
