### ISSUE TITLE
Is there a roadmap to be compliant with ES7?

### ISSUE THREAD

**Issue by giovannialbero1992** [ruflin/Elastica#1626]
Hi @ruflin, do you have a roadmap to share with community to develop new feature or remove deprecated feature in ES6 ?

**Comment by mmoreram** [comment]
@ruflin and if you have, can you share it so some of you can help?

**Comment by p365labs** [comment]
@giovannialbero1992 & @mmoreram there's a branch on which i'm working on.
which has been developed to be merged on master. as 6.x as its own branch,
master will be for the 7.x release.
I'm working on it and in a couple of day will be possible to merge it.

**Comment by ruflin** [comment]
Good time for this discussion as 7.0.0-rc2 is already out: https://www.elastic.co/blog/elastic-stack-7-0-0-rc2-released 

@p365labs Let's use this thread to also ask help from others on the migration part. I think after we get the branch in, we will still need to do some cleanup / adjustements?

**Comment by mmoreram** [comment]
@ruflin Count on @apisearch_io tests cases to test a lot of features. As soon as I can, I will create the adapter for ES7 and will test. Will send you all some feedback as soon as I have it.

**Comment by ruflin** [comment]
@mmoreram Great to hear. Now that 7.0 is out we should probably push this a bit more.

**Comment by mmoreram** [comment]
@ruflin yes. As soon as my two childs (Apisearch and my son XD) give me some time, I will try to help you a little bit!

Nice work!

**Comment by p365labs** [comment]
@ruflin @giovannialbero1992 and @mmoreram 
[PR for ES7](https://github.com/ruflin/Elastica/pull/1563) is ready: tests and BC breaks has been updated. Now the build is green (BEWARE that this is a WIP).
I've tried to understand if it could be possible to make tests pass without updating elasticsearch-php
but it's not possible. 

In order to maintain our tests and update codes we need ```include_type_name``` as a parameter, but as elasticsearch-php whitelist querystring parameters this is not possible until that lib will be updated.
Even removing types from our code won't change the problem as in elasticsearch-php there are a lor of endpoint with this king of checks :

```PHP
       if (isset($this->type) !== true) {
            throw new Exceptions\RuntimeException(
                'type is required for Put'
            );
        }
        $index = $this->index;
        $type = $this->type;
        $uri   = "/_mapping/$type";

        if (isset($index) === true && isset($type) === true) {
            $uri = "/$index/$type/_mapping";
        } elseif (isset($type) === true) {
            $uri = "/_mapping/$type";
        }

        return $uri;
```

Until we will have this kind of checks would be really complex to us to have Elastica ready for ES7.x
The question is ... how could be the tests GREEN if we have this kind of problems on elasticsearch-php, and if we have to wait for that lib to get updated?
Well I've updated the source code at least to whitelist ```include_type_name``` and updated current composer.json to use my fork... 

Actually this PR is a WIP and **could be not merged**
I've seen that today @ezimuel is working hard and has released a 6.5version, I think he will probably update sooner to 7.x but dunno when :=) Tbis will allow us to test against it.

Any Ideas on this?

**Comment by ruflin** [comment]
@p365labs Thanks for all the work on this. 

I would definitively prefer not to depend on a fork of elasticsearch-php. @p365labs Can you perhaps open a PR with your fix against elasticsearch-php? Let's also bring @ezimuel into the conversation here to see what his take is on how we should move forward.

**Comment by ezimuel** [comment]
Hi @ruflin and all, I'm working to fix the integration tests for ES 6.x versions on `elasticsearch-php`. I released `6.5.0` with some fixes and still working to solve ES 6.6 and ES 6.7. When done (hopefully this week) I'll focus on 7.0.0 release. I expect to release it next week.

As a new maintainer, I spent some time to understand the code base and I'm planning to do some refactor soon. I'm trying to do my best to fill the gap with the versions.

**Comment by p365labs** [comment]
```I would definitively prefer not to depend on a fork of elasticsearch-php.```
@ruflin totally agree :) That was the only way to test the new elastica code; 

Of course that is a wip but it would probably allow us to make a quick release after @ezimuel will release the new elasticsearch-php. I've already opened a PR against ES-php https://github.com/elastic/elasticsearch-php/pull/868 which has been converted to a WIP... as the code is changing pretty fast even if the PR is really simple it would be probably updated. 

Obviously the suggestion is to wait for ES-php 7.0.0 release and then we can change re-test the [PR](https://github.com/ruflin/Elastica/pull/1563) and then merge it if tests will be green.

**Comment by mmoreram** [comment]
@p365labs testing.
I will publish all things I see.

**Comment by ruflin** [comment]
@p365labs This is great.

@ezimuel Can you ping here as soon as master is working with 7.0? We don't need a 7.0 release for starting to merge PR into Elastica master.

**Comment by p365labs** [comment]
@ruflin good news, I've updated my branch composer.json and now it's pointing again to elasticsearch-php official repo. Have a look at the [PR#1563](https://github.com/ruflin/Elastica/pull/1563).

Today a new commit on that repo has been merged and is for [version 6.7](https://github.com/elastic/elasticsearch-php/releases/tag/v6.7.0). 
(Thank u @ezimuel !)
In this version there is what actually we need a new param ```include_type_name```. So tests are green right now.

Before merging I'll wait for the release of Elasticsearch-php 7.0.

@ruflin what do u guess?

ping @giovannialbero1992 @mmoreram

**Comment by ezimuel** [comment]
@ruflin, @p365labs and all, I just released [elastic/elasticsearch-php v.6.7.0](https://github.com/elastic/elasticsearch-php/releases/tag/v6.7.0). Let me know if this works for you.

I'm working on 7.0.0 right now, let me know if you have something to suggest or look into, thanks again for your support!

**Comment by ruflin** [comment]
@p365labs I see you currently depend on dev-master which is I think a good thing. So far I didn't as Elastica had a very simple branching model to keep simple. Moving forward I wander if we should change that. Meaning that we have a 7.x branch from day one and do backports. At the same time this creates more work and not sure if it is needed.

I'm good with moving forward with the PR and switch back to 7.0 branch when it's out.

@ezimuel What is your plan for php-elasticsearch. Will there be a release for each stack minor? So if 7.1 comes out but no changes are needed (let's see about that), will you ship a 7.1?

**Comment by p365labs** [comment]
@giovannialbero1992 @mmoreram as elasticsearch-php release for ES7 is still pending we decided to merge #1563 which uses elasticsearch-php ```dev-master```. When it will be released we will update composer.json. For now elastica dev-master is working with ES7.

**Comment by ezimuel** [comment]
@ruflin, @p365labs, @giovannialbero1992, @mmoreram I just released [elasticsearch-php 7.0.0](https://github.com/elastic/elasticsearch-php/releases/tag/v7.0.0).

**Comment by ruflin** [comment]
Great news @ezimuel This should get us closer to be able to release Elastica 7.0 too.

**Comment by p365labs** [comment]
@ruflin a PR is ready in order to test the new release :) PR #1639
