### ISSUE TITLE
Allow to pass DSN to the Elastica\Client constructor

### ISSUE THREAD

**Issue by renanbr** [ruflin/Elastica#1640]
Currently I have to handle config options as separated keys in each environment my application is deployed (local, ci, staging, prod...). Things become hard when an environment required an option the other don't...

It could be cool if  `Elastica\Client`'s constructor becomes able to parse a single string.

```php
new Elastica\Client('192.168.1.1:9200');
```

```php
new Elastica\Client('https://user:p4ss@foo.com:9200/elastic;persistent=false;retryOnConflict=2');
```

**Comment by tacman** [comment]
Yes, this would be particular helpful on deployments like Heroku, which creates the DSN environment variable when the service is created, but configuring it requires manually breaking it apart into the individual components.

**Comment by ruflin** [comment]
Do you see a way how we could introduce this without making it a breaking change? In general, +1 on having such a feature.

**Comment by alamirault** [comment]
PR is now merge, I think @ruflin you can close issue.
