### ISSUE TITLE
SetFields() method does not exist V6.1

### ISSUE THREAD

**Issue by Segolene-Albouy** [ruflin/Elastica#1641]
According to the [documentation](https://elastica.io/getting-started/search-documents.html) the method `SetFields` should exist for query object but it doesn't seem to be the case. Is there newer documentation?

```PHP
$query = new Elastica\Query();

$query
    ->setFrom(50)
    ->setSize(10)
    ->setSort(['name' => 'asc'])
    ->setSource(['obj1.*', 'obj2.'])
    ->setFields(['name', 'created'])
```

**Comment by ruflin** [comment]
The more up-to-date documentation should be our API docs: https://elastica.io/api/latest/namespaces/Elastica.html Could you share the Elasticsearch query you are trying to build?

**Comment by Sharptsa** [comment]
The `fields` parameter was on older versions of Elasticsearch (<=2.4.0) and Elastica (<=3.x).

On recent versions, the parameter has been renamed `stored_fields` and is set by using the method `setStoredFields` in Elastica.

Elasticsearch documentation 2.4 : https://www.elastic.co/guide/en/elasticsearch/reference/2.4/search-request-fields.html
Elasticsearch documentation 6.8 : https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-request-stored-fields.html

**Comment by ruflin** [comment]
@Segolene-Albouy Does this solve your problem? If yes, lets close the issue.
