### ISSUE TITLE
Reuse of guzzle client in Elastica 6.x

### ISSUE THREAD

**Issue by killerwolf** [ruflin/Elastica#1644]
Hello everyone,

When issuing a Search and and Msearch in the same script execution, the Guzzle client is reused for better performance. The problème is that the Content-Type of the second request is ignored, because the Content-Type is stored within the Guzzle Client

Here is the problème
https://github.com/ruflin/Elastica/blob/6.x/lib/Elastica/Transport/Guzzle.php#L159-L171

We should maybe backport the fix from the master branch
https://github.com/ruflin/Elastica/pull/1618/files

**Comment by ruflin** [comment]
@killerwolf Interested to open a backport PR with the change?

**Comment by reedy** [comment]
Backport was trivial to do, done in linked PR above

**Comment by ruflin** [comment]
Closing as https://github.com/ruflin/Elastica/pull/1671 was merged.
