### ISSUE TITLE
How to manage Elasticsearch 7.x?

### ISSUE THREAD

**Issue by eostis** [ruflin/Elastica#1649]
I tried to follow some threads on Elasticsearch 7.x, and noticed a recent commit for 7.1

But is there any documentation/hint/examples on that subject anywhere?

**Comment by eostis** [comment]
I installed the latest commit, and managed to create a 7.3 index.

But 6.5 indexes can no more be created, as the code automatically sends the parameter 'include_type_name' (not whitelisted):

/vendor/ruflin/elastica/lib/Elastica/Index.php:
   public function requestEndpoint(AbstractEndpoint $endpoint)
    {
        $cloned = clone $endpoint;

        $cloned->setIndex($this->getName());
        if ($endpoint instanceof Create || $endpoint instanceof \Elasticsearch\Endpoints\Indices\Mapping\Put) {
            $cloned->setParams(['include_type_name' => true]);
        }

        return $this->getClient()->requestEndpoint($cloned);
    }

**Comment by p365labs** [comment]
If u use the 7.x branch or the master one, the ES supported version is 7. If u want to use or work with a older version have a look at our [version matrix](https://github.com/ruflin/Elastica#versions--dependencies)

**Comment by eostis** [comment]
I did use the master branch indeed (I could not find a 7.x branch).

Does that mean Elastica will not be retro-compatible with versions prior to 7.x?

**Comment by ruflin** [comment]
We didn't create a 7.x branch yet but master is the one compatible with 7. Do be compatible with older versions, you need to download the 6.x releases.

**Comment by eostis** [comment]
Thanks.

**Comment by hotrush** [comment]
@ruflin do we need `include_type_name` for 7.x?

From docs:
> Elasticsearch 7.x
> - The include_type_name parameter in the index creation, index template, and mapping APIs will default to false. Setting the parameter at all will result in a deprecation warning.

**Comment by ruflin** [comment]
I think we do for users which still have some 6.x indices around.

**Comment by hotrush** [comment]
Then it must be optional i think, otherwise all other users will receive annoying warnings.

**Comment by ruflin** [comment]
Will https://github.com/ruflin/Elastica/pull/1654 solve this?

**Comment by hotrush** [comment]
I think yes, why not.
In my opinion type's stuff should be deprecated at all just because there are no more types in elasticsearch since v7. And all that related to types should be optional or deprected.

**Comment by hotrush** [comment]
Btw, i still don't understand how to create typeless index using your v7 library :)

**Comment by ruflin** [comment]
Agree on the optional and deprecated part. But the param is still around in 7.x: https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html#_schedule_for_removal_of_mapping_types

**Comment by hotrush** [comment]
Yes, it's still there, but it forces true value when true generates a deprecation warning. It should be ok if it will be optional, but don't think that is ok in current way.

**Comment by ruflin** [comment]
Agree. Are there more places which need changes like #1654  ?

**Comment by hotrush** [comment]
Unfortunately i didn't dive deep because i need to refactor tons of code from elasticsearch 1.3 to ~~7.x~~ 6.x and have no time.

Second thing that confused me that you still have Type class and functioanllity, it also must be deprecated and Index class should receive all it's functions like mapping, settings, adding documents, etc. Yes, you still can have some kind of types using type field or smth, but that's anyway should be resolved with filters on query level and not with Type class or smth.

**Comment by dpauli** [comment]
@ruflin Is there any plan to release a 7.0.0 working release. Its uncomfortable to use the master-*version* to checkout.

**Comment by ruflin** [comment]
@dpauli Yes, definitively. I hope I get to it rather sooner then later.
