### ISSUE TITLE
Support for search option track_total_hits

### ISSUE THREAD

**Issue by skylord123** [ruflin/Elastica#1663]
This should be super easy to add support for. I was able to patch it locally by just changing a couple lines. 

Here is the page on elasticsearch for this:
https://www.elastic.co/guide/en/elasticsearch/reference/7.0/search-request-track-total-hits.html

Thanks!

**Comment by ruflin** [comment]
Closing as https://github.com/ruflin/Elastica/pull/1664 was merged.
