### ISSUE TITLE
Optimize the CI and docker settings

### ISSUE THREAD

**Issue by thePanz** [ruflin/Elastica#1681]
Few ideas to improve the CI pipeline:
 * Looks like our CI is building docker images and not reusing any already available image.
 * we compile the PHP x-debug extension, while it is not used during the tests
 * running the php-cs-fixer could be done in travis-ci, no docker images are needed for that

**Comment by ruflin** [comment]
Always on board with optimisations. 

One thought I would like to share here on why things are potentially running the way they are running. In general I prefer to have just 1 setup on how to run tests. Running it locally or on CI should work the same. Things could be optimized on Travis, but it would mean we run it differently locally and on CI (if I don't have php-cs-fixer installed). Docker gurantees here we always have (almost) the same setup. Having said all that, always open for change :-)
