### ISSUE TITLE
Elastica\Client\updateDocument fails with ES 7.3

### ISSUE THREAD

**Issue by lenada** [ruflin/Elastica#1683]
When testing current master against Elasticsearch 7.3 
`->updateDocument()` throws

`Elasticsearch\Common\Exceptions\UnexpectedValueException`

 "version" is not a valid parameter. Allowed parameters are "_source", "_source_excludes", "_source_includes", "error_trace", "filter_path", "human", "if_primary_term", "if_seq_no", "lang", "opaqueId", "parent", "pretty", "refresh", "retry_on_conflict", "routing", "source", "timeout", "wait_for_active_shards"

After removing the `version` parameter it seems to update the document just fine.

Apart from that issue; are there plans to tag a ES 7.3 compatible release anytime soon?

**Comment by ruflin** [comment]
@lenada Thanks for filing. There are definitively plans for a 7.x release but we are currently blocked a bit on https://github.com/ruflin/Elastica/pull/1666

Did you dig into more details by chance on what changed in 7.3 Elasticsearch that causes the above (like a changelog)?

**Comment by lenada** [comment]
It seems the version parameter was deprecated in ES 7.0.0 
[Remove support for internal versioning for concurrency control](
https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-7.0.0.html)
(See CRUD paragraph)

related issue: https://github.com/elastic/elasticsearch/pull/38254

**Comment by philkra** [comment]
I tested `->updateDocument()` with the branch `es-7-remove-type` from PR #1666 and reproduced the error.

**Comment by lenada** [comment]
@ruflin @thePanz I recently tested `Release 7.0.0-beta.3` unfortunately ist seems the version parameter is still present there and errors with ES >= 7.0

**Comment by ruflin** [comment]
@lenada Did you figure out by chance where in the code this is coming from?

**Comment by thePanz** [comment]
@lenada @philkra can you provide an example code where the exception is being thrown?

**Comment by lenada** [comment]
@ruflin @thePanz thank you for your time! When I comment https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Client.php#L365 no exception is thrown.
I wonder why this error does not occur on any travis builds?

**Comment by ruflin** [comment]
Makes me wonder if we have a test case for updateDocument :-)

**Comment by armandojs** [comment]
I can confirm this on my end as well. I'm using `"ruflin/elastica": "7.0.0-beta.3"` 

Retrieving a document brings the 'version' parameter with it and saving the document back by running updateDocument produces the error.  

I can work around this by removing the 'version' parameter from the params array though not sure if it's a good idea.  My Elasticsearch/Elastica knowledge is very superficial.

**Comment by consolari** [comment]
Reproduced this on elaticsearch 7.9.1 and elatica dev-master. Everything else seems to work fine. Any chance it can be prioritized up?

When uncommented 'version' in params in Client.php->updateDocument() it works.

**Comment by ruflin** [comment]
@consolari Any chance you could open a PR with this change against master? This should simplify the dicsussion and we will also see what tests this effects.

**Comment by deguif** [comment]
Closed as it was fixed in #1803
