### ISSUE TITLE
Bump QueryBuilder version

### ISSUE THREAD

**Issue by deguif** [ruflin/Elastica#1691]
I see that the latest query builder version is `Version240` and the type filter was removed in it.
Shouldn't we instead bump it to a `Version700` or something like that?

**Comment by ruflin** [comment]
@deguif That should work I think. Want to take care of it?

**Comment by deguif** [comment]
@ruflin it's done with many other things ;)
Do you think you will have time to review/merge soon?

**Comment by ruflin** [comment]
@deguif Thank you for all your contributions. Will try to go through all of them (some I already did).
