### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by netwons** [ruflin/Elastica#1698]
What is this Error?
`Error in one or more bulk request actions: index: / detail_model / _doc / 1 caused index [detail_model] blocked by: [FORBIDDEN / 12 / index read-only / allow delete (api)]; index: / detail_model / _doc / 2 caused index [detail_model] blocked by: [FORBIDDEN / 12 / index read-only / allow delete (api)]; index: / detail_model / _doc / 3 caused index [detail_model] blocked by: [FORBIDDEN / 12 / index read-only / allow delete (api)];`

**Comment by philkra** [comment]
what version of elasticsearch are you using?

**Comment by netwons** [comment]
`name: "netwons-Lenovo-G50-70",
cluster_name: "elasticsearch",
cluster_uuid: "4SUqg3Z7QteNcHgH6_2ROQ",
version: {
number: "7.3.0",
build_flavor: "default",
build_type: "deb",
build_hash: "de777fa",
build_date: "2019-07-24T18:30:11.767338Z",
build_snapshot: false,
lucene_version: "8.1.0",
minimum_wire_compatibility_version: "6.8.0",
minimum_index_compatibility_version: "6.0.0-beta1"
},
tagline: "You Know, for Search"
}`

**Comment by philkra** [comment]
Please refer to this [forum post](https://discuss.elastic.co/t/forbidden-12-index-read-only-allow-delete-api/110282/5) to solve your problem. As it's not related to the Elastica lib.

**Comment by netwons** [comment]
I just got acquainted with the tire in Larval, what should I do to fix it

**Comment by philkra** [comment]
read the post in the forum for a solution --> https://discuss.elastic.co/t/forbidden-12-index-read-only-allow-delete-api/110282

**Comment by netwons** [comment]
How to write code it in laravel?

**Comment by netwons** [comment]
> read the post in the forum for a solution --> https://discuss.elastic.co/t/forbidden-12-index-read-only-allow-delete-api/110282

How to write code it in laravel?

**Comment by philkra** [comment]
forum post explains how to write the curl command

**Comment by netwons** [comment]
Now this eruption is gone
`The Response content must be a string or object implementing __toString(), "object" given.`
