### ISSUE TITLE
document

### ISSUE THREAD

**Issue by netwons** [ruflin/Elastica#1699]
The document is too dumb and weak.
Can you give an example?
help me

**Comment by ruflin** [comment]
You can find a lot of example for all the objects and methods in the tests: https://github.com/ruflin/Elastica/tree/master/test/Elastica Also there is the full API documentation: https://elastica.io/api/latest/

Agree that we could need more documentation. Would be great if you could contribute to it. The repository for it can be found here: https://github.com/ruflin/Elastica.io

To get better help, I think you need to be more specific on what you are looking for, what you tried and didn't work.

**Comment by ruflin** [comment]
Closing this issue as it is too generic, hope I gave some guidance with the above.
