### ISSUE TITLE
Bump PHP minimum version to 7.2

### ISSUE THREAD

**Issue by deguif** [ruflin/Elastica#1701]
As PHP 7.1 is going EOL very soon, should we bump its constraint in composer file to 7.2 for the upcoming version 7.0 of the library and adjust Travis configuration?

**Comment by ruflin** [comment]
@deguif SGTM. But I would still keep the 7.0 / 7.1 tests around so we know when we actually really going to break things.

**Comment by philkra** [comment]
I would suggest to rather make a strong cut to min `7.2` as php version or to stick around with `7.0`, as the new language constructs introduced in `7.1` and `7.2` are not compatible with `7.0`. Running tests with a `7.2` code will break in case in `7.0` and likely in `7.1`.

**Comment by ruflin** [comment]
See my comment in https://github.com/ruflin/Elastica/pull/1703
