### ISSUE TITLE
Tests broken since release of elastic/elasticsearch-php 7.4.0

### ISSUE THREAD

**Issue by deguif** [ruflin/Elastica#1710]
I investigated the issue and it seems some classes are now auto-generated, and their name was changed.

For example, `Elasticsearch\Endpoints\Ingest\Pipeline\Delete` was renamed to `Elasticsearch\Endpoints\Ingest\DeletePipeline`

**Comment by deguif** [comment]
@ruflin @thePanz a quick solution would be to update composer.json to avoid installing this version.

But I'm not sure what will be the best way to support 7.4 version and all 7.x versions.
Maybe we should create an issue on their repository.

**Comment by deguif** [comment]
https://github.com/ruflin/Elastica/pull/1711 should fix the tests, by marking the `elasticsearch` package as conflicting since version `7.4.0` in the `composer.json` file.

**Comment by thePanz** [comment]
A better solution would be to set the version range to something like `^7.0 || < 7.4.0`
So that we could work on the issue with more time. wdyt?

**Comment by deguif** [comment]
@thePanz I'm not sure the `||` will do what is expected here.
As `7.4.0` should match `^7.0`, but we should probably use `^7.0 < 7.4.0` as it would be an `and` in this case.
I was thinking the `conflict` was more appropriate, but it's up to you ;)

**Comment by deguif** [comment]
I confirm `^7.0 || <7.4.0` is not working while `^7.0 <7.4.0` is working as expected.

**Comment by deguif** [comment]
I also created an issue on the official `elastichsearch-php` repository, let's see what will come out.

**Comment by ezimuel** [comment]
I just commented about this issue [here](https://github.com/elastic/elasticsearch-php/issues/967).

**Comment by ruflin** [comment]
For having consitent testing, +1 on fixing the dependency version (already done). I would hope somewhere in the future, releases of the two libraries are even in more sync.

At the same time I'm kind of glad we found this now os testing with "latest" is not only bad. I suggest we make the change on our end before we ship 7.0 GA. As far as I understand it mainly changes some internal implementation but nothing external?

**Comment by ezimuel** [comment]
@ruflin exactly, I'm doing my best to avoid BC breaks but sometime it's quite hard to keep all previous inconsistency in place. I'm working on `elasticsearch-php 7.4.1` to reintroduce (some) old namespaces as class aliases.
Now that we have a code generation from the REST API specification we'll be more aligned with Elasticsearch version.

**Comment by ruflin** [comment]
@ezimuel Don't worry, fully understand that sometimes breaking changes in minors are needed ;-) Do you think we should directly rely on 7.4.1 and it will make things less breaking on our end?

**Comment by ezimuel** [comment]
@ruflin Yes, I'm releasing `7.4.1` soon with all the unexpected BC breaks. In the mean time, can you test https://github.com/elastic/elasticsearch-php/pull/968 and let me know if there are BC breaks in Elastica? 

I also tried to explain [here](https://github.com/elastic/elasticsearch-php/issues/967#issuecomment-558146095) the motivation behind the two potential BC breaks added intentionally in 7.4.0.

**Comment by deguif** [comment]
I just tested the test suite with  elastic/elasticsearch-php#968 and there are 2 remaining errors related to class renaming. See issue on elastic/elasticsearch-php#967 for more details.

**Comment by deguif** [comment]
Everything should be fine with the release of `elastic/elasticsearch-php` 7.4.1
I created PR #1715 to exclude version 7.4.0 but let greater version be installed.

**Comment by ezimuel** [comment]
I just released [7.4.1](https://github.com/elastic/elasticsearch-php/releases/tag/v7.4.1) that solves the BC break related to the endpoint class naming and it solves also the `trigger_error()` issue https://github.com/babenkoivan/scout-elasticsearch-driver/issues/297 using the suppress error `@` operator.

**Comment by deguif** [comment]
Thanks @ezimuel

**Comment by deguif** [comment]
I'm closing as all tests are now green.
