### ISSUE TITLE
send data to elastic

### ISSUE THREAD

**Issue by netwons** [ruflin/Elastica#1713]
How to store information in elastic?

How to read information from elastic?

please by example

**Comment by netwons** [comment]
Nobody knows anything

**Comment by ruflin** [comment]
Have you tried the links I mentioned here? https://github.com/ruflin/Elastica/issues/1699 Please elaborate in more details what you tried and what didn't work. 

Please also keep in mind, this is an open source project and you can't expect to get answers in a day on a weekend.
