### ISSUE TITLE
Publish a second beta

### ISSUE THREAD

**Issue by deguif** [ruflin/Elastica#1721]
What about publishing a second beta release?

**Comment by ruflin** [comment]
Yes, or should we go GA?

**Comment by deguif** [comment]
I would start with a second beta release ;)

**Comment by ruflin** [comment]
SGTM. Let me try to find some time for it this week.

**Comment by ruflin** [comment]
Here we go: https://github.com/ruflin/Elastica/releases/tag/7.0.0-beta2

**Comment by deguif** [comment]
Thanks @ruflin.
Is there a slack or something like this to discuss about some changes in the code?

**Comment by ruflin** [comment]
There is a Gitter channel but TBH I stopped really following it (lack of time). I strongly prefer the async communication whenever possible. Should we try to kick it off in a Github issue. If that doesn't work, happy to find out a chat way (I have a few in mind ;-) ).
