### ISSUE TITLE
Suggest you don't have to add fields source.

### ISSUE THREAD

**Issue by EliuFlorez** [ruflin/Elastica#1751]
Currently, a completion suggest request like this:
```
{
   "search_suggest" : {
      "completion" : {
         "field" : "name_suggest"
      },
      "prefix" : "nirv"
   }
}
```
returns all fields for each hit. I can't find a way to configure it so it just returns the fields I need. Seems like it may be faster if it didn't have to send everything back?

I tried adding:
```
public function setSource($params): self
{
	return $this->setParam('_source', $params);
}
```
But it gives me error.
**unexpected token [START_ARRAY] after [_source]**

I'm using elasticsearch 7.5

**Comment by ruflin** [comment]
What should the original request to ES look like? Perhaps try `setRawParam`?

**Comment by EliuFlorez** [comment]
It was not my mistake, since in suggesters I cannot sort by a specific fields. but if I can assign a weight which I order by the category that has more records. :1st_place_medal:
