### ISSUE TITLE
Terms aggregation with exact values in include

### ISSUE THREAD

**Issue by Chronoes** [ruflin/Elastica#1764]
After finally upgrading to Elasticsearch 7.x and Elastica 7.0.0-beta.3 I discovered that `Elastica\Aggregation\Terms::setInclude` no longer works due to type-hinting in #1549 . Looking at the docs, it makes sense but it ignores filtering by exact values [](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/search-aggregations-bucket-terms-aggregation.html#_filtering_values_with_exact_values_2) which expects an array instead of string. 

It seems that a similar issue was brought up in #1514 regarding incorrect docblock which has most likely caused the automated type-hinting to fail.

**Comment by ruflin** [comment]
@thePanz Could you take a look at this? 
@Chronoes Can you share the code snippet you are using and fails?

**Comment by thePanz** [comment]
I agree with @Chronoes : the ES documentation allows, for the `includes` property:
- a string (as a regexp)
- an array of strings (for [exact matches](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_filtering_values_with_exact_values_2))
- an object (for [partitions](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_filtering_values_with_partitions))

A first solution would be to allow a mixed "includes", or have a specialized setters (setInclueRegexp, setIncludeExact, setIncludePartitions) to handle those specific cases. wdyt @ruflin ?

**Comment by Chronoes** [comment]
> @thePanz Could you take a look at this?
> @Chronoes Can you share the code snippet you are using and fails?

Sure, it's pretty straightforward.
```
$aggregation = new \Elastica\Aggregation\Terms('foobar');
$aggregation->setInclude(['foo', 'bar']);
// TypeError: Argument 1 passed to Elastica\Aggregation\AbstractTermsAggregation::setInclude()
// must be of the type string, array given
```
For the time being, the workaround `$aggregation->setParam('include', ['foo', 'bar']);` works as well but it's not exactly in the spirit of this library.

**Comment by thePanz** [comment]
@Chronoes I implemented a fix in #1766 can you test if it works for you?
I choose to add specific methods to properly handle those cases

**Comment by Chronoes** [comment]
Yep, that works just fine. Thank you @thePanz

**Comment by thePanz** [comment]
Thanks for testing @Chronoes ! Pr merged and issue closed :)
