### ISSUE TITLE
Error or Bugs = Data too large

### ISSUE THREAD

**Issue by EliuFlorez** [ruflin/Elastica#1772]
Hello guys, I am presenting an error already with the system in production sometimes it throws the error other times it works well. Some qualitative idea would be the error and a solution.

#Error
app.CRITICAL: [parent] Data too large, data for [<http_request>] would be [1035672130/987.6mb], which is larger than the limit of [986061209/940.3mb], real usage: [1035671896/987.6mb], new bytes reserved: [234/234b], usages [request=72/72b, fielddata=20762933/19.8mb, in_flight_requests=234/234b, accounting=9022985/8.6mb] in File: /vendor/ruflin/elastica/lib/Elastica/Transport/Http.php:183 ["defaultException"] []

#Error
app.CRITICAL: Elasticsearch Synchronization Failure {"exception":"[object] (Elastica\\Exception\\ResponseException(code: 0): [parent] Data too large, data for [<http_request>] would be [1021614284/974.2mb], which is larger than the limit of [986061209/940.3mb], real usage: [1021611568/974.2mb], new bytes reserved: [2716/2.6kb], usages [request=72/72b, fielddata=20891007/19.9mb, in_flight_requests=2716/2.6kb, accounting=8988391/8.5mb] at /vendor/ruflin/elastica/lib/Elastica/Transport/Http.php:183)"} []

**Comment by ruflin** [comment]
Did not investigate but I would assume you hit of one of your php.ini configs? The other question is, why do you have requests that are almost 1GB? :-)

**Comment by EliuFlorez** [comment]
@ruflin Hi, I really don't know. What if I know that it gave me that error I have an index of more than 2GB because it is the information of all the localities, countries, states, city and an aggregation process is carried out to know how many publications exist in each country, state or city. . maybe the size of the query is my problem.

**Comment by ruflin** [comment]
Ah wait, this error is based on a query? And in your query you tried to fetch ALL the data at once?

**Comment by damienalexandre** [comment]
This is an Elasticsearch related error, see https://www.elastic.co/guide/en/elasticsearch/reference/current/circuit-breaker.html for more informations.

There is nothing Elastica can do here I'm affraid.

**Comment by thePanz** [comment]
I agree with @damienalexandre , we had the same issue on our Production instances: the issue is related to the ES cluster configuration, not on the Elastica library.

**Comment by EliuFlorez** [comment]
The way I found to fix this problem is to increase the dynamic storage size to 4G. example: java -Xms1024m -Xmx4096m and modifying alike forms the elasticsearch jvm.options
