### ISSUE TITLE
Version 6.x - Http Transport: Use forceMerge() fails because of HTTP request missing its content type

### ISSUE THREAD

**Issue by romainneutron** [ruflin/Elastica#1779]
The issue happens on Amazon Elasticsearch 6.8 with the latest version 6 of ruflin/Elastica

I'm using`foremerge()` to force-merge an index:
```
$result = $this->client->getIndex($index)->forcemerge([
    'max_num_segments' => 1,
])
```

Unfortunately, this fails, here's the `var_dump` of `$result`:

```
object(Elastica\Response)#606 (6) {
  ["_queryTime":protected]=>
  float(0.0024068355560303)
  ["_responseString":protected]=>
  string(0) ""
  ["_transferInfo":protected]=>
  array(37) {
    ["url"]=>
    string(162) "https://mydomain.amazonaws.com:443/my_index/_forcemerge?max_num_segments=1"
    ["content_type"]=>
    string(16) "application/json"
    ["http_code"]=>
    int(403)
    ["header_size"]=>
    int(193)
    ["request_size"]=>
    int(287)
    ["filetime"]=>
    int(-1)
    ["ssl_verify_result"]=>
    int(0)
    ["redirect_count"]=>
    int(0)
    ["total_time"]=>
    float(0.002392)
    ["namelookup_time"]=>
    float(2.8E-5)
    ["connect_time"]=>
    float(2.8E-5)
    ["pretransfer_time"]=>
    float(0.000111)
    ["size_upload"]=>
    float(0)
    ["size_download"]=>
    float(213)
    ["speed_download"]=>
    float(106500)
    ["speed_upload"]=>
    float(0)
    ["download_content_length"]=>
    float(213)
    ["upload_content_length"]=>
    float(0)
    ["starttransfer_time"]=>
    float(0.000114)
    ["redirect_time"]=>
    float(0)
    ["redirect_url"]=>
    string(0) ""
    ["primary_ip"]=>
    string(9) "10.0.8.52"
    ["certinfo"]=>
    array(0) {
    }
    ["primary_port"]=>
    int(443)
    ["local_ip"]=>
    string(12) "192.168.64.2"
    ["local_port"]=>
    int(40512)
    ["http_version"]=>
    int(3)
    ["protocol"]=>
    int(2)
    ["ssl_verifyresult"]=>
    int(0)
    ["scheme"]=>
    string(5) "HTTPS"
    ["appconnect_time_us"]=>
    int(28)
    ["connect_time_us"]=>
    int(28)
    ["namelookup_time_us"]=>
    int(28)
    ["pretransfer_time_us"]=>
    int(111)
    ["redirect_time_us"]=>
    int(0)
    ["starttransfer_time_us"]=>
    int(114)
    ["total_time_us"]=>
    int(2392)
  }
  ["_response":protected]=>
  array(1) {
    ["message"]=>
    string(199) "When Content-Type:application/x-www-form-urlencoded, URL cannot include query-string parameters (after '?'): '/my_index/_forcemerge?max_num_segments=1'"
  }
  ["_status":protected]=>
  int(403)
  ["_jsonBigintConversion":protected]=>
  bool(false)
}
```

When digging which headers are sent for this request, I realize the content-type is not set: https://github.com/ruflin/Elastica/blob/6.x/lib/Elastica/Transport/Http.php#L142

In the particular case of the _forcemerge API, the body is empty, parameters are passed in the URL as query string.

WIthin the HTTP transport, the content-type is set only when data is attached to the request. However it seems my php-curl uses a default `Content-Type: application/x-www-form-urlencoded` when a POST request is issued.

FYI I'm using:

```
$ php -v
PHP 7.3.17 (cli) (built: May  6 2020 22:54:47) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.17, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.17, Copyright (c) 1999-2018, by Zend Technologies

$ php --ri curl

curl

cURL support => enabled
cURL Information => 7.64.0
Age => 4
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => Yes
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => Yes
SPNEGO => Yes
SSL => Yes
SSPI => No
TLS-SRP => Yes
HTTP2 => Yes
GSSAPI => Yes
KERBEROS5 => Yes
UNIX_SOCKETS => Yes
PSL => Yes
HTTPS_PROXY => Yes
MULTI_SSL => No
BROTLI => No
Protocols => dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtmp, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Host => x86_64-pc-linux-gnu
SSL Version => OpenSSL/1.1.1d
ZLib Version => 1.2.11
libSSH Version => libssh2/1.8.0

Directive => Local Value => Master Value
curl.cainfo => no value => no value
```

The issue is easily reproducible with curl:

```
curl -H 'Content-type: application/x-www-form-urlencoded' -H 'Accept: ' -XPOST -v https://mydomain.amazonaws.com:443/my_index/_forcemerge?max_num_segments=1
```

I'm going to post a patch for this issue

**Comment by romainneutron** [comment]
Unfortunately I did not manage to reproduce my issue in the test suite

**Comment by romainneutron** [comment]
I've checked if this might be related to the forcemerge issue reported in https://github.com/ruflin/Elastica/pull/1686, but it's not

**Comment by ruflin** [comment]
Is this specific to AWS Elasticsearch or applies also to Elasticsearch from Elastic? If only AWS, I wonder who it is different?

**Comment by romainneutron** [comment]
I was actually wrong, it was not happening because elasticsearch but because of the default HTTP "Content-Type" header sent by the cURL extension.

When a post request is issued with PHP curl, using the POST method, it may use a default "Content-Type" header that could value "application/x-www-form-urlencoded". However, elasticsearch does not accept such requests on this endpoint.

Forcing POST request to use their `Content` header even if the body is empty fixes the issue

**Comment by romainneutron** [comment]
So, it appears that PHP cURL behavior is tied to the query string:

Here's elasticsearch error: `{"message":"When Content-Type:application/x-www-form-urlencoded, URL cannot include query-string parameters (after '?'): '/my_index/_forcemerge?max_num_segments=1'"}`

This is solved by forcing curl to use `Content-Type: application/json` header

**Comment by ruflin** [comment]
+1 on adding our default content type  if it is not added in your case: https://github.com/ruflin/Elastica/blob/98b2f9d6c72edf1bd9c7337576d303f644a6d82a/src/Request.php#L19 @romainneutron Could you open a PR with your change?

**Comment by romainneutron** [comment]
@ruflin Correct me if I'm wrong, but my pull-request https://github.com/ruflin/Elastica/pull/1780 does this. Since the `Request` always have a content-type, + my pull request, it ensures outgoing HTTP request always include the content-type (the one explicitely set or the default one)
