### ISSUE TITLE
self return type confuses static analysis tools

### ISSUE THREAD

**Issue by BackEndTea** [ruflin/Elastica#1786]
The self return type does not mean a `$this` return type to static analysis tools. 

When the following method in the `AbstractTermsAggregation`  class is called on the `Terms` class, SA tools will think an instance of the `AbstractTermsAggregation` is returned. Meaning that `setOrder` can not be called on it.
adding `@return $this` to all relevant methods should fix this.

```php
    /**
     * Sets the amount of terms to be returned.
     */
    public function setSize(int $size): self
    {
        return $this->setParam('size', $size);
    }
```

**Comment by ruflin** [comment]
@BackEndTea Could you open a PR?

**Comment by deguif** [comment]
Closing as #1857 was merged.
