### ISSUE TITLE
Wrong total hist

### ISSUE THREAD

**Issue by kr0lik** [ruflin/Elastica#1792]
https://github.com/ruflin/Elastica/blob/9146c80736cde1cf38cda29eb191130c4536bf44/src/ResultSet.php#L149

In old versions hits.total returned as int, no object. I suggest adding a check like this:
```
if (isset($data['hits']['total'])) {
    return is_int($data['hits']['total']) ? $data['hits']['total'] : (int) $data['hits']['total']['value'];
}

return 0;
```

**Comment by ruflin** [comment]
@kr0lik Which ES version are you using? If we don't have already, would be great to have a test for this to confirm.

**Comment by kr0lik** [comment]
Sorry, i was quickly create isse. Now i added some more information. My version 6.8.1. As I understood this parameter this parameter has been added to ease the transition to the new format and will be removed in the next major version (8.0).

**Comment by kr0lik** [comment]
I did not notice that there is a version under 6 es.
