### ISSUE TITLE
Parse error for Match class on php 8.0

### ISSUE THREAD

**Issue by BackEndTea** [ruflin/Elastica#1793]
Match can no longer be used as a class name in php 8.0.

https://3v4l.org/IuL7p

```
ParseError: syntax error, unexpected token "match"
```

**Comment by ruflin** [comment]
@BackEndTea Thanks for the heads up. I must confess I haven't started to think about PHP 8.0 yet. Seems like we will need to prefix the class name somehow.

Did you see other issue with Elastica an PHP 8.0?

**Comment by BackEndTea** [comment]
So far i haven't seen any issues, but i just started running the unit tests in CI.

What i've seen other projects do that use class names that are reserverd (like `String`). They add an underscore as a suffix:
`class String_`. 

It would probably work to rename the class, and in the place of the `Match.php` file add a class alias. Though i'm not  sure if that breaks preloading.

**Comment by deguif** [comment]
@BackEndTea Just started to work on this. See #1794

**Comment by deguif** [comment]
Should be fixed by #1799

**Comment by ruflin** [comment]
Going to close this issue. Please reopen if this problem still exists on master.

**Comment by natewiebe13** [comment]
@ruflin what's left before a new tag is created that includes this fix?

**Comment by deguif** [comment]
@natewiebe13 we're waiting an official release of https://github.com/elastic/elasticsearch-php 
That should be soon as PRs about PHP 8.0 support were merged recently there.
