### ISSUE TITLE
Percentiles Bucket aggregation missing

### ISSUE THREAD

**Issue by mkosiedowski** [ruflin/Elastica#1805]
Hi! I noticed that PercentilesBucket aggregation is missing (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-percentiles-bucket-aggregation.html).

I will prepare a change in the code and post a pull request in a moment - I am creating that issue just for tracking purpose ;)

**Comment by ruflin** [comment]
@mkosiedowski Thank you!
