### ISSUE TITLE
6.x branch DateRange aggregation does not support timezone parameter

### ISSUE THREAD

**Issue by dinamic** [ruflin/Elastica#1846]
Hey guys 👋

Thanks for keeping an eye on and maintaining this library!

Could we add support for the timezone on the date range aggregation, please? Is it a matter of just adding a setter on the DateRange class?

Here's the official documentation:
- https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-aggregations-bucket-daterange-aggregation.html#time-zones

**Comment by deguif** [comment]
See #1847 thats targets master.
Can probably be backported to 6.x.

**Comment by deguif** [comment]
#1847 was merged into master.
