### ISSUE TITLE
Release 7.1.0

### ISSUE THREAD

**Issue by romainneutron** [ruflin/Elastica#1896]
Hello, 

A lot of features have been added in the master branch. What about releasing them in a stable version ?

**Comment by deguif** [comment]
See https://github.com/ruflin/Elastica/pull/1871
We're waiting a release on `https://github.com/elastic/elasticsearch-php` regarding official PHP 8.0 support

**Comment by deguif** [comment]
Released: https://github.com/ruflin/Elastica/releases/tag/7.1.0

**Comment by ruflin** [comment]
@deguif THANK YOU!
