### ISSUE TITLE
Re-enable CI on 6.x branch

### ISSUE THREAD

**Issue by reedy** [ruflin/Elastica#1903]
As noticed in https://github.com/ruflin/Elastica/pull/1902, it seems you can commit invalid PHP on the 6.x branch, and CI won't complain at all...

**Comment by reedy** [comment]
I'm guessing Travis was turned off because master moved to using github actions... But 6.x is still active/maintained, making the .travis.yml a no-op..

**Comment by ruflin** [comment]
Yes, I guess we should move 6.x also to Github action if we still maintain it and make releases on it. @deguif Could we do a minimal set of checks?

**Comment by deguif** [comment]
Yes probably, need some time to do that ;)

**Comment by deguif** [comment]
> I'm guessing Travis was turned off because master moved to using github actions... But 6.x is still active/maintained, making the .travis.yml a no-op..

Travis CI was disabled automatically because free quota for OSS was exceeded, that's why project was migrated to GA.

**Comment by deguif** [comment]
Closing as #1918 was merged in `6.x` branch.
