### ISSUE TITLE
Should docker folder be added to .gitattributes

### ISSUE THREAD

**Issue by reedy** [ruflin/Elastica#1937]
Noticed in https://github.com/ruflin/Elastica/releases/tag/6.1.4

Is there any reason to not add the docker folder to .gitattributes? I believe it exists mostly for CI purposes, and as such, we don't ship the tests folder, so we shouldn't need to ship the docker folder either...

**Comment by deguif** [comment]
@reedy you're right, it can probably be added in `.gitattributes`.

**Comment by reedy** [comment]
I'll do a PR for master and 6.x :)

**Comment by deguif** [comment]
Thanks @reedy
