### ISSUE TITLE
X-Pack aggregations

### ISSUE THREAD

**Issue by panychek** [ruflin/Elastica#1953]
What's your view on including X-Pack-related stuff to Elastica?
For instance, I could provide a PR for the [Normalize pipeline aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-normalize-aggregation.html), which I make use of. But due to the OSS Docker images, functional testing won't be possible in this case.

**Comment by ruflin** [comment]
@panychek ++ on adding x-pack related stuff. I think we should remove the `-oss` from the testing part: https://github.com/ruflin/Elastica/blob/master/docker/docker-compose.es.yml#L5 Let me open a PR

**Comment by ruflin** [comment]
I opened https://github.com/ruflin/Elastica/pull/1954

**Comment by ruflin** [comment]
Support for the basic version added. @panychek Do you plan to open a PR?
