### ISSUE TITLE
cumulative_sum aggregation

### ISSUE THREAD

**Issue by Aassifh** [ruflin/Elastica#1972]
Does cumulative sum aggregation exists in this project ? thank you

**Comment by ruflin** [comment]
Here is the list of aggregations that we support at the moment: https://github.com/ruflin/Elastica/tree/master/src/Aggregation You can always use "raw requests" to send any query with the lib if needed. Interested to contribute the classes needed for cumulative sum aggregation?

**Comment by deguif** [comment]
Closing as it was implemented in #1987 and merged.
