### ISSUE TITLE
problem with php 8 in 7.1.1 package version

### ISSUE THREAD

**Issue by timmi129** [ruflin/Elastica#1975]
Package in version 7.1.1 supports php version 8.0 and uses elasticsearch/elasticsearch in version 7.1.1, but  elasticsearch/elasticsearch  supports php 8 version only from 7.11.0.

**Comment by deguif** [comment]
Can you run `composer update elasticsearch/elasticsearch`, that should upgrade to a more recent version of `elasticsearch/elasticsearch`.

**Comment by timmi129** [comment]
I can't, package has hard restriction:
<img width="261" alt="Снимок экрана 2021-09-09 в 10 26 39" src="https://user-images.githubusercontent.com/39489931/132641949-505a23c8-4334-4cef-9a4c-932de78cd54f.png">

**Comment by deguif** [comment]
It's not hard restricted when using the caret operator (see: https://getcomposer.org/doc/articles/versions.md#caret-version-range-). 
It means here that minimum version is `7.1.1` but it allows all other versions < `8.0` for `elasticsearch/elasticsearch`, which includes `7.14`.

If it was `~7.1.1` it would behave as you stated (see: https://getcomposer.org/doc/articles/versions.md#tilde-version-range-)
See https://github.com/ruflin/Elastica/pull/1736#issuecomment-576368800 for why `7.1.1` is the minimum supported elasticsearch php skd version

**Comment by thePanz** [comment]
@timmi129 I can not reproduce the issue you mentioned: I am using php 8.0.10

About the `^` operator:
> The ^ operator [..] sticks closer to semantic versioning, and will always allow non-breaking updates. For example ^1.2.3 is equivalent to >=1.2.3 <2.0.0 as none of the releases until 2.0 should break backwards compatibility.

**Comment by deguif** [comment]
@thePanz @timmi129 we can probably close this issue, WDYT?

**Comment by thePanz** [comment]
Closing this issue, feel free to reopen in case the problem persists.
