### ISSUE TITLE
More Match class PHP 8 fun (in 6.x)

### ISSUE THREAD

**Issue by reedy** [ruflin/Elastica#1978]
From our downstream issue - https://phabricator.wikimedia.org/T268861#7359008

Because of how I did `MatchQuery extends Match`, `Match` is still executed, meaning it does fail on PHP 8.0. And that's kinda fine, as I did it for forward compat purposes (so people could switch to `MatchQuery` earlier, and depending on their code, be able to support later 6.x and also 7.x).

As per https://github.com/ruflin/Elastica/blob/6.1.5/composer.json#L15, 6.1.x doesn't support PHP 8 either (at least officially, you can obviously ignore certain requirements).

We're contemplating how to do PHP 8 migration for Wikipedia (et al), and as our ES upgrade might not have happened by then (and hence, also upgrading ruflin/elastica and elasticsearch/elasticsearch-php).

Would a patch to make MatchQuery the canonical (ie find and replace Match with MatchQuery, and then make the `class Match extend MatchQuery` instead) be accepted?

This is related to https://github.com/ruflin/Elastica/issues/1913... And would be needed to support that. As per the backtrace below (from the task/comment linked above)

```
[99a80ba4319b973cca1c54a7] /index.php?search=%C3%A9v%C3%A9nement+%3A+c&title=Sp%C3%A9cial%3ARecherche&go=Lire&ns0=1 ParseError: syntax error, unexpected token "match"

Backtrace:

from /var/www/vhosts/fallout-wiki.com/httpdocs/extensions/Elastica/vendor/ruflin/elastica/lib/Elastica/Query/MatchQuery.php(10)
```

And that line is https://github.com/ruflin/Elastica/blob/6.1.5/lib/Elastica/Query/MatchQuery.php#L10, so we would need to stop that being executed.

I think I did mumble about this in one of the prior tasks, expecting something like this might eventually happen.

So I guess the TLDR... Is would a patch swapping `MatchQuery` and `Match` be welcomed, in support of https://github.com/ruflin/Elastica/issues/1913 and potentially being able to make 6.x support PHP 8 (obviously might be other issues down the line).

**Comment by Hikariii** [comment]
+1 for php8 support on the 6.x branch.

**Comment by reedy** [comment]
Seems https://github.com/ruflin/Elastica/pull/1977 was created before I created this issue...

**Comment by ruflin** [comment]
I definitively support this. The important part for me is that we don't break existing installations but it seems with this approach this is possible.

**Comment by reedy** [comment]
My version in https://github.com/ruflin/Elastica/pull/1981 does that, AFAIK...
