### ISSUE TITLE
Geodistance filter, missing options

### ISSUE THREAD

**Issue by pierrre** [ruflin/Elastica#200]
There are missing options:
- distance_type
- optimize_bbox

Do you have any recommendation?
Are class constants required? (arc, plane, memory, indexed, none)

**Comment by ruflin** [comment]
@pierrre As you closed this, I assume this is not needed anymore or already implemented.

**Comment by pierrre** [comment]
Yes, I closed all my old issues: https://github.com/pierrre?tab=activity
I use the official PHP client.

**Comment by ruflin** [comment]
Ok, thx. Even though I would prefer that you would still use Elastica ;-)

**Comment by pierrre** [comment]
:-(
