### ISSUE TITLE
(Question) ElasticSearch App support

### ISSUE THREAD

**Issue by coreation** [ruflin/Elastica#2059]
Hi everyone,

I was wondering if there was support in Elastica for ElasticSearch "Enterprise Search" endpoints.
I've recently been digging into their documentation and things look very much the same as if you would do regular ElasticSearch query, but I assume these endpoints are not supported in this library?

If so, does anyone have experience with other compatible libraries that wrap "Enterprise Search" functionality?
In all honesty, I won't have time to contribute to what seems like a lot of work, so if the answer is no, this question ticket can be closed.

**Comment by ruflin** [comment]
Elastic Enterprise Search stores all its data in Elasticsearch. So if you want to query the data directly from Elasticsearch, things should just work. But there are also custom endpoints built with additional services AFAIK. These will likely have a custom API and are not supported by Elastica. And as you say, it would be quite an effort to support these.

Be aware, I have not used Enterprise Search APIs and only the UI part so the above information might be wrong.

**Comment by coreation** [comment]
Thanks the info @ruflin , that was what I expected, as always, great library and appreciate the effort of you and the community!
