### ISSUE TITLE
[DateHistogram] `interval` field is deprecated

### ISSUE THREAD

**Issue by kissifrot** [ruflin/Elastica#2097]
Hello,

`interval` field is deprecated in [7.x](https://www.elastic.co/guide/en/elasticsearch/reference/7.14/search-aggregations-bucket-datehistogram-aggregation.html#calendar_and_fixed_intervals) (in favor of `fixed_interval)` and was deleted in 8.x version of ElasticsSearch, would it be possible to replace it?

**Comment by thePanz** [comment]
Fixed in d4849e2
