### ISSUE TITLE
Get default values from index setting api

### ISSUE THREAD

**Issue by krasilnikovm** [ruflin/Elastica#2114]
### Problem:
I need to retrieve index settings like 'max_result_window' but in the response body default value is not returned, in order to fetch the default value need to add the include_default query param to /_setting request.

### Suggestion:
We can add the ability to set flag include_default(or by default set to true?) and change the behavior of \Elastica\Index\Settings::get method

1. search setting value in the `setting` key as before
2. if the value is not found on 1 step then search setting value in default key.

**Comment by krasilnikovm** [comment]
What do think about this? is it will be useful for this lib?

**Comment by krasilnikovm** [comment]
I have prepared PR: https://github.com/ruflin/Elastica/pull/2115

**Comment by deguif** [comment]
Closing as this merged.
