### ISSUE TITLE
Parse error with T_PAAMAYIM_NEKUDOTAYIM

### ISSUE THREAD

**Issue by benr77** [ruflin/Elastica#2122]
I'm getting a parse error on what seems to be valid code.  (version 7.2)

The error is shown when I run composer-require-checker (see https://github.com/maglnet/ComposerRequireChecker/issues/357), but eval'ing the code also results in a parse error.

See https://3v4l.org/6UpX2

```
<?php

namespace Elastica\Query;

\trigger_deprecation('ruflin/elastica', '7.1.0', 'The "%s" class is deprecated, use "%s" instead. "match" is a reserved keyword starting from PHP 8.0. It will be removed in 8.0.', Match::class, MatchQuery::class);
```

And the parse error is:

```
Parsing the file [/var/www/vendor/ruflin/elastica/src/Query/Match.php] resulted in an error: Syntax error, unexp  
  ected T_PAAMAYIM_NEKUDOTAYIM, expecting ':' on line 5
```

I'm running PHP 8.1 on linux.

Thanks

**Comment by deguif** [comment]
@benr77 you should not use `Match` class on PHP > 8.0 as `match` is become a reserved keywork. That's why `MatchQuery` was introduced. Use this one instead.

**Comment by SvenRtbg** [comment]
@deguif You mean this code? https://github.com/ruflin/Elastica/blob/7.2.0/src/Query/Match.php

**Comment by deguif** [comment]
I mean, use this one instead: https://github.com/ruflin/Elastica/blob/master/src/Query/MatchQuery.php
It's the same without the issue you're having as the class name is not reserved keyword.

**Comment by benr77** [comment]
I understand to use `MatchQuery` instead of `Match` on PHP > 8.0. 

The problem is that the code is being analysed by Composer Require Checker and this is causing a parse error. 

I think if we just change `Match::class` to use the actual string `Elastica\Query\Match` it should be fine.

Is this an acceptable change?

**Comment by deguif** [comment]
You can try locally. But I think that will break with the class name too and we can't change the class name as it would break backward compatibility.

**Comment by deguif** [comment]
See this issue which is similar to yours https://github.com/maglnet/ComposerRequireChecker/issues/283
From what I understand there is no way to exclude some files/classes from analysis.
What's wrong with this tool is that it analyses every vendor files even if you're not using them in your project. Looking at the list of issues, there're quite some similar issues.

**Comment by benr77** [comment]
Yes, I can see now. I will have to just run the tool with the `--ignore-parse-errors` option.

Thanks for your help!
