### ISSUE TITLE
Support the Combined Fields query type

### ISSUE THREAD

**Issue by mparker17** [ruflin/Elastica#2195]
The Combined Fields query type was introduced in ElasticSearch 7.13.

See
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-combined-fields-query.html for more information.

A combined fields query is useful for frameworks like Drupal, which store data in structured fields.

**Comment by ruflin** [comment]
~~@mparker17Interested to contribute?~~  😇  

Update: Nevermind, just saw https://github.com/ruflin/Elastica/pull/2196 Thank you!
