### ISSUE TITLE
Psalm error caused by duplicate line

### ISSUE THREAD

**Issue by delboy1978uk** [ruflin/Elastica#2198]
You've already fixed this, but it isn't yet in a 7.x release
https://github.com/ruflin/Elastica/blob/7.3.1/src/Query.php#L51C1-L52C36 

Can you cherry pick https://github.com/ruflin/Elastica/commit/2033a67f2fae7a440343ebaf13d2760f36b99d2c and tag a patch release  7.3.2 please? 

I originally thought it was psalm unable to properly handle phpstan tags, see here for context https://github.com/vimeo/psalm/issues/10810

**Comment by ruflin** [comment]
Good catch, seems there are 2 more commits not released yet in 7.x. Trying to tag a release soonish. @thePanz In case you get to it faster.

**Comment by thePanz** [comment]
on it @ruflin 

→ here you go: https://github.com/ruflin/Elastica/pull/2199

**Comment by thePanz** [comment]
@delboy1978uk @ruflin 
v7.3.2 has been released https://github.com/ruflin/Elastica/releases/tag/7.3.2

**Comment by delboy1978uk** [comment]
Thank you so much guys! ❤️
