### ISSUE TITLE
PHP 8.3 support please

### ISSUE THREAD

**Issue by DavidGarciaCat** [ruflin/Elastica#2200]
Good day,

I am working on an upgrade for a Symfony API which uses this Elastica Bundle. The new code is powered by PHP 8.3, which seems incompatible with the existing version restrictions/requirements.

Are there any short-term plans to support the new version?

Otherwise, some advice might be helpful for me or someone else to contribute and add support for the new version.

Thanks,

**Comment by VincentLanglet** [comment]
Hi, why do you think PHP 8.3 is not supported ?

- In 8.x it's allowed https://github.com/ruflin/Elastica/blob/8.x/composer.json#L18
- In 7.x also https://github.com/ruflin/Elastica/blob/7.x/composer.json#L18

**Comment by DavidGarciaCat** [comment]
Answering your question, “I think it's not supported” because I read the README and it says this (as you can see, the rule is “>=8.0 <8.2”):

![IMG_1794](https://github.com/ruflin/Elastica/assets/7809429/1cead38d-c0eb-44d0-ac8e-af5c0656c91c)

**Comment by VincentLanglet** [comment]
The readme is just not up to date.
There is CI on 8.3 https://github.com/ruflin/Elastica/commit/85e36c86d3f5816126d8bf1242c5edf8f4a247be

**Comment by DavidGarciaCat** [comment]
Understood. Thanks for the update.

But I hope you understand why I was opening this issue and what led me to the (apparent) wrong conclusion :-)

Enjoy the rest of your weekend!
