### ISSUE TITLE
Class Elastica_client not found

### ISSUE THREAD

**Issue by shevaton7** [ruflin/Elastica#253]
Hi everybody !

Thank for built this bundle.
I have an error when I execute my website : Fatal error: Class 'Elastica_Client' not found in C:\wamp\www\Symfony\vendor\bundles\FOQ\ElasticaBundle\Client.php on line 12
but in C:\wamp\www\Symfony\vendor\elastica\lib\Elastica\client.php I have déclaration of the class Elastica_client in client.php.

I need to know where this error does it come from please ?

Thank you for all !

**Comment by thiruvenkatam** [comment]
Hi everyone.

I installed Elastica using composer to my Laravel project folder. But i am facing "Class 'Elastica\Client' not found" error. I have followed the steps as per in the installation guide.
I need some help regarding this.

I will post controller code below.

<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Elasticsearch\ClientBuilder;
use Elastica\Client as ElasticaClient;

require_once 'C:\xampp\htdocs\logistics\vendor\autoload.php';

class ClientController extends Controller
{
    //
    protected $elasticsearch;
    protected $elastica;

    public function __construct()
    {
      $this->elasticsearch  = ClientBuilder::create()->build();

      $elasticaConfig=[
        'host' => 'localhost','port' => 9200 , 'index' => 'library'
      ];

      $this->elastica = new ElasticaClient($elasticaConfig);
    }

    public function test()
    {
      dump($this->elasticsearch);

      echo "Retriving Document:\n";
      $params = [
        'index' => 'library' , 'type' => 'books' , 'id' => '1'
      ];

      $response = $this->elasticsearch->get($params);
      dump($response);
    }
}

Thanks

**Comment by ruflin** [comment]
@thiruvenkatam Please do not double post: https://github.com/ruflin/Elastica/issues/1463
