### ISSUE TITLE
Couldnt connect to host, ElasticSearch down? 

### ISSUE THREAD

**Issue by shevaton7** [ruflin/Elastica#255]
Hi everybody !

I try to use ElasticaBundle with symfony and I get this following error :

Couldnt connect to host, ElasticSearch down? 

Please any one know how to fixe it ?

Thank you for your help

**Comment by ncrocfer** [comment]
I had the same problem and I found a solution here : https://phabricator.wikimedia.org/T73221#761042

I just forgot to restart Apache :

**Comment by ncrocfer** [comment]
I had the same problem and I found a solution here : https://phabricator.wikimedia.org/T73221#761042

I just forgot to restart Apache (`sudo service apache2 restart`) and it worked for me.
