### ISSUE TITLE
 Invalid UTF-8 sequence

### ISSUE THREAD

**Issue by techi602** [ruflin/Elastica#377]
Invalid UTF-8 sequence in argument in "Elastica/Transport/Http.php(95)"

Well this is pretty often warning I get for json_encode() since the query string is carried inside request uri.

Question is if we should treat the query string outside or inside the library.
I suggest to add silent operator and skip the query string it if json_encode() fails

**Comment by ruflin** [comment]
Closing as no updated provided.
