### ISSUE TITLE
Terms Filter not exposing all options

### ISSUE THREAD

**Issue by Tobion** [ruflin/Elastica#403]
The [Terms Filter](https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Filter/Terms.php) does not provide functionality to define `execution mode` and `terms lookup` options in ES: http://www.elasticsearch.org/guide/reference/query-dsl/terms-filter/

**Comment by ruflin** [comment]
Closed based on https://github.com/ruflin/Elastica/pull/741#issuecomment-68550735
