### ISSUE TITLE
Add Geo Shape Filter & Query

### ISSUE THREAD

**Issue by glennjacobs** [ruflin/Elastica#410]
Add Geo Shape Filter & Query to Elastica - need I say more? ;-)

**Comment by ruflin** [comment]
GeoShape Filters were added in the mean time. Queries are still missing.

**Comment by nicolassing** [comment]
Hello @ruflin, you're work on it or I can work on a pull request ? 

thx !

**Comment by ruflin** [comment]
@nicolassing Please open a pull request. Thx.

**Comment by nicolassing** [comment]
Ok I'll try to work on it this week end :)

**Comment by ruflin** [comment]
:+1:

**Comment by ruscon** [comment]
ping ?

**Comment by Tobion** [comment]
This can be closed as there are already `\Elastica\Query\GeoShapeProvided` and `\Elastica\Query\GeoShapePreIndexed` available.
