### ISSUE TITLE
Time To Live option

### ISSUE THREAD

**Issue by Sydney-o9** [ruflin/Elastica#425]
Hi @ruflin,

The *time to live* `_ttl`   [seems to be incorporated](https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Type/Mapping.php#L191-L194) in the library. I tried to set this up using `FOQElasticaBundle ` but it looks like the configuration file does not allow this.

Do you have any idea why?

I understand this issue belongs to FOSElasticaBundle instead so [I have posted my issue here](https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/340) but because these 2 bundles are linked together and because you coded most of FOQElasticaBundle, I quickly wanted to see what are you thoughts on this :)

Many many thanks @ruflin, I am enjoying this bundle more and more,

Cheers, 

Sydney_o9

**Comment by im-denisenko** [comment]
> issue belongs to FOSElasticaBundle

Fixed since https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/340#issuecomment-44014549.
