### ISSUE TITLE
disMax is throwing an error.

### ISSUE THREAD

**Issue by atsiddiqui** [ruflin/Elastica#426]
$builder = new \Elastica\Query\Builder();
$disMax = $builder->disMax();
    $query1 = .....;
    $query2 = .....;
    $max = $builder->queries(
    array(
        json_encode($query1->toArray()),
        json_encode($query2->toArray()),
    )
);
$query = new \Elastica\Query($max);

This gives error ```The query produced is invalid```. I think the problem is in the ```$builder->__toString()``` method. It needs to an extra ```}```.

**Comment by im-denisenko** [comment]
`Elastica\Query\Builder` is deprecated #855. Use new `Elastica\QueryBuilder` instead.

@atsiddiqui Reopen please, if you think that this issue really needs to be fixed.
