### ISSUE TITLE
Add reindex method to index class

### ISSUE THREAD

**Issue by Tobion** [ruflin/Elastica#473]
There should probably be a method in reindex all documents from one index into a new index. This is needed when one wants to change the mapping with no downtime. See http://www.elasticsearch.org/blog/changing-mapping-with-zero-downtime/

Several other client libraries already include that functionality:

- https://github.com/geronime/es-reindex (ruby)
- http://pythonhosted.org/pyes/references/pyes.es.html#pyes.es.ES.reindex (phyton)

Early draft. For some reason I get a Java exception inside elastic search as soon as there are documents in the old index.

```
[Elastica\Exception\ResponseException]
  MapperParsingException[mapping [product]]; nested: ClassCastException[java.
  util.ArrayList cannot be cast to java.util.Map];
```

The method is missing arguments to optionally overwrite the mapping and settings for the new index. Otherwise it would just be a copy.

```
// Elastica\Index

    /**
     *
     *
     * @return string The new index name
     *
     * @see http://www.elasticsearch.org/blog/changing-mapping-with-zero-downtime/
     */
    public function reindex()
    {
        $scrollResponse = $this->request('_search', Request::GET,
            array('query' => array(
                'match_all' => array()
            )),
            array('search_type' => 'scan', 'scroll' => '10m', 'size' => '100')
        );
        //var_dump($scrollResponse);

        $scrollId = $scrollResponse->getScrollId();
        unset($scrollResponse);

        $mapping = $this->getMapping();
        $settings = $this->getSettings()->get();

        $config = array();
        $config['mappings'] = $mapping[$this->_name];
        $config['settings'] = $settings;

        $this->_name = $this->_name . date('-Y-m-d-Gis');

        $this->create($config);

        unset($mapping, $settings, $config);

        $scrollResponse = $this->getClient()->request('_search/scroll', Request::GET,
            array(),
            array('scroll' => '10m', 'scroll_id' => $scrollId)
        );
        //var_dump($scrollResponse);

        return $this->_name;
    }
```

**Comment by progrupa** [comment]
+1

**Comment by michellesanver** [comment]
We just added reindexing at work using scan and scroll, I'll spend some time to extract it into Elastica\Util and make a pull request :)

**Comment by ruflin** [comment]
@michellesanver Looking forward to it.

**Comment by webdevsHub** [comment]
Added in https://github.com/ruflin/Elastica/issues/853 
Thanks @Tobion
