### ISSUE TITLE
Type->deleteById() throws NotFoundException for missing documents

### ISSUE THREAD

**Issue by rayward** [ruflin/Elastica#565]
Just wanted to initiate some discussion around whether this method should consider a missing document an error.

https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Type.php#L423

In my opinion, its not an error and shouldn't throw the `NotFoundException`. Trying to delete a document that doesn't exist still ends up with the same result, the document no longer exists. This seems fine to me.

Elastic doesn't consider it an error as it doesn't populate the `error` field. For comparison, neither does MySQL. It will say `Query OK, 0 rows affected (0.00 sec)`.

Also, there's an inconsistency with the Bulk delete, as it doesn't generate any exceptions for missing documents.

If someone wants to know whether the document did exist and was actually deleted then they can read the response data and check the `found` element themselves.

**Comment by tastendruecker** [comment]
I just stumbled over this problem and would like to pick up the discussion again. I agree with rayward: As the result is the same, no exception should be thrown. My suggestion would be to remove the corresponding block.
@ruflin Would that be okay with you? Would you remove that code?

**Comment by ruflin** [comment]
I'm ok with changing it, but I would like to have still a way to identify if the doc was actually deleted or not. This could be through a bool or an int that is returned couting how many docs were deleted. Feel free to open a PR for further discussions.

**Comment by tastendruecker** [comment]
Isn't the returned $response object supposed to carry that information? (Please bare with me as I haven't much experience with Elastica. I just depend on using it within a project that had been designed before I entered the project team.)

**Comment by ruflin** [comment]
@tastendruecker You are probably right. I'm not sure what the exact response will be. Can you open a PR? Then we can directly check it in the tests :-)
