### ISSUE TITLE
Script fields being returned as nested array

### ISSUE THREAD

**Issue by Decave** [ruflin/Elastica#584]
It appears as though script field values are now being returned as nested arrays as opposed to direct values. For example, calling ```getFields()``` on a result set used to return:
```
array(2) {
      ["max_weight"]=>
        float(1.8475695),
      ["distance"]=>
        float(11954.734459781)
}
```
but now returns:
```
array(2) {
      ["max_weight"]=>
      array(1) {
        [0]=>
        float(1.8475695)
      }
      ["distance"]=>
      array(1) {
        [0]=>
        float(11954.734459781)
      }
}
```
Was this change intentional? If so, could someone explain why it was implemented? Thanks in advance.

**Comment by ruflin** [comment]
Closing as no updates were provided. Please reopen if this is still an issue.
