### ISSUE TITLE
Add MatchPhrase and MatchPhrasePrefix classes

### ISSUE THREAD

**Issue by ThePixelDeveloper** [ruflin/Elastica#599]
Came up to using these features and realise Elastica didn't have the classes for them.

Features defined in ES here:

1. [match_phrase](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-match-query.html#_phrase)
2. [match_phrase_prefix](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-match-query.html#_match_phrase_prefix)

Worth adding new classes for these?

**Comment by yehosef** [comment]
I think the library is most useful when it matches the documented way of doing it - and if there are two ways of doing the same thing I would prefer that be replicated in the library (obviously with a proxy method).

**Comment by olee** [comment]
Also there is no method to set slop without having a class for that.
Currently you need to call
````
$match->setFieldParam('myField', 'slop', 100);

**Comment by ruflin** [comment]
@yehosef @olee Does anyone of you have some spare time to open a pull request with the mentioned changes?

**Comment by yehosef** [comment]
@ruflin  - I'll try.

**Comment by ruflin** [comment]
@yehosef Thx

**Comment by Jmoati** [comment]
@ruflin Can you please close this issue ?
