### ISSUE TITLE
Builder not support muli and filter

### ISSUE THREAD

**Issue by 1337er** [ruflin/Elastica#638]
Hey. Is it possible, that the Query/Builder support "and" condition like this:

```json
...
"filter": {
	"and": [
		{
			"range": {
				"@timestamp": {
        	"gte": "2014-05-01",
          "lt": "2014-05-30"
        }
      }
    },
		{
			"id": {
				"@id": "27"
			}
		}
  ]
},
...
```

**Comment by im-denisenko** [comment]
`Elastica\Query\Builder` is deprecated #855. Use new `Elastica\QueryBuilder` instead.

@1337er Reopen please, if you think that this issue really needs to be fixed.
