### ISSUE TITLE
field_value_factor support

### ISSUE THREAD

**Issue by dwenaus** [ruflin/Elastica#639]
will field_value_factor be supported?

**Comment by yehosef** [comment]
I think this should be reopened.  Other options of the function_score are supported natively: weight, script, random, decay.  It's not clear why the field_value_factor should not be supported natively.

I think it's fine to leave open for someone to make the changes and pull request - but in my mind this is still an unresolved issue.

**Comment by ruflin** [comment]
@yehosef Agree. I reopened it.

**Comment by ruflin** [comment]
Implemented through https://github.com/ruflin/Elastica/pull/953/files

**Comment by dwenaus** [comment]
:D
