### ISSUE TITLE
Memory limit error, if elasticsearch not started

### ISSUE THREAD

**Issue by ZhukV** [ruflin/Elastica#646]
Hi. I have a memory limit error (In .ini file set 512Mb memory limit), if elasticsearch not started and php script work from CLI mode.

```
[Wed Jul 02 20:02:20 2014] [error] [client 141.8.147.6] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 77 bytes) in /var/www/domain.com/releases/20140702125752/vendor/ruflin/elastica/lib/Elastica/Response.php on line 277
```

If i start elastic search, this problem disappears.

OS: Debian
PHP: PHP 5.4.30-1~dotdeb.1 (cli) (built: Jun 29 2014 23:18:55) 

Thank.

**Comment by ruflin** [comment]
Closing as no new information.
