### ISSUE TITLE
Using "name" or "alias" in nested query

### ISSUE THREAD

**Issue by net8floz** [ruflin/Elastica#651]
I have a type "Region" with a mapping "City"  which is of nested type. City has two properties "alias" and "someName". 

Say alias and someName both contain "bethany".

The following works: 

        $queryString = new QueryString();
        $queryString->setDefaultField('someName'); //using some name
        $queryString->setQuery('bethany');

        $nestedQuery = new Nested();
        $nestedQuery->setQuery($queryString);
        $nestedQuery->setPath('cities');

If I use the field "alias" instead of "someName" I will get no results, even though I can hit up elastic search directly and get accurate results by searching "bethany".

Are the fields "alias" and "name" ( I've also had the some trouble with using "name" as a field name ) problematic in elastica? 

Is this an issue?

**Comment by ruflin** [comment]
Closing as no updates were provided. Please reopen if needed.
