### ISSUE TITLE
Elastica/Transport/Http.php  curl_setopt($conn, CURLOPT_NOBODY, $httpMethod == 'HEAD');

### ISSUE THREAD

**Issue by sangxiaolong** [ruflin/Elastica#654]
when I try to make a POST request with the elastica client  to  ES server, it always return all documents, it seems that my query criteria doesn't work. but when I use the curl command it returns the filterd result what i want

after debuging for 2 hours i found it works if i comment this line of Elastica/Transport/Http.php

// curl_setopt($conn, CURLOPT_NOBODY, $httpMethod == 'HEAD');

see also these two questions:

http://stackoverflow.com/questions/9474971/php-curl-cannot-set-post-method/9475039
http://stackoverflow.com/questions/1091623/sending-post-data-with-curl-and-php/1091757

my php version 5.3.10
curl version 7.22.0 libcur/7.22.0

**Comment by ruflin** [comment]
Closing as no updates provided Please reopen if needed.
