### ISSUE TITLE
notice of setFields params array $fields must not modified or it will cause error

### ISSUE THREAD

**Issue by nickfan** [ruflin/Elastica#673]
setFields(array $fields) : \Elastica\Query

the array $fields must not be modified or it will cause error
```php
$myfields = array('id','name','text','title','_boost');
unset($myfields[2]);
$query->setFields($myfields);
```
will cause error, elastica will format $myfields into {"0":"id","1":"name","3":title}
you must make sure you pass the list as array not dict:
```php
$reqFields = array();
foreach($myfields as $field){
if($field!='text'){
$reqFields[]=$filed;
}
}
$query->setFields($reqFields);
```

**Comment by im-denisenko** [comment]
ES not expects dictionary as value of "fields", hence nobody should care about keys in this array.

I would propose following change to properly fix this issue:
```php
public function setFields(array $fields)
{
    return $this->setParam('fields', array_values($fields));
}

**Comment by ruflin** [comment]
Fine for me.

**Comment by ruflin** [comment]
@im-denisenko As far as I know, this suggested change was never pushed?

**Comment by ruflin** [comment]
Closing this issue as the "core" issue was address. For the suggestion of @im-denisenko please open a new issue or directly a PR.
