### ISSUE TITLE
Elastica\Query\Filtered does not have setSort() method

### ISSUE THREAD

**Issue by ilijastuden** [ruflin/Elastica#679]
ElasticSearch documentation has examples with sorted filtered queries here:

[http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/_sorting.html](http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/_sorting.html)

but there is no `setSort()` method in `Elastica\Query\Filtered` that lets me prepare such request.

**Comment by Tobion** [comment]
Closing as `Elastica\Query\Filtered` is not the right place to add sorting to.
