### ISSUE TITLE
PartialShardFailureException

### ISSUE THREAD

**Issue by digitalkaoz** [ruflin/Elastica#689]
i always get the following exception nowadays:

    Uncaught PHP Exception Elastica\Exception\PartialShardFailureException: "5"

my cluster health:

```json
{
cluster_name: elasticsearch
status: green
timed_out: false
number_of_nodes: 1
number_of_data_nodes: 1
active_primary_shards: 5
active_shards: 5
relocating_shards: 0
initializing_shards: 0
unassigned_shards: 0
}
```

all shards are "green"...so where is the problem exactly?

my elasticsearch version:

```json
{
status: 200
name: Human Top II
version: {
number: 1.3.4
build_hash: a70f3ccb52200f8f2c87e9c370c6597448eb3e45
build_timestamp: 2014-09-30T09:07:17Z
build_snapshot: false
lucene_version: 4.9
}
tagline: You Know, for Search
}
```

my installed versions:

friendsofsymfony/elastica-bundle     3.0.5
ruflin/elastica                      v1.3.0.0

any hints? if i look with the head plugin everything works regarding quering...

**Comment by ruflin** [comment]
Closing as no updates were provided in the last 5 months. Please reopen if new information comes up.
