### ISSUE TITLE
Disable PHP 5.3 and enable PHP 5.6 in travis build

### ISSUE THREAD

**Issue by ruflin** [ruflin/Elastica#696]
PHP 5.3 is EOL and PHP 5.6 is officially released.

**Comment by nickel715** [comment]
already done in 1c7c432a61ea6cb7620de6b8a94660e143027bc2?

Does the composer.json file also needs an update? In composer.json PHP 5.3 is still supported

**Comment by ruflin** [comment]
@nickel715 Good point, I switched it already for Travis. Until 2 days ago also all tests were still running with 5.3 and were green. I suggest we add 5.3 to travis again and see if it still builds and or what changes would be needed to make it build (I think it is only making some [] to array()). If it doesn't built anymore, we remove it.

**Comment by ruflin** [comment]
Both are now enabled for the travis builds. HHVM was also added.
