### ISSUE TITLE
Using both query string query with suggest in array form

### ISSUE THREAD

**Issue by omondiy** [ruflin/Elastica#706]
Hi All,

I am relatively new to elasticsearch and am trying to perform a search using the below query in php but I am getting an error.
		$query = array(
			'query' => array(
				'query_string' => array(
					'query' => "(name_en:cook)^2 OR  (name_en:door)  AND (_id:11)",
				)
			),
			'suggest' => array(
				'text' => "unganda",
				'term'=>array(
					"field"=> "name_en",
					"max_edits"=> 2,
					"sort"=> "score",
					"suggest_mode"=>"missing",
					"prefix_length"=> 0,
					"min_word_length"=> 2
				)
			)
		);
		$response = $client->request($path, \Elastica\Request::GET, $query);
		$responseArray = $response->getData();
		//print_r($responseArray['suggest']);
		// Loop through the results
		return $responseArray;
		diE();

The error is Fatal error: Uncaught exception 'Elastica\Exception\ResponseException' with message 'SearchPhaseExecutionException[Fai.........

Is this the correct way of doing it. Can some one tell me how to write this. I am following the example on http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-suggesters.html#search-suggesters.

Thanks in advance.

**Comment by ruflin** [comment]
Closing as no updates provided. Please reopen if needed.
