### ISSUE TITLE
Add request parameters to query

### ISSUE THREAD

**Issue by akorthaus** [ruflin/Elastica#720]
Hi!

To enable shard query caching per request, you have to append two parameters to the request URL, e.g.:
localhost:9200/my_index/_search?search_type=count&query_cache=true

Is it possible to append two parameters without using a "raw" request?

see: http://www.elasticsearch.org/guide/en/elasticsearch/reference/1.4/index-modules-shard-query-cache.html#_enabling_caching_per_request

Thank you!

best
Andreas

**Comment by ruflin** [comment]
Closing as I think this issue was resolved. Please reopen if needed.
