### ISSUE TITLE
Starting a New Port

### ISSUE THREAD

**Issue by CriztianiX** [ruflin/Elastica#758]
Hello... i am starting a  port your library for moonscript/lua.
The source can be viewed in https://github.com/CriztianiX/eluastica
Elastica is my favourite library for elasticsearch!
Great Job

**Comment by ruflin** [comment]
@CriztianiX Cool. Feel free to also put it under projects on Elastica.io http://elastica.io/projects/ If I can be of help in any way, let me know.

**Comment by CriztianiX** [comment]
@ruflin Thanks!!!...
Would be helpful , for the moment I am the only active developer

**Comment by ruflin** [comment]
I added your library here: http://elastica.io/projects/ I will close this issue as I think it is not an "issue" we can fix.
