### ISSUE TITLE
Documentation on website: wrong Composer name

### ISSUE THREAD

**Issue by sosso** [ruflin/Elastica#760]
Hi,

On your website:
![image](https://cloud.githubusercontent.com/assets/619968/5906363/d679c0d6-a54b-11e4-9889-b83d069f0c24.png)

I think it needs to be ruflin/elastica instead.  I tried capitalizing it per the website (ie I ran composer require ruflin/Elastica) but Composer didn't like it.

**Comment by ruflin** [comment]
I just checked what the FOSElastica Bundle is doing and they are also using lower case: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/composer.json#L20

**Comment by ruflin** [comment]
I just fixed it: http://elastica.io/getting-started/installation.html
