### ISSUE TITLE
setPostFilter has no upgrade path that doesn't spew deprecation warnings

### ISSUE THREAD

**Issue by nik9000** [ruflin/Elastica#763]
See:  https://phabricator.wikimedia.org/T76727

We can't deploy this library at the _exact_ same time as we deploy our code.  As is we have to call setPostFilter with an array before the upgrade and after the upgrade calling it with the array logs warnings.  We could work around it if we had some way to detect that PostFilter wants the filter instead of the array.  Any ideas?

**Comment by ruflin** [comment]
Ok, as far as I understood the main problem is the flodding of deprected messages and I assume disable this in PHP is not an option (something like error_reporting(E_ALL ^ E_DEPRECATED); )?

A more "crazy" method but probably also slow could be using the Reflection class and read out the function documentation as this one is quite different: 

http://php.net/manual/en/reflectionfunctionabstract.getdoccomment.php

**Comment by Nikerabbit** [comment]
FWIW, we have just forced uses to upgrade by dropping support for old version.

**Comment by ruflin** [comment]
@Nikerabbit Thanks for the update. I will close the issue in this case. Let me know in case it should be reopened.
