### ISSUE TITLE
Allow to specify script ID

### ISSUE THREAD

**Issue by bakura10** [ruflin/Elastica#776]
Hi,

Starting from ES 1.4.3, Groovy has been disabled by default so we cannot use it anymore with dynamic scripts (see: http://www.elasticsearch.org/blog/running-groovy-scripts-without-dynamic-scripting/).

The simplest solution currently is to create scripts using the REST endpoint, and specify a "script_id" instead of script. However Elastica currently forces having a script : https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Script.php#L113

I think it should now throw an exception only if neither script nor script_id is defined.

**Comment by ruflin** [comment]
@bakura10 Yes, it looks like we have to refactor this component to also make the new functionality available. As far as I understand it is still possible to pass dynamic scripts, but it has to be enabled first, right?

**Comment by bakura10** [comment]
Actually the problem seems to be far deeper (and honestly annoys me as I'm using script extensively). Actually the script_id suffers from the same restrictions and as I undersood it, the only way to use it is:

Either enable again scripting (but you are still vulnerable to the security issue)
Or you need to upload scripts in the node

In both cases, this is simply not possible when you use hosted elasticsearch :(. This means that for now, people using script must actually stay on 1.4.2 if they use dynamic script.

Or at least that's how I undersood it.

**Comment by ruflin** [comment]
The alternative would be to move to Sandboxed languages: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/modules-scripting.html

As the vulnerability is also in 1.4.2 I assume the hosters will also disable it there ...

**Comment by bakura10** [comment]
I asked compose (my hoster) and they confirmed me that for now they won't disable it (a lot of their customers rely on this, it would break apps very badly).

Which language is sandbox actually? I'm using expression scripts quite a lot but those cannot be used on things like update queries and are pretty limited :(

**Comment by ruflin** [comment]
@bakura10 I don't use the scripting myself so I'm not an expert here :-(

**Comment by d-claassen** [comment]
Any progress on using the script_id of a script stored in the /_script index?

**Comment by ruflin** [comment]
@nicolassing recently refactored Script and implemented FileScript: https://github.com/ruflin/Elastica/pull/902 I assume implementing on top of AbstractScript the _script id index should be possible. Instead of the scriptFile, the script id would be passed to the constructor. Can one of you two have a look at this? It would be nice to have it in Elastica.

**Comment by nicolassing** [comment]
@ruflin I've made a PR #920

**Comment by Tobion** [comment]
Closing as a ScriptId class exists now.
