### ISSUE TITLE
Independent Versioning of Elastica

### ISSUE THREAD

**Issue by ruflin** [ruflin/Elastica#789]
The versioning of Elastica currently depends on the version of Elasticsearch. An additional digit is added to the elasticsearch version to differentiate the different Elastica releases. This has the advantage that it is very easy visible to which elasticsearch release Elastica is compatible. This made a lot of sense in the beginning when elasticsearch was still changing on a daily based. In the meantime elasticsearch got more stable and BC breaks are less frequent.

In this issue it should be discussed, if Elastica should switch to its own semantic versioning, as this can also have advantages:
* Clear indication of BC breaks in Elastica through proper semantic versions indepndent of elasticsearch
* Proper semantic versioning (only 3 digits)
* ?

I would like to invite everyone to provide his opinion on this to decide if versioning should be changed in the future or not. 

@im-denisenko @merk @dbu @lsmith77

**Comment by merk** [comment]
I'm completely +1 on semantic versioning. 

I dont believe being linked to ElasticSearch's version makes all that much sense now that the API is more stable, but even then - using a MySQL 5.6 function through PDO on a 5.5 server will cause an exception. I'd expect the same from Elastica.

**Comment by lsmith77** [comment]
+1

**Comment by ruflin** [comment]
If we go with independent versioning, should we go to 2.0.0 or directly jump to 3.0.0. 3.* would make sure there is no confusion with Elasticsearch, which could also go soon to 2.0.0.

**Comment by dbu** [comment]
i am +1 on adopting semantic versioning. i can read up what version of ES Elastica is compatible with. but its much more critical - and likely when BC breaks inside Elastica happen. i would go with 2.0.0 (maybe take the oportunity to remove deprecated code first, if there is any). just state clearly in the README what versions of elasticsearch the current version is tested with.

**Comment by im-denisenko** [comment]
+1 for semver.
We could add table "ES version - Elastica version" to README and it's will be even more obvious way to say to developers, which version they should use, because almost all ES plugins do this like that.
Then no reason to jump directly to 3.0.0

**Comment by merk** [comment]
There isnt a hard link between Elastica's basic querying support and ElasticSearch versions, and you cant generally expect to use a feature in Elastica that isnt present in your ElasticSearch version.

It might make some sense to document methods added that have a minimum required ES version, but other than that I dont think theres much point documenting supported versions.

2.0 is fine, imo.

**Comment by ruflin** [comment]
Ok, based on the input of you guys I think the decision is obvious. I now created a 2.0.0 milestone (https://github.com/ruflin/Elastica/milestones/2.0.0) where we can move in all the issues that should go into version 2.0.0 and a 2.0.x branch (https://github.com/ruflin/Elastica/tree/2.0.x) to merge in all the changes.

If we already talk about version. What is your preferred way of calling branch and tag names? I checked several projects and it seems like every single on is different. 

For the release tags I see two options:
* v2.0.4
* 2.0.4

For the branches there are also several options
* 2.0.x
* 2.0
* v2.0.x
* v2.0

I'm sure I also missed some. Any thoughts on this?

**Comment by merk** [comment]
I'd keep your tag format the same as for the 1.x releases (with or without a v)

As for branches my personal opinion is 1.4, 2.0, 2.1, etc

**Comment by merk** [comment]
I'd be creating a 1.4 branch for maintenance of 1.4 and putting 2.0-dev into master personally though.

**Comment by ruflin** [comment]
@merk I was thinking again about the branches and I'm not even sure if it is needed. The branches are mainly needed if a long term release plan exists with specific features. This is less the case in Elastica as it is mainly driven by elasticsearch. So probably the branches are not even needed.

**Comment by merk** [comment]
Not normally for dev no - for example FOSElasticaBundle has 2 branches right now: master, for developing 3.1, and 3.0 for bug fix releases to 3.0 (which are merged into master occasionally).

I'd say with semver, Elastica would be similar.

**Comment by ruflin** [comment]
@dbu I was thinking about your input to introduce all BC changes with 2.0.0. I actually would suggest to go the other way around and don't introduce any major changes to make the migration as seamless as possible not to "loose" engineers on the old versions. After releasing 2.0.0 we have the possibility to use the semantic versioning to show the BC breaks and developers will get used to it.

**Comment by ruflin** [comment]
@merk Ok, I see. So far I never pushed "fixes" into older version. But in case there are major BC breaks I see why this could make sense.

**Comment by merk** [comment]
Using a deprecation cycle during 2.0 and removal in 3.0 could work. I have a few things that I hope to propose over the next few months that are going to probably need some big changes

**Comment by merk** [comment]
The way I like to work for development is to have a stable release branch where no new features go - but bug fixes do, and a development branch where new features go. It means you can have an extended testing period of a newer version.. No need to bump minor versions for bug fixes, just bump the patch version.

**Comment by dbu** [comment]
fully agree with @merk for the naming of branches and release tags.

about maintenance branches: if you tag a 1.4.0 and then make master branch-alias to 2.0.x-dev you can still checkout 1.4.0 and start a 1.4 branch from that later, if there is an important fix that you want to release as 1.4.1

and +1 for deprecating things in 2.0 and only removing in 3.0 if there is no big painpoints already.

and i agree its better to focus on having master work correctly than trying to support multiple legacy versions. its not like we have too many maintainers on this project and need to look for work ;-) and the current versions are pretty stable, so i don't expect it to happen all the time that people ask for updating older versions.

**Comment by dbu** [comment]
@merk in the OS projects i worked, we always had master be the current development version and kept a branch of the current stable version (i.e. 1.4). the win of that is that people see the latest dev version first.

for work larger projects, we use [git flow](http://nvie.com/posts/a-successful-git-branching-model/) which is exactly what you describe. i think it could make sense here as well, but you would need to make `develop` the default branch or you will see a lot of feature addition PRs be done from the stable version instead of develop.

**Comment by merk** [comment]
Sorry, I equate develop branch with master in my head - we're on the same page :)

**Comment by ruflin** [comment]
@dbu I also use git flow in larger projects but I think here it is overkill.

**Comment by ruflin** [comment]
Implemented.
