### ISSUE TITLE
Invalid transport 

### ISSUE THREAD

**Issue by gcleaves** [ruflin/Elastica#792]
Hello,

I've moved my PHP/Elastica project to an AWS instance and am now receiving an error that I don't understand.  Can you please help?  The code works well on my machine and from a docker image.  I'm using the same docker image on AWS.  (I thought docker was supposed to avoid these problems :( )

Type: Elastica\Exception\InvalidException
Message: Invalid transport
File: /usr/share/nginx/html/vendor/ruflin/elastica/lib/Elastica/Transport/AbstractTransport.php
Line: 95
Trace

#0 /usr/share/nginx/html/vendor/ruflin/elastica/lib/Elastica/Connection.php(192): Elastica\Transport\AbstractTransport::create('http', Object(Elastica\Connection))
#1 /usr/share/nginx/html/vendor/ruflin/elastica/lib/Elastica/Request.php(165): Elastica\Connection->getTransportObject()
#2 /usr/share/nginx/html/vendor/ruflin/elastica/lib/Elastica/Client.php(603): Elastica\Request->send()
#3 /usr/share/nginx/html/vendor/ruflin/elastica/lib/Elastica/Search.php(443): Elastica\Client->request('adserver_stats_...', 'GET', Array, Array)
#4 /usr/share/nginx/html/vendor/ruflin/elastica/lib/Elastica/Index.php(294): Elastica\Search->search()
#5 /usr/share/nginx/html/classes/AdServerQuery.php(86): Elastica\Index->search(Object(Elastica\Query))
#6 /usr/share/nginx/html/classes/AdServerQuery.php(65): Billy\AdServerQuery->_conversionQuery('conversions')
#7 /usr/share/nginx/html/include/adserverRoutes.php(77): Billy\AdServerQuery->conversionsQuery()
#8 [internal function]: {closure}('2015-02-22 00:0...', '2015-02-23 23:5...')
#9 /usr/share/nginx/html/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#10 /usr/share/nginx/html/vendor/slim/slim/Slim/Slim.php(1338): Slim\Route->dispatch()
#11 /usr/share/nginx/html/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#12 /usr/share/nginx/html/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#13 /usr/share/nginx/html/vendor/slim/extras/Slim/Extras/Middleware/HttpBasicAuth.php(85): Slim\Middleware\MethodOverride->call()
#14 /usr/share/nginx/html/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Extras\Middleware\HttpBasicAuth->call()
#15 /usr/share/nginx/html/vendor/slim/slim/Slim/Slim.php(1283): Slim\Middleware\PrettyExceptions->call()
#16 /usr/share/nginx/html/index.php(102): Slim\Slim->run()
#17 {main}

**Comment by im-denisenko** [comment]
Problem is, that `http` is not valid transport. Should be `Http`. Could you show how exactly you create `Elastica\Client` instance?

**Comment by gcleaves** [comment]
Here is how I create the client.  It works on my dev laptop.
        
    return new Client(array(
            'host' => 'kibana.billysrv.com',
            'transport' => 'http',
            'headers' => $authHeader,
            'port' => 80
        ));

**Comment by gcleaves** [comment]
I've capitalised Http 

    return new Client(array(
        'host' => 'kibana.billysrv.com',
        'transport' => 'Http',
        'headers' => $authHeader,
        'port' => 80
    ));

and the problem has gone away.  Many thanks!

**Comment by ruflin** [comment]
Seems like you had before a case insensitive file system. I will close this. Please reopen if you need further help.
