### ISSUE TITLE
QueryBuilder not generating the right match query

### ISSUE THREAD

**Issue by BitOne** [ruflin/Elastica#796]
Hello,

It seems that the QueryBuilder, when asked to generate a match() query, doesn't generate the right DSL.

```php
query->setQuery(
    $qb->query()->match("description", "processor");
);
```
will generate the following Elasticsearch JSON:
```json
{
    "query":{
        "match":{
            "field": {
                "description-en_US-print":"processor"
            }
        }
    }
}
```
Which is the wrong syntax, as the match query should be:
```json
{
    "query":{
        "match":{
            "description-en_US-print":"processor"
        }
    }
}
```
as defined here: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-match-query.html#query-dsl-match-query

The problem seems to come from the QueryBuilder code:
https://github.com/ruflin/Elastica/blob/master/lib/Elastica/QueryBuilder/DSL/Query.php#L67

When replacing the following line:
```php
$match->setFieldParam('field', $field, $value);
```
by
```php
$match->setParam($field, $value);
```
the resulting syntax is correct and the query works well.

What do you think guys ? Is there something I'm doing wrongly or there's a problem with the QueryBuilder DSL Query part for the match query ?

Thanks !

**Comment by ruflin** [comment]
@webdevsHub Can you have a look here?

**Comment by webdevsHub** [comment]
definitely a bug! plx see #798

thx for reporting @BitOne
