### ISSUE TITLE
Documentation : Use of curl_exec

### ISSUE THREAD

**Issue by gourlaa** [ruflin/Elastica#800]
Hi,

I am running elastica search in local, so why this Elastica Bundle need a curl_exec function ? It's not secure to give access to curl exec.

PHP Warning:  curl_exec() has been disabled for security reasons in /home/httpd/www/api/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php on line 128.

Thank

**Comment by ruflin** [comment]
@gourlaa Without curl Elastica will not work, as Elastica must connect to the elasticsearch server and that happens through curl. I don't really see an alternative here.

**Comment by ruflin** [comment]
Closing as unclear if further steps are needed.
