### ISSUE TITLE
setFieldBoost in Match Query doesn't work.

### ISSUE THREAD

**Issue by Defgenx** [ruflin/Elastica#801]
I use the Match Query of the FOSElasticaBundle and try to use the method setFieldBoost(), but it returns the following error:

ErrorHandler ->handleError ('2', 'Illegal string offset 'boost'', '/my/path/to/vendors/vendor/ruflin/elastica/lib/Elastica/Query/Match.php', '45', array('field' => 'EVENEMENT_NOM', 'key' => 'boost', 'value' => '100', 'this' => object(Match)))

I think that the problem is that the boost value became a string but it should be a float or an int. But I don't know if it's the real reason. Boost in this query type is still supported in ES ; it's written in the documentation.

It works well with the Regexp Query or QueryString.

**Comment by ruflin** [comment]
The boost value "should" be automatically converted to a float if it is not the case. Check here: https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Query/Match.php#L109

Can you post some more of your code to see what kind of params you put in? I just checked the tests and unfortunately there is no implementation test for setFieldBoost, only a unit test.

**Comment by ruflin** [comment]
I just added two tests to check for the setFieldBoost function with and without a float, both seems to work: https://github.com/ruflin/Elastica/commit/a163767b78052647a74afc187afb38e9fb60db60

Seems like we need to hunt the error somewhere else.

**Comment by Defgenx** [comment]
So here is my code:
1/ The error comes when I tried this
$queryString = new \Elastica\Query\Match();
$queryString->setField('EVENEMENT_NOM', Util::escapeTerm($search));
$queryString->setFieldBoost('EVENEMENT_NOM', 103.0);

2/ No exception with this second code, but no boost is added.
$queryString = new \Elastica\Query\Match();
$queryString->setFieldBoost('EVENEMENT_NOM', 103.0);
$queryString->setField('EVENEMENT_NOM', Util::escapeTerm($search));

In my second example, I think the setField() erase the setFieldBoost() call.

If it works fine with float and string, the error might be in the setFieldParam() call from the setFieldBoost() method. Look the stack trace from my Symfony instance:
Match ->setFieldParam ('EVENEMENT_NOM', 'boost', '103')
in vendor/ruflin/elastica/lib/Elastica/Query/Match.php at line 109

And it point out that part of the code:
![elastica_boost_match](https://cloud.githubusercontent.com/assets/10920570/6730041/b40abed6-ce38-11e4-8adc-0114f2764bd4.PNG)

I'll take a look when I go back home.

**Comment by ruflin** [comment]
setField is actually only a proxy for setParam as you can see here: https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Query/Match.php#L26

I can see that this could be confusion and I don't think the setField function is really needed, but removing it would now mean making some BC breaks.
