### ISSUE TITLE
Elasticsearch 1.5

### ISSUE THREAD

**Issue by im-denisenko** [ruflin/Elastica#812]
- [x] Update required ES version in travis build
- [x] [Memcached and thrift transports are deprecated](https://github.com/elastic/elasticsearch/pull/10167)
- [x] [Delete by query api is deprecated](https://github.com/elastic/elasticsearch/pull/10082)
- [x] [More like this field query is deprecated](https://github.com/elastic/elasticsearch/pull/8253)
- [x] Add new Version class for query builder
- [x] [Deprecated offset-related options in date histogram aggregation](https://github.com/elastic/elasticsearch/pull/9614)
- [x] [Deprecated timezone-related options in date histogram aggregation](https://github.com/elastic/elasticsearch/pull/9722)
- [x] [New option in function score query](https://github.com/elastic/elasticsearch/pull/7814)
- [x] [New option in query string query](https://github.com/elastic/elasticsearch/pull/8164)
- [x] [Removed option in query string query](https://github.com/elastic/elasticsearch/pull/10086)
- [ ] [Support for artificial documents in mlt query](https://github.com/elastic/elasticsearch/pull/7725)
- [ ] [Support for inner hits](https://github.com/elastic/elasticsearch/pull/8153)
- [ ] [New option in numeric metric aggregations](https://github.com/elastic/elasticsearch/pull/9032)
- [ ] [Multiple order criteria in terms aggregation](https://github.com/elastic/elasticsearch/pull/7662)
- [x] [New option in mlt query](https://github.com/elastic/elasticsearch/pull/7898)
- [x] [New option in simple_query_string](https://github.com/elastic/elasticsearch/pull/9864)

**Comment by hugohenrique** [comment]
@ruflin @im-denisenko You already imagined how it would implement to support the inner hits results?
How can I help?

**Comment by im-denisenko** [comment]
@hugohenrique I have not worked on this yet.

> How can I help?

You could provide easy-to-understand example of how this feature should work.
Pull requests are welcomed as well :)

**Comment by joshuataylor** [comment]
Inner hits are awesome, as they allow you to query a docset and get back the relevant children easily.

May not be the best example, but an example would be...

Let's say I have a simple document called 'product', with nested documents called 'variations', which might have fields such as 'size', 'color', 'price', etc, you could use inner_hits to get just certain color/sizes. It's excellent.

**Comment by ruflin** [comment]
Does anyone have some time to open a pull request with the feature?

**Comment by joshuataylor** [comment]
@ruflin I will have a look over the weekend, as this is a killer feature for me personally and would love for this to be in (due to time restraints we resorted to nasty arrays :-1: ), so to help contribute back I'll look into it.

**Comment by ruflin** [comment]
:+1:

**Comment by ruflin** [comment]
Closing this one even though some points are still open. By now we support 2.0 and we implement the open features above when requested. Please reopen if you disagree.
