### ISSUE TITLE
The library is incompatible with PHP 7 because of reserved class names

### ISSUE THREAD

**Issue by stof** [ruflin/Elastica#825]
``Bool`` is reserved in PHP 7. See https://travis-ci.org/Seldaek/monolog/jobs/60151678 for example

You can have a look at https://github.com/symfony/symfony/pull/14228 to see how Symfony will handle it with a BC layer on PHP 5

**Comment by ruflin** [comment]
I also planned to look into this "soonish". Did you already try to run it with PHP 7? We should also create a list with the things that must be adjusted.

**Comment by stof** [comment]
Well, Monolog runs its own testsuite against PHP 7 on Travis, and it has an integration with Elastica which broke the testsuite. See the link above.

The easy way to spot PHP 7 incompatibilities would be to enable testing on PHP 7 on Travis.

**Comment by ruflin** [comment]
Thanks for the pull request. I wasn't aware that Travis already supports PHP 7.

**Comment by ruflin** [comment]
It is probably best to follow the suggestion of @im-denisenko concerning the naming in #826. @stof Is Null also affected? 

What we could do to keep it BC is to set BoolFilter as the base class and use it across all the client library. But keep the Bool class which extends Bool*. So it will never actively used in the library itself but "could" be used before PHP 7. I'm not sure if PHP 7 will complain also if it is not called.

**Comment by ruflin** [comment]
Pull request opened: https://github.com/ruflin/Elastica/pull/837

http://php.net/manual/en/reserved.other-reserved-words.php

**Comment by stof** [comment]
@ruflin if it is never used, PHP 7 will not complain (as the file won't be loaded)

**Comment by ruflin** [comment]
@stof That is what I assume. It is time to get a local PHP 7 environment running for testing this stuff. Which docker or vagrant images are you using for php7?

**Comment by stof** [comment]
I don't have a PHP 7 setup yet. I relied on Travis until now.

**Comment by digitalkaoz** [comment]
you could go with rasmus box https://github.com/rlerdorf/php7dev

**Comment by ruflin** [comment]
@digitalkaoz Thx for the link. Will try it out.  There are also some Docker images available: https://registry.hub.docker.com/search?q=php7&searchfield=

**Comment by im-denisenko** [comment]
Fixed via #826, #837, #868
