### ISSUE TITLE
Scroll does not respect ordered results by default

### ISSUE THREAD

**Issue by hasumedic** [ruflin/Elastica#827]
According to elasticsearch's documentation:
http://www.elastic.co/guide/en/elasticsearch/reference/1.5/search-request-scroll.html#scroll-scan
> "Normally, you just want to retrieve all results and the order doesn’t matter. Scrolling can be combined with the scan search type to disable any scoring or sorting and to return results in the most efficient way possible. All that is needed is to add search_type=scan to the query string of the initial search request:"

I understand that this means that scoring and sorting are being taken into account by default.

This conflicts with the current implementation of the ScanAndScroll.php class, where the first query to obtain the "scroll_id" is made:

```php
    /**
     * Start the initial scan search
     * @link http://php.net/manual/en/iterator.rewind.php
     * @throws \Elastica\Exception\InvalidException
     * @return void
     */
    public function rewind()
    {
        $this->_search->getQuery()->setSize($this->sizePerShard);

        $this->_search->setOption(Search::OPTION_SEARCH_TYPE, Search::OPTION_SEARCH_TYPE_SCAN);
        $this->_search->setOption(Search::OPTION_SCROLL, $this->expiryTime);

        // initial scan request
        $this->_setScrollId($this->_search->search());

        // trigger first scroll request
        $this->_scroll();
    }
```

I would think that the setOption for the search type should be optional and default to none.

Am I missing something? I'm fairly new to this repository, but if I can get some pointers on how this could be fixed without breaking BC I'm more than happy to do a PR.

**Comment by hasumedic** [comment]
After few stabs at the problem (#828), I think I came to the conclusion that what's actually happening is that the library is missing the implementation of Scroll all together. Scroll and Scan-Scroll are different things, with different behaviours, meanings and results.

**Comment by webdevsHub** [comment]
That is correct: `ScanAndScroll` class is dedicated to http://www.elastic.co/guide/en/elasticsearch/guide/current/scan-scroll.html and should be used to reindex or export whole indexes (see https://github.com/ruflin/Elastica/pull/617#issuecomment-43440568)

I could not see any advantage of using `scroll` over `from`, `size` with normal queries when I wrote the Iterator, but actually it offers some few advantages:

* faster (Quote: "The scroll API keeps track of which results have already been returned and so is able to return sorted results more efficiently than with deep pagination")
* retryable (send an old scroll id to get the old results)
* removable context (useless in my opinion)

So a new Iterator should focus on these advantages only. It could store previous scroll ids and offer a retry function with time checks (is the scroll still open?) without sending a query. It could also act as the base class for `ScanAndScroll` without breaking BC

**Comment by webdevsHub** [comment]
Turns out the "retryable" assumption was wrong: It is not, so the whole `return $_lastScrollId` in `ScanAndScroll` is basically useless.

While figuring this out I found a couple of other bad things and started coding new `Scroll` and `ScanAndScroll` classes.

@hasumedic Do you mind if I take on at this point?

**Comment by hasumedic** [comment]
Hey @webdevsHub, no worries. I was planning to work on this tomorrow and Friday, but if you're on it already I'll be working on other PRs then :)

**Comment by webdevsHub** [comment]
Fixed in https://github.com/ruflin/Elastica/issues/842
