### ISSUE TITLE
Util method - is this an issue or am i missing something?

### ISSUE THREAD

**Issue by virtuman** [ruflin/Elastica#830]
Here's a method in Util.php:
```
    public static function reindex(Client $client, $newIndex, $oldIndex, $expiryTime = '1m', $sizePerShard = 1000)
    {
        $search = new Search($client);
        $oldIndex = new Index($client, $oldIndex);
        $newIndex = new Index($client, $newIndex);
        
        $bulk = new Bulk($client);
        $bulk->setIndex($newIndex);
                
        $search->addIndex($oldIndex);
        $search->setOption(Search::OPTION_SEARCH_TYPE, Search::OPTION_SEARCH_TYPE_SCAN);
        $scanAndScroll = new ScanAndScroll($search, $expiryTime, $sizePerShard);
        foreach ($scanAndScroll as $resultSet) {
            $data = $resultSet->getResponse()->getData();
            foreach ($data['hits']['hits'] as $d) {
                $meta = array('_index' => $newIndex->getName() , '_type' => $d['_type'], '_id' => $d['_id']);
                $actions[] = new Action(Action::OP_TYPE_INDEX, $meta ,$d['_source']);
            }
            //$actions = new Bulk\Action();
            $bulk->addActions($actions);
            $bulk->send();
        }
        $newIndex->refresh();
        return "reindex complete";
    }
```

Lines of interest here are:
```
        foreach ($scanAndScroll as $resultSet) {
            $data = $resultSet->getResponse()->getData();
            foreach ($data['hits']['hits'] as $d) {
                $meta = array('_index' => $newIndex->getName() , '_type' => $d['_type'], '_id' => $d['_id']);
                $actions[] = new Action(Action::OP_TYPE_INDEX, $meta ,$d['_source']);
            }
            //$actions = new Bulk\Action();
            $bulk->addActions($actions);
            $bulk->send();
        }
```

$actions container here seems to be constantly appended to during all scanandscroll + hits iteration.
Wouldn't this result in results doubling up on each iteration, ie:
1. scanAndScroll is set to select 10 entries from each of 5 shards
2. during first iteration $actions will become container for 50 docs
3. addActions and send() will push these products to newIndex
4. during second iteration $actions will get another 50 added to it and will now become a container for 100 docs
5. addActions and send() will now push all 100 products
6. ... same repeats until the end resulting in $actions to hold entire dataset that was being selected by scanAndScroll to avoid out of memory issues

granted it's not an issue with documents doubling up because _id is set explicitly on each iteration, but to my understanding $actions should be reset within scanAndScroll foreach loop?

**Comment by ruflin** [comment]
@xwei3752 Can you give some insights here as you implemented this?

**Comment by virtuman** [comment]
haven't implemented it, just looked at the code as an example.

**Comment by ruflin** [comment]
@virtuman That is why I mentioned @xwei3752 who implemented it in https://github.com/ruflin/Elastica/pull/829

**Comment by webdevsHub** [comment]
There are several problems with that function in my opinion. The missing `$actions` cleanup is a good catch :+1: 

`$actions = array();` before the second `foreach` would fix that.

or just add actions on the fly 

```php
$bulk = new Bulk($client);
foreach ($data['hits']['hits'] as $d) {
    $bulk->addAction(new Action(Action::OP_TYPE_INDEX, $meta ,$d['_source']));
}
$bulk->send();
```

Another problem with that function: it assumes that both indexes uses to same client. So you cannot reindex from one cluster to another. To fix that I would change the definition to:

```php
public static function reindex(Index $newIndex, Index $oldIndex, $expiryTime = '1m', $sizePerShard = 1000) 
{
    $search = new Search($oldIndex->getClient());
    $bulk = new Bulk($newIndex->getClient());
    // ...
}
```

And finally that `return "reindex complete";`. Maybe the intention was to output that string somewhere but I think a return type `bool` or `void` (there are only Exceptions in case of an error anyway) would be better.

**Comment by xwei3752** [comment]
@virtuman its my fault,it should be init before loop.thx
@webdevsHub thanks for your suggestion,modified
[#831](https://github.com/ruflin/Elastica/commit/fdee0c6ba6f9aaa7266064c77fb6ea9d3aa0393f)

**Comment by ruflin** [comment]
I merged the changes. What I will change is the return type to bool and return true.

**Comment by ruflin** [comment]
@virtuman @webdevsHub @xwei3752 What do you think about the order of the params? I would intuitively put the old index first and then the new index. The second thing is: Is this really reindex? Isn't this copy?

**Comment by webdevsHub** [comment]
> old index first and then the new index

:+1:

> Is this really reindex? Isn't this copy?

The current implementation is more copy then reindex. Maybe rename that function to `copy` and create a new `reindex` function that checks and creates the mapping in new index before copying the data.

**Comment by ruflin** [comment]
Suggestion: I switch the params and rename the function to copy. In a new issue we discuss what reindex actually is. 

@virtuman As you are using this in one of your applications I assume your input would be more then welcome here. And as you are based on master, you will have to rename your implementation. I will rename it before the next release so we wont have any BC breaks.

**Comment by ruflin** [comment]
Pull request can be found here: https://github.com/ruflin/Elastica/pull/836

Some more thoughts: I also changed the return to the new index. That is what I would expect in case I want to chain some commands together. Most of the time I probably want to work on the new index.

For the reindex functionality: The link provided by @xwei3752 describes very well what other functionality is needed. Copy is really taking a full index and copy the data to an other index. Reindexing can start at a certain criteria as it is mentioned in the documentation. I see copy as a sub function of reindexing as reindexing is more complex.

**Comment by webdevsHub** [comment]
> The simplest way to apply these changes (add new analyzers or make changes to existing fields) to your existing data is to reindex ... [link](http://www.elastic.co/guide/en/elasticsearch/guide/master/reindex.html)

`reindex` copies all documents but **not** the mapping. So the current implementation is actually `reindex` and `copy` would be a parent function to `reindex`, because `copy` includes mappings.

> Reindexing can start at a certain criteria as it is mentioned in the documentation

I think this section is about continuous reindexing (replication with different mappings). But you are right: the current implementation behaves more like full copy.

Here a possible solution:

I would rename the function back to `reindex` and add an optional `$query` parameter:

```php
public static function reindex(Index $oldIndex, Index $newIndex, AbstractQuery $query = null, $expiryTime = '1m', $sizePerShard = 1000)
{
    $search = new Search($oldIndex->getClient());
    $search->setQuery($query);
    // ...
}
```
After that add a new function `copy`:

```php
public static function copy(Index $oldIndex, Index $newIndex, $expiryTime = '1m', $sizePerShard = 1000)
{
    // copy mapping
    foreach ($oldIndex->getMapping() as $type => $properties) {
        $type = new Type($newIndex, $type);

        $mapping = new Mapping($type, $properties);
        //$mapping->setParam('ignore_conflicts', true); // ???
        $mapping->send();
    }

    // copy documents
    self::reindex($oldIndex, $newIndex, new MatchAll(), $expiryTime, $sizePerShard);
}
```

**Comment by ruflin** [comment]
Looks good. For reindex I'm not sure if the third parameter should be an array that covers all the optional params. I'm quite sure more params will follow. Do you have some time today to open a pull request with this? Like this I could get it into the 2.0.0 release. The other option is I remove it again from the 2.0.0 release and we readd it afterwards.

**Comment by ruflin** [comment]
I removed it for the 2.0.0 release as I really wanted to get this out the door. The "old" code can be found here: https://github.com/ruflin/Elastica/tree/reindex-and-copy

**Comment by webdevsHub** [comment]
> I removed it for the 2.0.0 release

:+1: there is no hurry

I am going to create 2 pull requests regarding `Scroll` + `ScanAndScroll` (see https://github.com/ruflin/Elastica/issues/827) and `copy` + `reindex`

**Comment by ruflin** [comment]
About the ignore_conflict: We should not ignore it as the copy assumes $newIndex is an index which does not exist yet and has not mapping / data yet. So a conflict should never happen. If one happens, it should raise an exception.

**Comment by ruflin** [comment]
Looking forward to it :-)
