### ISSUE TITLE
Rethink Elastica Support Forum

### ISSUE THREAD

**Issue by ruflin** [ruflin/Elastica#835]
Currently Elastica support questions should be posted in the Elastica Google Group: https://groups.google.com/forum/#!forum/elastica-php-client Only few questions end up here. Some questions are posted as an Issue on Github or most of the questions end up on Stackoverflow: http://stackoverflow.com/search?q=elastica

I suggest not to mix Github issues which are for bugs and support questions. Where should Elastica questions go to in the future? As most of the questions go to Stackoverflow already, it could make sense to direct engineers to Stackoverflow directly instead of the Google Groups.

@im-denisenko @webdevsHub Any thoughts?

**Comment by webdevsHub** [comment]
I prefer Stackoverflow too. There is already a tag for Elastica: http://stackoverflow.com/tags/elastica/info. One can follow tags on Stackoverflow, so would be easy to overview all questions.

We could just add a new header to README.md like:

Support
------------
Please ask any question about Elastica on [stackoverflow.com](http://stackoverflow.com) and tag it with [\[elastica\]](http://stackoverflow.com/tags/elastica/info) to get an answer from Elastica contributors or other users.

We could add a FAQ document to the repository based on questions on stackoverflow later on.

**Comment by im-denisenko** [comment]
I think no matter if there will be google group, standalone site, mailing list or something else - people always will use SO, as well as github's issues.

Hence I vote for SO too, with a little concern: most of the answers I've seen about Elastica is outdated and were written long ago. Is there any chance to assign a certain moderator for tag to have possibility edit questions and answers?

**Comment by webdevsHub** [comment]
There is no tag moderation AFAIK. Moderation is done by reputation and voting. Which is fine in my opinion. So we should add better answers to the question and vote it up.

I think there are several "internal" tasks to organise like "who wants to answer a question" or in general thinks like "someone should have a look into that reddit discussion" or new ideas or whatever.

ruflin could start a https://trello.com/ board for contributors. It is free and easy to use

**Comment by ruflin** [comment]
So we agree to Stackoverflow. The question is now how to "organise" it. I haven't used Stackoverflow too much in the past. Does someone of you have a "high" reputation?

As Elastica is an open source project the question is how much "tools" should be used for organizing it. The less tools the better. So I'm not 100% sure if Trello would not just be a tool we use in the first 2-3 months and then is more or less dead. Should we use a good old IRC channel so also other people could ask questions directly there?

One thing I tried to for some time but never suceeded in the long run is the build a "foundation" team around Elastica. So we have several people that push it forward, can merge pull requests and also make releases. @webdevsHub @im-denisenko What do you think?

**Comment by webdevsHub** [comment]
> Does someone of you have a "high" reputation?

No, I am a read only user too. But SO does a really good job in finding the correct solution and with enough reputation you can even edit answers from different users (if none of us can do that: one could add a comment to the outdated answer at least)

> Should we use a good old IRC channel ...?

I am fine with IRC as a starting point. But it could turn out to be less useful then Trello in organizing stuff because IRC usually has no history.

>  build a "foundation" team around Elastica

I appreciate the fact that you want to give me write permission in Elastica. It would be a great pleasure for me to be a project maintainer of this awesome library :smile:

**Comment by im-denisenko** [comment]
> So we agree to Stackoverflow. The question is now how to "organise" it. I haven't used Stackoverflow too much in the past. Does someone of you have a "high" reputation?

I don't have SO account at all. But i'm pretty sure that there is possibility to subscribe to tag, get new questions to email and answer to them at free time, if it still has no answer.

> As Elastica is an open source project the question is how much "tools" should be used for organizing it. The less tools the better. So I'm not 100% sure if Trello would not just be a tool we use in the first 2-3 months and then is more or less dead. Should we use a good old IRC channel so also other people could ask questions directly there?

I would suggest use [Gitter](https://gitter.im). It's like IRC with new shiny interface, but has history, markdown and github integration. At least, I've seen that some open source projects already adapt it, for example: [Laravel](https://gitter.im/laravel/laravel), [Codeception](https://gitter.im/Codeception/Codeception), [etc](https://gitter.im/explore/). Also it has [badge](https://badges.gitter.im/Join%20Chat.svg). More badges for badges god!

> One thing I tried to for some time but never suceeded in the long run is the build a "foundation" team around Elastica. So we have several people that push it forward, can merge pull requests and also make releases.

Sure, i'll be very pleased to be involved in something like that.

**Comment by ruflin** [comment]
Here is an Elastica Chat Room: https://gitter.im/ruflin/Elastica I never used Gitter but lets try it out

**Comment by ruflin** [comment]
@webdevsHub @im-denisenko I added you both as collaborators to the project. You should now also be able to merge pull requests. With power comes responsibility ;-)

**Comment by ruflin** [comment]
The open point we still have is SO. It seems all three of us are not very active on SO means we have almost no reputation. The easiest one to gain reputation is answering old questions and especially the new ones. I will try to watch for questions on SO a little bit more so I get the chance to answer the new questions...

**Comment by im-denisenko** [comment]
> I added you both as collaborators to the project. You should now also be able to merge pull requests. With power comes responsibility ;-)

@ruflin Thanks. Hope my help will be useful :)

**Comment by ruflin** [comment]
@im-denisenko Always was and will be ;-)

**Comment by ruflin** [comment]
I started to answer some answers on SO and we use gitter. Closing as I think a larger changes is not feasible.
