### ISSUE TITLE
PHP 7 issue with phpunit and DEBUG constant

### ISSUE THREAD

**Issue by ruflin** [ruflin/Elastica#861]
PHP 7 in combination with phpunit and a constant named DEBUG leads currently to the following output:

```
make: *** [phpunit] Segmentation fault
```

This is cause by the constant DEBUG which is used for the test environment: https://github.com/ruflin/Elastica/blob/master/test/phpunit.xml.dist#L27-L29

If the variable is renamed, the problem disappears.

Currently I'm not sure if this issue is cause by phpunit or PHP 7. I assume there is some name conflict. In all versions before PHP 7 it works without any issues. One solution is to rename the constant and make it ELASTICA_DEBUG to adjust it to make it namespace specific.

**Comment by ruflin** [comment]
@webdevsHub @im-denisenko I need some fresh eyes here. Do you know about any "know" bug or issue why PHP 7 / phpunit and a constant "DEBUG" crashes everything?

**Comment by webdevsHub** [comment]
I have no experience in PHP 7, maybe @sebastianbergmann can help? Would be nice!

**Comment by sebastianbergmann** [comment]
`DEBUG` is not used by PHPUnit (or any of its dependencies). I'm afraid there's not much debugging I (or a PHP core dev) can do without a minimal, self-contained, reproducing script.

**Comment by ruflin** [comment]
I will try to get a minimal script together to reproduce this.

**Comment by im-denisenko** [comment]
Well. DEBUG constant it's not a real problem. It seems like curl is broken in certain cases.

It's why segfault happens at low level:
* When DEBUG is setted, Elastica\Util::debugEnabled will return true.

* Elastica\Transport\Http will set additional option to curl handler [here](https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Transport/Http.php#L134). 

* After that, curl_getinfo [here](https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Transport/Http.php#L155) will return key "request_header". 

* This key will be added to result array [here](https://github.com/php/php-src/blame/master/ext/curl/interface.c#L3011).

* ch->header.str is a pointer to zend_string, as defined [here.](https://github.com/php/php-src/blob/master/ext/curl/php_curl.h#L167)

* Segmentation fault means that this pointer is null at some time when it must not.

* As defined [below](https://github.com/php/php-src/blob/master/ext/curl/interface.c#L3017), when curl_getinfo called with second argument, it returns copy of pointer, not pointer itself.

* This segfault can be fixed, if [line 3011](https://github.com/php/php-src/blob/master/ext/curl/interface.c#L3011) will be updated:

    ```
    CAASTR("request_header", zend_string_copy(ch->header.str));
    ```

**Comment by im-denisenko** [comment]
What a real problem, is that I can't understand and explain how to reproduce this error.

It's why segfault happens at higher level:

* Must be at least two functional tests.

* Regardless of results of first test, tearDown will delete all indices in ES. It means that Elastica\Transport\Http::exec will be called at least once. Right now it'll be successfull.

* Second test must throw an exception inherited from PHPUnit_Framework_Exception. In our case, it happens when we call markTestSkipped. After that, tearDown will delete all indices in ES (again Elastica\Transport\Http::exec).

* Segmentation fault in the curl_getinfo.

**Comment by im-denisenko** [comment]
There is also some kind of magic with exceptions.

This is segfault:
```
public function testExample()
{
    self::markTestSkipped();
}
```

And this is segfault:
```
public function testExample()
{
    throw new \PHPUnit_Framework_SkippedTestError();
}
```

And this is segfault:
```
public function testExample()
{
    try {
        self::markTestSkipped();
    } catch (\PHPUnit_Framework_SkippedTestError $ex) {
        throw $ex;
    }
}
```

But this is **works fine**:
```
public function testExample()
{
    try {
        self::markTestSkipped();
    } catch (\PHPUnit_Framework_SkippedTestError $ex) {
        throw new \PHPUnit_Framework_SkippedTestError();
    }
}
```

**Comment by im-denisenko** [comment]
Minimal code required to reproduce this error with elastica:
```php
define('DEBUG', true);
$client = new Elastica\Client(['host' => 'elasticsearch', 'port' => 9200]);
$index = $client->getIndex('foobar');
$index->create(array(), true);
$index->refresh();
$index->count();
```

**Comment by im-denisenko** [comment]
As temporary workaround, we can add this method to `Elastica\Transport\Http`:
```php
/**
 * @see https://github.com/ruflin/Elastica/issues/861
 * @return array
 */
protected function _curlGetInfo($ch)
{
    if (version_compare(phpversion(), 7, '<')) {
        return curl_getinfo($ch)
    }

    return [
        'url' => curl_getinfo($ch, CURLINFO_EFFECTIVE_URL),
        'content_type' => curl_getinfo($ch, CURLINFO_CONTENT_TYPE),
        'http_code' => curl_getinfo($ch, CURLINFO_HTTP_CODE),
        'header_size' => curl_getinfo($ch, CURLINFO_HEADER_SIZE),
        'request_size' => curl_getinfo($ch, CURLINFO_REQUEST_SIZE),
        'filetime' => curl_getinfo($ch, CURLINFO_FILETIME),
        'ssl_verify_result' => curl_getinfo($ch, CURLINFO_SSL_VERIFYRESULT),
        'redirect_count' => curl_getinfo($ch, CURLINFO_REDIRECT_COUNT),
        'total_time' => curl_getinfo($ch, CURLINFO_TOTAL_TIME),
        'namelookup_time' => curl_getinfo($ch, CURLINFO_NAMELOOKUP_TIME),
        'connect_time' => curl_getinfo($ch, CURLINFO_CONNECT_TIME),
        'pretransfer_time' => curl_getinfo($ch, CURLINFO_PRETRANSFER_TIME),
        'size_upload' => curl_getinfo($ch, CURLINFO_SIZE_UPLOAD),
        'size_download' => curl_getinfo($ch, CURLINFO_SIZE_DOWNLOAD),
        'speed_download' => curl_getinfo($ch, CURLINFO_SPEED_DOWNLOAD),
        'speed_upload' => curl_getinfo($ch, CURLINFO_SPEED_UPLOAD),
        'download_content_length' => curl_getinfo($ch, CURLINFO_CONTENT_LENGTH_DOWNLOAD),
        'upload_content_length' => curl_getinfo($ch, CURLINFO_CONTENT_LENGTH_UPLOAD),
        'starttransfer_time' => curl_getinfo($ch, CURLINFO_STARTTRANSFER_TIME),
        'redirect_time' => curl_getinfo($ch, CURLINFO_REDIRECT_TIME),
        'certinfo' => curl_getinfo($ch, CURLINFO_CERTINFO),
        'primary_ip' => curl_getinfo($ch, CURLINFO_PRIMARY_IP),
        'primary_port' => curl_getinfo($ch, CURLINFO_PRIMARY_PORT),
        'local_ip' => curl_getinfo($ch, CURLINFO_LOCAL_IP),
        'local_port' => curl_getinfo($ch, CURLINFO_LOCAL_PORT),
        'redirect_url' => curl_getinfo($ch, CURLINFO_REDIRECT_URL),
        'request_header' => curl_getinfo($ch, CURLINFO_HEADER_OUT),
    ];
}
```

**Comment by ruflin** [comment]
@im-denisenko Thanks for the detailed research. Can you open a pull request with the code above to see if it builds? The good news seems to be that it has nothing to do with phpunit, the bad news is that there seems to be an issue somewhere in curl in PHP 7.

**Comment by im-denisenko** [comment]
> curl in PHP 7

This week, I'll try to reproduce same error using curl without elastica and submit issue to php.net. Though, if someone here has touch with one of core team member, it'll be much simpler if he can summon him here.

**Comment by ruflin** [comment]
Best would be to mentioned Sterling Hughes as he is the creator of curl, but I couldn't find his Github handle.

**Comment by im-denisenko** [comment]
@laruence Could you have a look please? You were the last one who changed [this line](https://github.com/php/php-src/blob/master/ext/curl/interface.c#L3011) in ext-curl.

**Comment by im-denisenko** [comment]
Reported, closed: https://bugs.php.net/bug.php?id=69831
Let's wait for travis update and revert 7a05f6feaaedf0a6e806a099db3b5e8817f8a04e then.

**Comment by ruflin** [comment]
Cool. Will probably take some time to get the "fix" on travis.
