### ISSUE TITLE
Can't connect to https host - HttpException is thrown.

### ISSUE THREAD

**Issue by otosiol** [ruflin/Elastica#865]
Hello,

I have an issue with Elastica, I can't connect to the elasticsearch database. I got this error :
"Couldn't resolve host 500 Internal Server Error - HttpException"

I tried on local and prod environment but i get the same error.

Elasticsearch-php offical client is working i don't understand what is wrong on Elastica.

Here is my configuration :

$elasticaClient = new \Elastica\Client(array(
            'connections' => array(
                array('host' => 'https://user:*******@aws-us-east-1-portal3.dblayer.com', 'port' => 10050),
                array('host' => 'https://user:*******@aws-us-east-1-portal2.dblayer.com', 'port' => 10062)
            )
        ));

        // Load index
        $elasticaIndex = $elasticaClient->getIndex('twitter');

        // Create the index new
        $elasticaIndex->create(
            array(
                'number_of_shards' => 4,
                'number_of_replicas' => 1,
                'analysis' => array(
                    'analyzer' => array(
                        'indexAnalyzer' => array(
                            'type' => 'custom',
                            'tokenizer' => 'standard',
                            'filter' => array('lowercase', 'mySnowball')
                        ),
                        'searchAnalyzer' => array(
                            'type' => 'custom',
                            'tokenizer' => 'standard',
                            'filter' => array('standard', 'lowercase', 'mySnowball')
                        )
                    ),
                    'filter' => array(
                        'mySnowball' => array(
                            'type' => 'snowball',
                            'language' => 'German'
                        )
                    )
                )
            ),
            true
        );

Someone know what is wrong ?

Thank you

**Comment by im-denisenko** [comment]
@otosiol Hello. Did you try answer I wrote for you on [Stackoverflow](http://stackoverflow.com/a/30537408/4901820)? Is this not working?

**Comment by otosiol** [comment]
@im-denisenko Hello thank you for your answer i just see it. I tried now it still not working but i got another error now : 

Case mismatch between loaded and declared class names: Elastica\Transport\https vs Elastica\Transport\Https
500 Internal Server Error - RuntimeException

**Comment by im-denisenko** [comment]
@otosiol `transport` is case sensitive parameter. Should be exact `Https` (first letter uppercased)

**Comment by otosiol** [comment]
Yes that was exactly my mistake now i set Https it seem better

**Comment by otosiol** [comment]
I still have this error when creating and index:

Unknown error:60
500 Internal Server Error - HttpException

**Comment by im-denisenko** [comment]
@otosiol Well, now it's ssl verification problem. I hope that your server's certificate is not self signed?

I want to see why official client works and Elastica is not. Could you specify, which version of `elasticsearch-php` you used?

Right now you can try the way that explained in [this article](http://unitstep.net/blog/2009/05/05/using-curl-in-php-to-access-https-ssltls-protected-sites/). Applying additional curl options looks like this:
```php
$elasticaClient = new \Elastica\Client([
    'connections' => [
        [
            'transport' => 'Https', 
            'host' => 'user:****@aws-us-east-1-portal3.dblayer.com', 
            'port' => 10050, 
            'curl' => [
                CURLOPT_SSL_VERIFYPEER => false,
            ],
        ],
    ],
]);
```

**Comment by otosiol** [comment]
That Work! Great Man thank you so much. I was using "elasticsearch/elasticsearch": "~1.0", version of Elasticsearch-php and i'm using compose.io with amazon server if someone get the same problem. Thank you again!

**Comment by webdevsHub** [comment]
just for the record: that article recommends `CURLOPT_CAINFO`

:warning: Please do not disable TLS peer verification

**Comment by im-denisenko** [comment]
For newcomers: official client's [documentation](https://github.com/elastic/elasticsearch-php/blob/master/docs/security.asciidoc) it's also good place to go. 
Elastica's syntax slightly different, but all curl options that must be applied stays the same.

I'll close it.

**Comment by ruflin** [comment]
@im-denisenko This documentation is quite good. We should probably also link it on Elastica.io

**Comment by im-denisenko** [comment]
@ruflin We should have our own indeed :) I'll think about that next day.

**Comment by otosiol** [comment]
The same configuration is possible on FOSElastica?

**Comment by otosiol** [comment]
It's seem not working. This is my configuration :

```
fos_elastica:
    clients:
        default:
            connections:
                - { transport: Https, host: user:****@aws-us-east-1-portal3.dblayer.com, port: 10050, curl: {CURLOPT_SSL_VERIFYPEER: false} }
                - { transport: Https, host: user:****@aws-us-east-1-portal1.dblayer.com, port: 10062, curl: {CURLOPT_SSL_VERIFYPEER: false} }
```

Return this error : Unrecognized option "curl" under "fos_elastica.clients.default.connections."

**Comment by im-denisenko** [comment]
You'd better ask this question to developers of FOSElastica.

@merk Could you have a look please?

**Comment by merk** [comment]
It looks like the configuration for the bundle doesnt support passing extra parameters and a PR will need to be sent against FOSElastica to let the options through.

https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/DependencyInjection/Configuration.php#L109-133

A workaround would be to define the basic parameters for each connection and overwrite the service definitions for the connections in services.yml until the extra parameters are supported.
