### ISSUE TITLE
Allow to specify endpoints in \Elastica\Search

### ISSUE THREAD

**Issue by diimpp** [ruflin/Elastica#874]
Hi,

thanks for the great bundle.

I'm using [jpante/elasticsearch-csv](https://github.com/jprante/elasticsearch-csv) plugin, which uses _search_csv endpoint.
So I'm wandering if it's feasible use case and it should be made configurable.

Regards.

**Comment by im-denisenko** [comment]
Hello. Basically, you can perform any request to ES using [raw array query](http://elastica.io/example/raw-array-query.html).

Here is example:

```php
$path = '/ezbxml/_search_csv?keys=ezb:zdbid,ezb:license_period.ezb:available,ezb:isil,ezb:sigel,ezb:license_entry_id,ezb:ill_relevance.ezb:ill_code';
$query = new Elastica\Query(new Elastica\MatchAll());

$client = new Elastica\Client();
$response = $client->request($path, Elastica\Request::GET, $query->toArray());
$data = $response->getData();

var_dump($data['message']); // will output responsed csv
```

Is this suitable answer?

**Comment by diimpp** [comment]
Sure, raw query is certainly solving my issue. Thank you for the snippet. 
I've extended Search class with endpoint property though, as I would like to use ScanAndScroll after that.

Question is would library benefit from configurable endpoints? It doesn't introduce BC and it seems useful. But I don't know if my use case is a popular one as I'm new to ES and for all I know tweaking endpoints might be a rare thing.

Please close the issue, if it's not relevant.

Regards.

**Comment by im-denisenko** [comment]
@diimpp AFAIK you are the first one who requested custom search endpoint :)

I don't use neither this csv plugin or the custom endpoints, hence for now don't see real benefit of that. I would leave this issue opened for a while - maybe someone else will confirm that this feature is useful.

Also cc @ruflin as he knows more.

**Comment by ruflin** [comment]
I'm not aware of lots of other endpoints. I suggest instead of having a general "endpoint" support that we decided plugin by plugin if it should be supported (as we do several others).

**Comment by ruflin** [comment]
Closing as no updates. Please reopen if needed.
