### ISSUE TITLE
Remove Percolate Methods where not compatible anymore

### ISSUE THREAD

**Issue by ruflin** [ruflin/Elastica#883]
Fore more details see https://github.com/ruflin/Elastica/pull/881 and https://github.com/elastic/elasticsearch/commit/b7c4adeea3ce0b8341a5ac66fd83cd676eaade64

**Comment by Tobion** [comment]
Closing as this is fixed since https://github.com/ruflin/Elastica/commit/87b6c3a940d226d7ec65e99e16f027fb0f6aee88#diff-a969b7352ce43aa7d58ef68342c015c6
