### ISSUE TITLE
Can't specify custom Index for each document in Bulk insert

### ISSUE THREAD

**Issue by pasdeloup** [ruflin/Elastica#885]
I made a custom Transformer to select the Index according to specific rules in my Doctrine Entity.
It works, except that it's overwritten before being sent to the server.
In Index.php ,  addDocuments() method, why do you force the index of each Document without checking if it's not already set ?

    public function addDocuments(array $docs)
    {
        foreach ($docs as $doc) {
             if(!$doc->getIndex()) {
                 $doc->setIndex($this->getName()); 
             }
        }
        return $this->getClient()->addDocuments($docs);
    }

**Comment by ruflin** [comment]
@pasdeloup Good point. We should change that. Can you open a pull request?

**Comment by ruflin** [comment]
@pasdeloup I was having a second look at this. If you want not to overwrite the index, you have to use \Elastica\Client->addDocuments(). If you use addDocuments() on and index or even a type, it assumes you specifically want to add all documents to this index (which I think makes sense). addDocuments on Index and Type are only proxy functions.

I will close this Issue as I don't think we should change this behaviour.
