### ISSUE TITLE
Create test setup to prepare Elastica for Elasticasearch 2.0

### ISSUE THREAD

**Issue by ruflin** [ruflin/Elastica#900]
Create a test setup that makes it possible to run Elastica tests with Elasticsearch 2.0 to prepare everything for the release. There are quite a few BC changes.

**Comment by im-denisenko** [comment]
@ruflin We have to compile 2.0 from source or there build is already available?

**Comment by ruflin** [comment]
There is no build available yet, but I hope that the first beta will be out very soon. I suggest to start as soon as the first build is available on the docker registry: https://registry.hub.docker.com/_/elasticsearch/ Alternatively we could create a docker build ourself.

**Comment by yvann** [comment]
A first beta just arrived for your informations :) https://github.com/elastic/elasticsearch/releases

**Comment by ruflin** [comment]
:+1: We should get a build with it ASAP. Does anyone have time?

**Comment by im-denisenko** [comment]
@ruflin I'll look here at this evening.

**Comment by michaelfeinbier** [comment]
@ruflin What exactly has to be done? The current state of this library does not work with 2.0beta2 and I like to help. Do we need a 2.0beta2 docker-container?

**Comment by ruflin** [comment]
@michaelfeinbier Good to hear. @im-denisenko is currently working on this branch here to implement the necessary changes: https://github.com/ruflin/Elastica/tree/elasticsearch-2.0 As you seen in the build (or you don't see it because it is green but actually isn't) a lot of things are broken in 2.0: https://travis-ci.org/ruflin/Elastica/builds/80773741

Yes we need a 2.0beta2 container and we need to refactor the code to work with 2.0. Best is you pull the elasticsearch-2.0 branch and start to open pull requests on this branch.

**Comment by ruflin** [comment]
I now moved the CI build on travis to docker-compose which allowed me to remove ansible and vagrant files. The builds for ES2.0 look promising.

**Comment by ruflin** [comment]
To track the changes I opened an issue here: https://github.com/ruflin/Elastica/issues/946

**Comment by ruflin** [comment]
3.0.0-beat1 was released with es 2.0 support
