### ISSUE TITLE
php7 support, now have fatal Compile Error: Cannot use 'Bool' as class name as it is reserved

### ISSUE THREAD

**Issue by oncesk** [ruflin/Elastica#903]
Hi when i am using elastica with php7 i have fatal error, Compile Error: Cannot use 'Bool' as class name as it is reserved

**Comment by im-denisenko** [comment]
@oncesk Hello. This is already fixed, and classes that incompatible with php7 were deprecated in https://github.com/ruflin/Elastica/issues/825. Use `Elastica\Filter\BoolFilter` and `Elastica\Query\BoolQuery` instead.

**Comment by oncesk** [comment]
thanks, i already use it =)

**Comment by Mohammadtrabelsi** [comment]
In any version this bug has fixed please ?

**Comment by p365labs** [comment]
at the moment the strategy is the same : use Elastica\Query\BoolQuery and not Bool.

**Comment by Mohammadtrabelsi** [comment]
Can you give me more detail
because the bug is in the vender folder and i c'ant change it:
```
in vendor/ruflin/elastica/lib/Elastica/Query/Bool.php at line 13:
class Bool extends BoolQuery
{
}
```

**Comment by p365labs** [comment]
you should use vendor/ruflin/elastica/lib/Elastica/Query/BoolQuery.php

I hope to have understood the problem.

**Comment by Mohammadtrabelsi** [comment]
thanks a lot
