### ISSUE TITLE
No search results

### ISSUE THREAD

**Issue by trueinviso** [ruflin/Elastica#906]
The query generated by the plugin always returns no results for a search. The SQL statement generated by the query:

`SELECT SQL_CALC_FOUND_ROWS wp_posts.* FROM wp_posts WHERE 1=1 AND wp_posts.ID IN (0) AND wp_posts.post_type IN (\'post\', \'page\', \'attachment\', \'events\', \'testimonies\', \'leadership\') AND (wp_posts.post_status = \'publish\' OR wp_posts.post_author = 1 AND wp_posts.post_status = \'private\') ORDER BY wp_posts.post_type ASC LIMIT 0, 500'`

It always has `wp_posts.ID IN (0)` which would seem to always be false?  All the posts are in elasticsearch and I am able to run queries on the data from the command line.  I am new to elasticsearch and this plugin, maybe I am missing something simple?

**Comment by ruflin** [comment]
@trueinviso What is the plugin you are talking about? Elastica is the client for elasticsearch and doesn't generate SQL queries.

**Comment by trueinviso** [comment]
whoops sorry, I meant to post this in Fantastic elastic search, it uses elastica.

**Comment by ruflin** [comment]
Just adding the link to the repo in case someone is looking for it: https://github.com/parisholley/wordpress-fantastic-elasticsearch

In case there is an Elastica issue, let me know.
