### ISSUE TITLE
Missing Context for suggester

### ISSUE THREAD

**Issue by jippi** [ruflin/Elastica#913]
As per https://www.elastic.co/blog/elasticsearch-1-2-adding-context-suggestions it should be possible for a `Elastica\Suggest` or a `Elastica\Suggest\Completion` to include a context - I may be blind, but I can't find the code anywhere for attaching this to either

**Comment by jippi** [comment]
Never mind, it can be set using `setParam` - very low level, don't know if it make sense to expose it as a method at some point :)

**Comment by ruflin** [comment]
@jippi Glad you found it :-) I assume this is a feature that will be used more in the future. Perhaps it still make sense to add a proxy function?

**Comment by jippi** [comment]
I think it makes very good sense to add a proxy function for it :) 

I tried to get for context in the src/ and came up empty - so assumed it wouldn't be possible - by chance I found the param methods :)

**Comment by ruflin** [comment]
@jippi I reopened the issue. Do you have some time to open a pull request with it?
