### ISSUE TITLE
Ensure PHP7 Compatibility

### ISSUE THREAD

**Issue by joshuataylor** [ruflin/Elastica#918]
PHP7 is now in beta, with final release coming November 12th.

Let's fix some issues that are happening as a cause of this.
- [x] Add PHP7 to travis testing
- [x] Fatal error: Cannot use Elastica\Filter\Bool as Bool because 'Bool' is a special class name

**Comment by im-denisenko** [comment]
@joshuataylor Hello. This is already fixed in #825.

**Comment by im-denisenko** [comment]
Closed. Reopen please, if we actually miss something.
