### ISSUE TITLE
Support for Guzzle 6?

### ISSUE THREAD

**Issue by sandermarechal** [ruflin/Elastica#921]
Will support be added for Guzzle 6.x which uses PSR-7?

**Comment by ruflin** [comment]
There were quite a few discussions on PSR-7 in this pull request here: https://github.com/ruflin/Elastica/pull/845

It is probably time to revise this again. I'm not fully up-to-date about PSR-7. Perhaps have a look at the discussion and let us know what your thoughts are.

**Comment by jeskew** [comment]
This would certainly make #948 easier. Is this something that's already being worked on or would you be open to a PR?

**Comment by ruflin** [comment]
@jeskew Definitively open for a PR.

**Comment by Tobion** [comment]
This can be closed since #1023
