### ISSUE TITLE
Unable to connect multiple hosts

### ISSUE THREAD

**Issue by janselr** [ruflin/Elastica#923]
Hi ruflin,

I'm facing one little problem trying to make Elastica to recognize different instances of elasticsearch running on different host but same port,  below what I'm trying to do.

 ```php
$servers = [];

// Adding master node host and port
$servers[] = [ 'host' => getenv('NODE_MASTER_HOST'),'port' => getenv('NODE_MASTER_PORT') ];


//Adding slaves node host and port. actually NODE_SLAVES_COUNTS = 1

for($i = 1; $i <= (int) getenv('NODE_SLAVES_COUNTS'); $i++){
    if (!is_null(getenv('NODE_SLAVES'.$i.'_HOST'))){
        $servers[] = ['host' => getenv('NODE_SLAVE'.$i.'_HOST'), 'port' => getenv('NODE_SLAVE'.$i.'_PORT')];
    }
}

$client = new ElasticClient($servers);


//Setting elasticserach custom cluster name
$settings = new Settings($client);
$settings->set(['cluster.name' => getenv('CLUSTER_NAME')]);

$client = $settings->getClient();
```

How can I get elastica listening on different transports nodes or the same thing elasticsearch instances  ?

**Comment by im-denisenko** [comment]
Hello.

You should use `connections` key of config array to specify multiple servers.
In common, it looks like this:
```php
$client = new Elastica\Client([
    'connectionStrategy' => 'RoundRobin',
    'connections' => [
        [
            'host' => 'xxx.xxx.xxx.xxx',
            'port' => 9200,
        ],
        [
            'host' => 'xxx.xxx.xxx.xxx',
            'port' => 9200,
        ],
    ],
]);
```

Specifically for your case:
```php
//$client = new ElasticClient($servers);
$client = new ElasticClient(['connections' => $servers]);
```

**Comment by im-denisenko** [comment]
Btw.
```php
$settings->set(['cluster.name' => getenv('CLUSTER_NAME')]);
```
This line will change cluster name, using [update settings api](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-update-settings.html).
I guess that cluster name should be specified only once (in your snippet it happens on every request).

**Comment by jxrodr** [comment]
Thanx @im-denisenko 

I've made a little change you state, but I'm still getting the error **Couldn't connect to host, Elasticsearch down?**


I'm using this setup 

```php
$client = new Elastica\Client([
    'connectionStrategy' => 'RoundRobin',
    'connections' => [
        [
            'host' => 'xx.xx.xx.233',
            'port' => 11112,
        ],
        [
            'host' => 'xx.xx.xx.234',
            'port' => 11112,
        ],
    ],
])

```

**Comment by ruflin** [comment]
Did you check if the hosts are reachable for example through curl?

**Comment by frangeris** [comment]
In facing the same issue, test you code @im-denisenko and still getting **Couldn't connect to host, Elasticsearch down?**

So I tried using [official library](https://github.com/elastic/elasticsearch-php) to see if could be something wrong with my ES conf, and test this code...

```php
$hosts = [
    'xxx.xxx.xxx.xxx:9200',
    'xxx.xxx.xxx.xxx:9200',
    'xxx.xxx.xxx.xxx:9200',
];

$client = ClientBuilder::create()
            ->setHosts($hosts)
            ->build();
```
This works, so... where is the issue?

**Comment by ruflin** [comment]
Just some assumptions / ideas:
* I'm not sure if the ClientBuilder actually tests the connection or only prepares everything. Did you also try to make some requests?
* Second is that perhaps Elastica complains already when the first host is down. I have to check this. 

@frangeris Are you able to "curl" all three hosts from the machine the client runs?

**Comment by frangeris** [comment]
@ruflin yep

GET request to my `<ip>:9200` and 200 is the response....

```json
{
  "status": 200,
  "name": "master",
  "cluster_name": "elasticsearch",
  "version": {
    "number": "1.7.1",
    "build_hash": "b88f43fc40b0bcd7f173a1f9ee2e97816de80b19",
    "build_timestamp": "2015-07-29T09:54:16Z",
    "build_snapshot": false,
    "lucene_version": "4.10.4"
  },
  "tagline": "You Know, for Search"
}
```

**Comment by ruflin** [comment]
@frangeris I assume that is the case for all 3? Which version of Elastica are you using?

**Comment by ruflin** [comment]
Closing as no updates were provided. Please reopen in case the issue still exists.
