### ISSUE TITLE
deleteByQuery() "approved" alternative example (?)

### ISSUE THREAD

**Issue by bartclarkson** [ruflin/Elastica#925]
So basically I'm deleting what can be a tremendous amount of tracking data when a user deletes an account.  It seems to me that deleteByQuery is something the core developers want to get rid of, but are finding removal to be problematic.  The main site (https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html) indicates one should pursue a scroll & scan approach.  

Great! But the Internet seems remarkably silent on how to actually *do* this with Elastica.  I'm submitting the following for comment.  It produces the desired outcome.  But perhaps I'm missing the boat with something that Elastica has already abstracted?

```php

$account_id = 123;

$query = new \Elastica\Query\Bool();
$match_all = new \Elastica\Query\MatchAll();
$query->addShould($match_all);
$match_account_terms = new \Elastica\Query\Terms();
$match_account_terms->setTerms('account_id', array($account_id));
$query->addMust($match_account_terms);

// https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html
// https://github.com/elastic/elasticsearch/issues/10067
// deleteByQuery is a memory risk.  That much seems certain, particularly for big deletes.
// deleteByQuery was deprecated, but undeprecated. Core developers are having trouble walking it back.
// Seems the wisest course is not to develop a dependency on it.
// Official website says scan and scoll into bulk api.

// get scan result
// $index = new Index($your_search_client, 'your_type');
$index = $this->fos_elastica_index_site_track;

$scan = $index->search($query, [
    \Elastica\Search::OPTION_SEARCH_TYPE => \Elastica\Search::OPTION_SEARCH_TYPE_SCAN,
    \Elastica\Search::OPTION_SCROLL => '1m',
    \Elastica\Search::OPTION_SIZE => '5000',
]);

// prepare iteration
$scroll = $scan->getResponse()->getScrollId();
$total = $scan->getTotalHits();
$count = 0;

// iterate over batches
while ($count <= $total) {
    // get batch result
    $result = $index->search($query, [
        \Elastica\Search::OPTION_SCROLL_ID => $scroll,
        \Elastica\Search::OPTION_SCROLL => '1m',
    ]);

    // break when done
    if (!count($result->getResults())) {
        break;
    }

    // process batch
    $documents = [];
    foreach ($result->getResults() as $doc) {
        $documents[] = new \Elastica\Document($doc->getId(), $doc->getData(), $doc->getType());
        $count++;
    }

    // delete batch, move on
    $index->deleteDocuments($documents);
    $scroll = $result->getResponse()->getScrollId();

}
```

**Comment by ruflin** [comment]
@bartclarkson This looks good. What I would probably add:
* Directly use ScanAndScroll Implementation: https://github.com/ruflin/Elastica/blob/master/lib/Elastica/ScanAndScroll.php
* The $documents[] part could be made more lightweight in case you only want to delete docs from one type by using $type->deleteDocuments. Also the $doc->getData() can be left out I think. Like this we would have very lightweight docs with just the $id.

Should we put up a test that shows this or put it on Elastica.io? What do you recommend?

**Comment by bartclarkson** [comment]
Inasmuch as deleteByQuery seems to be in a non-favored status, it probably would be good to formalize another approach and associated test.  

Oddly enough, I never interact with the Search object directly, as it is abstracted/injected by FOSElasticaBundle handlers.  So for my immediate purposes, I have simply taken your excellent suggestion to pass an empty array rather than getData(). 

Nevertheless, in the meantime, I have commented out the following untested code in my project for when I can spend some time with it.  I believe it is more along the lines your suggestion to use ScanAndScroll.  Perhaps it might find a place to live in Elastica once perfected. 

```php
public function deleteByScanAndScroll(\Elastica\Search $search, $expiryTime = '1m', $sizePerShard = 1000)
{
    $scanAndScroll = \Elastica\ScanAndScroll($search, $expiryTime, $sizePerShard);
    foreach($scanAndScroll as $shard) {
        $documents = [];
        foreach ($shard->getResults() as $result) {
            $documents[] = new \Elastica\Document($result->getId(), null, $result->getType());
        }
        foreach($search->getIndices() as $index) {
            $index->deleteDocuments($documents);
        }
    }
}
```

**Comment by ruflin** [comment]
@bartclarkson Ok I see, we could even at it as a function of Elastica. Good idea. We could replace the deleteByQuery function with the above code. As deleteByQuery is removed in 2.0 anyways, we could directly do that. @im-denisenko What do you think as you are currently working on 2.0?

**Comment by im-denisenko** [comment]
@bartclarkson @ruflin As far as I know, ES developers keep deleteByQuery because "if we will delete it, every client library will have to implement this functionality on their own". And instead of deletion they just changed used algorithm (internally it uses scan_and_scroll in 2.0). At least this was actual in June when I read their discussion on github. But I'm not sure, I need to recheck this.

**Comment by ruflin** [comment]
I check with the devs what the current status is.

**Comment by ruflin** [comment]
It's going to be a Plugin: https://www.elastic.co/guide/en/elasticsearch/plugins/2.0/plugins-delete-by-query.html

**Comment by MrHash** [comment]
May i suggest that Elastica could benefit from a 'Manager' of sorts where processes like these can be provided. This library provides some useful tools already https://github.com/darklow/ff-elastica-manager

**Comment by ruflin** [comment]
@MrHash Thanks for pointing to the project, I wasn't aware of it. So far the goal of Elastica was to "only" provide base functionality, additional things went into Util. The question I would like to open is if we should integrate something like that to make elastica more powerful or if it is better to keep it separate.

My general approach is most of the time to have smaller modules which can also be used independent. The good thing is if someone is using elastica-manager is, he also gets Elastica itself. The same is true for the fos-bundle. I would like to invite also @darklow to this conversation.

**Comment by bartclarkson** [comment]
@ruflin, for what it's worth, I think the scope of the Elastica project is sized correctly.  It stands in the gap in making Elastic Server extremely convenient for PHP developers.   Providing a bug-free PHP corollary to all posted Elastic API is plenty of responsibility.  This particular thread is right at the edge of "core api" and "implementation decision".

Personally, as a Symfony2 guy, I'm a huge fan of FOS Elastic bundle.  I couldn't possibly be happier about the approach whereby Doctrine entities are translated over to Elastic Server in an ongoing way, or as a wholesale refresh when development changes direction.  The convenience is extraordinary.

Perhaps links to such management projects as the ff-elastica-manager might be linked on main README.md.

Is it presently the plan to provide a wrapper of the upcoming plug-in?  The functionality of the plug-in seems rather modest to me.  The argument for building the scan approach into Elastica's deleteByQuery is not really negated.

**Comment by ruflin** [comment]
@bartclarkson I agree with your statement. One topic that pops up frequently is that people even confuse Elastica with projects using Elastic. It could be helpful to more obviously linke these projects in the README or on Elastica.io. So if someone is looking for more then a client he finds these options also starting from Elastica.

About the plugins: There are already quite a few plugins supported now (like attachment-mapper). I think Elastica should support at least the core plugins which are provided by elasticsearch itself. For third party plugins it would be good to have a general interface in case this is possible. DeleteByQuery seems for me quite a no brainer to have inside as these seems to be  a core functionality.

**Comment by ruflin** [comment]
As an update here: Elastica 3.0.0 still supports deleteByQuery with the same implementation but requires the plugin now. 

I'm not sure what we should do about the docs updates. In case some has a solution or a suggestion, please directly open an issue or PR for it. I will close this issue as it was initially related to deleteByQuery. Please reopen if needed.
