### ISSUE TITLE
Current Travis Builds don't return errors

### ISSUE THREAD

**Issue by ruflin** [ruflin/Elastica#931]
The current travis builds are always green even when there are errors. The reason is that in `make phpunit` all commands are prefixed with - which skips the errors. A solution must be found here.

**Comment by im-denisenko** [comment]
@ruflin I suggest to just drop "-" in all commands, if you can't remember why you added this.

**Comment by ruflin** [comment]
@im-denisenko Sounds good. I'm quite sure because I wanted that all build run also if one fails. Perhaps there is an other solution to have this result without using -.

**Comment by oldskool** [comment]
Phpunit should continue running on errors (or failed tests) and complete it's build as long as you don't pass the `--stop-on-error` (or `--stop-on-failure`) flag.

**Comment by ruflin** [comment]
@oldskool PHPunit keeps running, but as we run phpunit multiple time the Makefile stops executing commands after the first error.
