### ISSUE TITLE
Split Filters aggregation

### ISSUE THREAD

**Issue by ewgRa** [ruflin/Elastica#936]
In elasticsearch we can't mix anonymous and named filters in one query

Such queries is not possible:
```
      "filters" : {
        "filters" : {
          0 :   { "term" : { "body" : "error"   }},
          "warnings" : { "term" : { "body" : "warning" }}
        }
      },
```

Answer buckets always will be or all anonymous, or all named.

My suggestion is to split Filters on NamedFilters and AnonymousFilters and deprecate Filters.

Now code allow add named and anonymous filters simultaneously, that give unexpected results.

Any comments?

**Comment by im-denisenko** [comment]
@ewgRa If array key will be quoted will it be a valid filter name?

**Comment by ruflin** [comment]
@ewgRa In case elasticsearch does not allow the mix, I suggest we also prevent it in Elastica and give the user an exception.

**Comment by ewgRa** [comment]
@im-denisenko 

Yes, it is valid:

```
      "filters" : {
        "filters" : {
          "0" :   { "term" : { "body" : "error"   }},
          "warnings" : { "term" : { "body" : "warning" }}
        }
      },
```
In buckets there will be "0" key. I already add this case to tests in #935.
If you use arrays with keys - you must use string as key. If this is not an associative array - it will be anonymous buckets.

Just fyi: "e'räro\"rs" also valid, becomes in results "e'räro"rs"

@ruflin but in exists class? you don't want to split it to be close to Elasticsearch?

**Comment by ewgRa** [comment]
@ruflin but in exists class? you don't want to split it to be close to Elasticsearch?

**Comment by ruflin** [comment]
@ewgRa No I would not split the class, but throw an error before elasticsearch has to do it. This is more convenience for the person that implements it. Instead of getting a response exception and having to figure out what is going on, it is already thrown before the request is sent and is very specific.

**Comment by ewgRa** [comment]
PR for prevent mixing keys - #939
