### ISSUE TITLE
extended_bounds in Elastica\Aggregation\DateHistogram 

### ISSUE THREAD

**Issue by markeilander** [ruflin/Elastica#942]
Is it possible to implement the extende_bounds paramers as descriped in https://www.elastic.co/guide/en/elasticsearch/guide/current/_returning_empty_buckets.html

**Comment by ruflin** [comment]
@markeilander It should be quite easy to add it to: https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Aggregation/DateHistogram.php Feel free to open a pull request.

As long as there is no proxy function, you can use it by calling setParam and passing the arguments directly.

**Comment by markeilander** [comment]
Done..

**Comment by ruflin** [comment]
@markeilander I think there went something wrong in your changes. See my comment in the pull request.
