### ISSUE TITLE
Support IAM credentials

### ISSUE THREAD

**Issue by joshuaspence** [ruflin/Elastica#948]
I would like to use Amazon's Elasticsearch with IAM roles configured to allow access to the cluster. According to http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-gsg-upload-data.html:

> Standard clients, such as curl, cannot perform the request signing that is required of identity-based access policies. You must use an IP address-based access policy that allows anonymous access to successfully perform the instructions for this step.

**Comment by ruflin** [comment]
As a reference: http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html

**Comment by jeskew** [comment]
The AWS SDK for PHP also exposes a class that can sign an arbitrary PSR-7 request (as detailed [here](https://github.com/aws/aws-sdk-php/issues/671#issuecomment-120666137)). @ruflin, would you be open to a PR that added an integration for this behavior if it meant adding a dependency on the SDK?

**Comment by ruflin** [comment]
As discussed on Gitter: Lets do the Guzzle 6 implementation first and lets check what is needed on top.

**Comment by ruflin** [comment]
@jeskew Any updates here?

**Comment by jeskew** [comment]
@ruflin I sent a pull request bumping the Guzzle dependency to v6 (#1023), which should aid in getting this out the door.

**Comment by lukevers** [comment]
Hey guys,

I'm also very interested in this as well. Has anyone started working on this anywhere, or has there only been talk about it?

**Comment by ruflin** [comment]
@jeskew did some cleanup and improvements to get the foundation for this. But not sure if anyone continued the actual implementation. @jeskew ?

**Comment by devfubar** [comment]
A rough ETA would be great so I can know how much effort to put into a work around or migrate from the bundle if its not going to be supported

**Comment by ruflin** [comment]
Implemented in https://github.com/ruflin/Elastica/pull/1056 This will be part of the next release.
