### ISSUE TITLE
Simplify usage of credentials with elasticsearch

### ISSUE THREAD

**Issue by ruflin** [ruflin/Elastica#949]
Currently to use credentials with elasticsearch, the following is needed:

```
$client = new \Elastica\Client(
  array(
    'host' => 'es.host.com',
    'port' => '9200',
    'headers' => array(
        'Authorization ' =>  'Basic ' . base64_encode('admin' . ':' . '1234')
    )
  )
);
```

This should be simplified through introducing username and password params in connections.

**Comment by juuuuuu** [comment]
Maybe this issue could be closed.

**Comment by ruflin** [comment]
@juuuuuu Yep, closing. Thanks for the ping.
