### ISSUE TITLE
_timestamp enable support in mapping

### ISSUE THREAD

**Issue by savdeep** [ruflin/Elastica#964]
I was trying to find out  use timestamp with intial index mapping which generally is done by put request to elasticsearch as "_timestamp" : { "enabled" : true , "store" : "yes"} 

Is there any way to do this in elastica?

**Comment by ruflin** [comment]
For the Mapping, there is currently not proxy function for _timestamp. But using Mapping->setParam you can set all params by just passing an array to it: https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Type/Mapping.php

For a later reference I put here also the es docs link: https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-timestamp-field.html

It would be nice to have a proxy function for this in Elastica. So feel free to also open a pull request with it.

In case the above doesn't work as expected, let me know.

**Comment by ruflin** [comment]
Closing as https://github.com/ruflin/Elastica/pull/965 was merged.
