### ISSUE TITLE
Wrong parameters for Exception

### ISSUE THREAD

**Issue by JunniH** [ruflin/Elastica#970]
I was running Elastica just fine on a hosting with Elasticsearch 1.4.2, but running versions 2.0.0 now on a VPS and getting the following error while creating an index:

Fatal error: Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in /gifthings/lib/vendor/Elastica/Exception/ResponseException.php on line 34

Correct to assume that this will be resolved with issue #946 ?

Thanks for feedback!

Best regards,
Junni

**Comment by Lumbendil** [comment]
You're right, there are some major changes, the bug you mentioned has been solved in the 2.0 branch as far as I know, but it isn't yet complete.

**Comment by eit** [comment]
Exactly, the master branch is not ready yet for elasticsearch 2.0 version. I think we should wait for 2.0 branch be complete.

**Comment by ruflin** [comment]
@JunniH There are quite a lot of changes in 2.0, now exception format is only one. Waiting for 2.0 branch to be merged is a good idea. Help to get it in faster is always welcome.

**Comment by JunniH** [comment]
Thanks for the answers!

**Comment by ruflin** [comment]
Closing this as 3.0.0-beta1 was released.
