### ISSUE TITLE
PHP 7 broken

### ISSUE THREAD

**Issue by marguse** [ruflin/Elastica#971]
As PHP 7 has reserved keyword "bool" but elastica has class "Bool" and it breaks. Any plan to add php 7 support?

Reserved keywords:
http://php.net/manual/en/reserved.other-reserved-words.php

Thanks.

**Comment by ruflin** [comment]
@marguse This issue is already fixed. As you can see here, under PHP 7 you must use BoolQuery: https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Query/Bool.php#L7 Same for all other conflicting classes.

Closing this issue. Please reopen if this is still an issue.
