### ISSUE TITLE
"Error: Wrong parameters for Exception(..)" - while using Elastica with FosElastica

### ISSUE THREAD

**Issue by lakhman** [ruflin/Elastica#974]
Hi,

I'm having the same issue as described here in this stackoverflow question (after upgrading elasticsearch from 1.7.3 => 2.0):

```
Error: Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]])
```

http://stackoverflow.com/questions/33229423/error-in-responseexeption-while-populating-foselasticabundle-symfony2

I was using elasticsearch 1.7.3 with foselasticabundle, but after upgrading elasticsearch to 2.0, and running `console fos:elastica:populate --no-debug`, I get the following error & trace:

```
~/Sites/webapp $ console fos:elastica:populate --no-debug

Resetting app

PHP Fatal error:  Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in /Users/user/Sites/webapp/vendor/ruflin/elastica/lib/Elastica/Exception/ResponseException.php on line 34
PHP Stack trace:
PHP   1. {main}() /Users/user/Sites/webapp/bin/console:0
PHP   2. Symfony\Component\Console\Application->run() /Users/user/Sites/webapp/bin/console:27
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/user/Sites/webapp/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:120
PHP   4. Symfony\Component\Console\Application->doRun() /Users/user/Sites/webapp/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
PHP   5. Symfony\Component\Console\Application->doRunCommand() /Users/user/Sites/webapp/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:189
PHP   6. Symfony\Component\Console\Command\Command->run() /Users/user/Sites/webapp/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:846
PHP   7. FOS\ElasticaBundle\Command\PopulateCommand->execute() /Users/user/Sites/webapp/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:256
PHP   8. FOS\ElasticaBundle\Command\PopulateCommand->populateIndex() /Users/user/Sites/webapp/vendor/friendsofsymfony/elastica-bundle/Command/PopulateCommand.php:124
PHP   9. FOS\ElasticaBundle\Index\Resetter->resetIndex() /Users/user/Sites/webapp/vendor/friendsofsymfony/elastica-bundle/Command/PopulateCommand.php:144
PHP  10. Elastica\Index->create() /Users/user/Sites/webapp/vendor/friendsofsymfony/elastica-bundle/Index/Resetter.php:100
PHP  11. Elastica\Index->delete() /Users/user/Sites/webapp/vendor/ruflin/elastica/lib/Elastica/Index.php:257
PHP  12. Elastica\Index->request() /Users/user/Sites/webapp/vendor/ruflin/elastica/lib/Elastica/Index.php:183
PHP  13. FOS\ElasticaBundle\Elastica\Client->request() /Users/user/Sites/webapp/vendor/ruflin/elastica/lib/Elastica/Index.php:496
PHP  14. Elastica\Client->request() /Users/user/Sites/webapp/vendor/friendsofsymfony/elastica-bundle/Elastica/Client.php:47
PHP  15. Elastica\Request->send() /Users/user/Sites/webapp/vendor/ruflin/elastica/lib/Elastica/Client.php:621
PHP  16. Elastica\Transport\Http->exec() /Users/user/Sites/webapp/vendor/ruflin/elastica/lib/Elastica/Request.php:171
PHP  17. Elastica\Exception\ResponseException->__construct() /Users/user/Sites/webapp/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php:159
PHP  18. Exception->__construct() /Users/user/Sites/webapp/vendor/ruflin/elastica/lib/Elastica/Exception/ResponseException.php:34

Fatal error: Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in /Users/user/Sites/webapp/vendor/ruflin/elastica/lib/Elastica/Exception/ResponseException.php on line 34

Call Stack:
    0.0006     235128   1. {main}() /Users/user/Sites/webapp/bin/console:0
    0.0465    3396792   2. Symfony\Component\Console\Application->run() /Users/user/Sites/webapp/bin/console:27
    0.0500    3612624   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/user/Sites/webapp/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:120
    0.1798   11821888   4. Symfony\Component\Console\Application->doRun() /Users/user/Sites/webapp/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
    0.1801   11822808   5. Symfony\Component\Console\Application->doRunCommand() /Users/user/Sites/webapp/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:189
    0.1811   11872392   6. Symfony\Component\Console\Command\Command->run() /Users/user/Sites/webapp/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:846
    0.1907   12786088   7. FOS\ElasticaBundle\Command\PopulateCommand->execute() /Users/user/Sites/webapp/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:256
    0.1908   12787344   8. FOS\ElasticaBundle\Command\PopulateCommand->populateIndex() /Users/user/Sites/webapp/vendor/friendsofsymfony/elastica-bundle/Command/PopulateCommand.php:124
    0.1913   12807512   9. FOS\ElasticaBundle\Index\Resetter->resetIndex() /Users/user/Sites/webapp/vendor/friendsofsymfony/elastica-bundle/Command/PopulateCommand.php:144
    0.1920   12884920  10. Elastica\Index->create() /Users/user/Sites/webapp/vendor/friendsofsymfony/elastica-bundle/Index/Resetter.php:100
    0.1920   12885152  11. Elastica\Index->delete() /Users/user/Sites/webapp/vendor/ruflin/elastica/lib/Elastica/Index.php:257
    0.1922   12919776  12. Elastica\Index->request() /Users/user/Sites/webapp/vendor/ruflin/elastica/lib/Elastica/Index.php:183
    0.1922   12920352  13. FOS\ElasticaBundle\Elastica\Client->request() /Users/user/Sites/webapp/vendor/ruflin/elastica/lib/Elastica/Index.php:496
    0.1926   12962168  14. Elastica\Client->request() /Users/user/Sites/webapp/vendor/friendsofsymfony/elastica-bundle/Elastica/Client.php:47
    0.1927   12964968  15. Elastica\Request->send() /Users/user/Sites/webapp/vendor/ruflin/elastica/lib/Elastica/Client.php:621
    0.1937   13088032  16. Elastica\Transport\Http->exec() /Users/user/Sites/webapp/vendor/ruflin/elastica/lib/Elastica/Request.php:171
    0.1989   13198928  17. Elastica\Exception\ResponseException->__construct() /Users/user/Sites/webapp/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php:159
    0.1989   13199008  18. Exception->__construct() /Users/user/Sites/webapp/vendor/ruflin/elastica/lib/Elastica/Exception/ResponseException.php:34


[Symfony\Component\Debug\Exception\FatalErrorException]                                                   
Error: Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]])
```

It seems there is a pull request outstanding here: https://github.com/ruflin/Elastica/pull/968

Any ideas on an ETA for 2.0?

**Comment by ruflin** [comment]
There are still some open issue with 2.0 For more details see here: https://github.com/ruflin/Elastica/issues/946 Help to get the last issues fixes is always welcome.

**Comment by ruflin** [comment]
@Lakhman Thanks for linking the issue. I also commented there.

**Comment by Lakhman** [comment]
Thanks!

**Comment by ewgRa** [comment]
This must be fixed by https://github.com/ruflin/Elastica/commit/41a7a2075837320bc9bd3bca4150e05a1ec9a115

Also commit has typo that will be fixed by #978

**Comment by lakhman** [comment]
How can I test this with FOSElastica? I wanted to use FOSElastica with Elasticsearch 2.0 (to test this upgrade to 2.0).
I tried forking FOSElastica and updating the elastica version constraint to 3.0.0-beta1, but this didn't work. 

How can I use FOSElastica with these new changes from ruflin/elastica?

**Comment by redayoub** [comment]
Hi, I'm having the same error. Any help please ?

Thanks

**Comment by AliHichem** [comment]
@redayoub this is already fixed , you should make your composer.json use "dev-master" to get the fix.

**Comment by ruflin** [comment]
Please be aware that one more potential is pushed here: https://github.com/ruflin/Elastica/pull/1016 Closing this issue as fix was already merged. Please reopen if needed.

**Comment by redayoub** [comment]
Thanks @AliHichem

**Comment by Badlapje** [comment]
get this issue now, even though everything worked fine with version 2.3.2 up until now (as it should, given that support for 2.x is now ok with the bundle).  Here's my stack trace;

> Exception trace:
 () at /home/vagrant/Code/RoeselareVrijwilligt/VrijwilligersTool/vendor/ruflin/elastica/lib/Elastica/Exception/ResponseException.php:34
 Exception->__construct() at /home/vagrant/Code/RoeselareVrijwilligt/VrijwilligersTool/vendor/ruflin/elastica/lib/Elastica/Exception/ResponseException.php:34
 Elastica\Exception\ResponseException->__construct() at /home/vagrant/Code/RoeselareVrijwilligt/VrijwilligersTool/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php:159
 Elastica\Transport\Http->exec() at /home/vagrant/Code/RoeselareVrijwilligt/VrijwilligersTool/vendor/ruflin/elastica/lib/Elastica/Request.php:171
 Elastica\Request->send() at /home/vagrant/Code/RoeselareVrijwilligt/VrijwilligersTool/vendor/ruflin/elastica/lib/Elastica/Client.php:621
 Elastica\Client->request() at /home/vagrant/Code/RoeselareVrijwilligt/VrijwilligersTool/vendor/friendsofsymfony/elastica-bundle/Elastica/Client.php:47
 FOS\ElasticaBundle\Elastica\Client->request() at /home/vagrant/Code/RoeselareVrijwilligt/VrijwilligersTool/vendor/ruflin/elastica/lib/Elastica/Index.php:496
 Elastica\Index->request() at /home/vagrant/Code/RoeselareVrijwilligt/VrijwilligersTool/vendor/ruflin/elastica/lib/Elastica/Index.php:183
 Elastica\Index->delete() at /home/vagrant/Code/RoeselareVrijwilligt/VrijwilligersTool/vendor/ruflin/elastica/lib/Elastica/Index.php:257
 Elastica\Index->create() at /home/vagrant/Code/RoeselareVrijwilligt/VrijwilligersTool/vendor/friendsofsymfony/elastica-bundle/Index/Resetter.php:100
 FOS\ElasticaBundle\Index\Resetter->resetIndex() at /home/vagrant/Code/RoeselareVrijwilligt/VrijwilligersTool/vendor/friendsofsymfony/elastica-bundle/Command/PopulateCommand.php:144
 FOS\ElasticaBundle\Command\PopulateCommand->populateIndex() at /home/vagrant/Code/RoeselareVrijwilligt/VrijwilligersTool/vendor/friendsofsymfony/elastica-bundle/Command/PopulateCommand.php:124
 FOS\ElasticaBundle\Command\PopulateCommand->execute() at /home/vagrant/Code/RoeselareVrijwilligt/VrijwilligersTool/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /home/vagrant/Code/RoeselareVrijwilligt/VrijwilligersTool/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:807
 Symfony\Component\Console\Application->doRunCommand() at /home/vagrant/Code/RoeselareVrijwilligt/VrijwilligersTool/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:186
 Symfony\Component\Console\Application->doRun() at /home/vagrant/Code/RoeselareVrijwilligt/VrijwilligersTool/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/vagrant/Code/RoeselareVrijwilligt/VrijwilligersTool/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:117
 Symfony\Component\Console\Application->run() at /home/vagrant/Code/RoeselareVrijwilligt/VrijwilligersTool/bin/console:29
