### ISSUE TITLE
Amazon Elasticsearch

### ISSUE THREAD

**Issue by analogmultimedia** [ruflin/Elastica#984]
Is it possiple to Connect to an Amazon Elasticsearch with Elastica? When i use the "AWS Account access policy". How can I set the header?

**Comment by ruflin** [comment]
@fritzdacat Did you find a solution?

**Comment by mablae** [comment]
Maybe this could be wrapped into some kind of Auth Layer since also Basic Auth is now possible?

**Comment by ruflin** [comment]
@mablae Best is to directly have the conversation here: https://github.com/ruflin/Elastica/issues/948
