### ISSUE TITLE
Can't find Indices query 

### ISSUE THREAD

**Issue by Nihaux** [ruflin/Elastica#991]
Hasn't it been implemented or am I missing something ?
https://www.elastic.co/guide/en/elasticsearch/reference/1.6/query-dsl-indices-query.html

**Comment by ruflin** [comment]
@Nihaux The indicies query is not implemented yet. You can always use not implemented queries by adding your raw array (see here for more details): http://elastica.io/example/raw-array-query.html

Or the other method is opening a PR with the query inside. Have a look on how the existing queries are implemented.

**Comment by Tobion** [comment]
Closing because the query exists now https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Query/Indices.php but is deprecated since ES 5 anyway.
