### ISSUE TITLE
Does elastica requires symphony?

### ISSUE THREAD

**Issue by jdc18** [ruflin/Elastica#992]
I run composer and I go this  symfony  depencies

  - Installing guzzlehttp/guzzle (6.1.1)
  - Installing symfony/filesystem (v2.7.7)  
  - Installing symfony/config (v2.7.7)
  - Installing symfony/dependency-injection (v2.7.7)
  - Installing symfony/finder (v2.7.7)     
  - Installing symfony/translation (v2.7.7)   
  - Installing symfony/yaml (v2.7.7)
symfony/process (v2.7.6 => v2.7.7)
  - Installing symfony/console (v2.7.7)
  - Installing doctrine/orm (v2.5.2)

This dependencies might be from something else.

**Comment by mablae** [comment]
No, there is a dedicated bundle to integrate this standalone lib into a Symfony2 Project: https://github.com/FriendsOfSymfony/FOSElasticaBundle

Whatever you did, (I asume you ran `composer update`) has nothing to do with the deps of this package. For better unterstanding, how things work take a look at the composer.json of this Project: 

```
    "require": {
        "php": ">=5.3.3",
        "psr/log": "~1.0"
    },
    "require-dev": {
        "guzzlehttp/guzzle": "5.3.*"
    },
```

As you can see, the only dependecy is PSR/Log
